/* A5c2a single audio manager: SFX assets are lazy-decoded after user activation. */
(() => {
  "use strict";
  const DEBUG = location.hash.toLowerCase().includes("debug"), KEY = "trust_me_bro_audio_v1";
  const names = ["coin","ramp","flip","land","crane","barrel","collapse-warning","collapse-fall","pallet","door","checkpoint","finish","purchase","equip"];
  const files = Object.fromEntries(names.map(n => [n, `audio/sfx/${n}.ogg`]));
  let ctx, music, sfx, limiter, ceiling, musicMeter, sfxMeter, active = 0, musicSources = 0, unlocked = false, paused = false, platform = true;
  const faults={coinTrigger:false,doorTrigger:false,bypass:false,warningGain:false,ignoreVisibility:false,decodeThrow:false,musicToSfx:false};
  const buffers = new Map(), failed = new Set(), log = [];
  let levels = { music: .55, sfx: .8 }; try { levels = { ...levels, ...JSON.parse(localStorage.getItem(KEY) || "{}") }; } catch (_) {}
  const clamp = v => Math.max(0, Math.min(1, Number(v) || 0));
  function graph() { if (ctx) return ctx; const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;ctx=new A();music=ctx.createGain();sfx=ctx.createGain();limiter=ctx.createDynamicsCompressor();ceiling=ctx.createWaveShaper();musicMeter=ctx.createAnalyser();sfxMeter=ctx.createAnalyser();for(const a of [musicMeter,sfxMeter]){a.fftSize=2048;a.smoothingTimeConstant=0}limiter.threshold.value=-1;limiter.knee.value=0;limiter.ratio.value=20;limiter.attack.value=.001;limiter.release.value=.08;const curve=new Float32Array(65536);for(let i=0;i<curve.length;i++)curve[i]=Math.max(-.88,Math.min(.88,i/(curve.length-1)*2-1));ceiling.curve=curve;ceiling.oversample="4x";music.connect(musicMeter);musicMeter.connect(ctx.destination);sfx.connect(limiter);limiter.connect(ceiling);ceiling.connect(sfxMeter);sfxMeter.connect(ctx.destination);apply();return ctx; }
  function apply(){if(!ctx)return;const mute=paused||!platform;music.gain.setValueAtTime(mute?0:clamp(levels.music),ctx.currentTime);sfx.gain.setValueAtTime(mute?0:clamp(levels.sfx),ctx.currentTime);}
  async function unlock(){const c=graph();if(!c)return;try{await c.resume();unlocked=c.state==="running";apply();}catch(_){}}
  async function load(name){if(buffers.has(name)||failed.has(name))return buffers.get(name);try{const r=await fetch(files[name],{cache:"force-cache"});if(!r.ok)throw Error(`sfx ${r.status}`);const b=await graph().decodeAudioData(await r.arrayBuffer());buffers.set(name,b);return b;}catch(e){failed.add(name);if(DEBUG&&faults.decodeThrow)queueMicrotask(()=>{throw e});return null;}}
  async function play(name,detail={}){if(DEBUG&&((faults.coinTrigger&&name==="coin")||(faults.doorTrigger&&name==="door")))return false;if(!files[name]||!unlocked||paused||!platform)return false;const b=await load(name);if(!b||paused||!platform)return false;try{const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=b;gain.gain.value=name==="collapse-warning"?(faults.warningGain?.02:1):(name==="coin"?.62:.82);source.connect(gain);gain.connect(sfx);source.onended=()=>{active=Math.max(0,active-1)};active++;source.start();if(DEBUG)log.push({name,gameTime:detail.gameTime??null,frame:detail.frame??null,at:performance.now()});return true;}catch(_){return false;}}
  function tone(channel="music",seconds=.8){if(!DEBUG)return false;const c=graph();if(!c||!unlocked)return false;const o=c.createOscillator(),g=c.createGain(),bus=channel==="sfx"?sfx:music;o.frequency.value=220;g.gain.value=.18;o.connect(g);g.connect(bus);if(channel==="music")musicSources++;else active++;o.onended=()=>{if(channel==="music")musicSources=Math.max(0,musicSources-1);else active=Math.max(0,active-1)};o.start();o.stop(c.currentTime+seconds);return true;}
  function sample(channel="sfx"){const a=channel==="music"?musicMeter:sfxMeter;if(!a)return {peak:0,rms:0,db:-Infinity};const v=new Float32Array(a.fftSize);a.getFloatTimeDomainData(v);let peak=0,sum=0;for(const x of v){peak=Math.max(peak,Math.abs(x));sum+=x*x}const rms=Math.sqrt(sum/v.length);return {peak,rms,db:rms?20*Math.log10(rms):-Infinity};}
  function setLevel(channel,value){if(!(channel in levels))return;levels[channel]=clamp(value);try{localStorage.setItem(KEY,JSON.stringify(levels))}catch(_){}apply();syncUI();}
  function setPaused(v){paused=!!v;apply()} function setPlatform(v){platform=!!v;apply()}
  function syncUI(){for(const k of ["music","sfx"]){const e=document.getElementById(`a5-${k}`);if(e)e.value=String(levels[k]);}}
  const labels={en:["MUSIC","SFX"],tr:["MÜZİK","EFEKT"],ru:["МУЗЫКА","ЭФФЕКТЫ"]};
  function language(lang){const v=labels[lang]||labels.en,ls=document.querySelectorAll("#a5-audio-controls label");if(ls[0])ls[0].firstChild.data=v[0]+" ";if(ls[1])ls[1].firstChild.data=v[1]+" ";}
  function installUI(){const host=document.createElement("div");host.id="a5-audio-controls";host.style.cssText="position:fixed;right:54px;top:8px;z-index:31;background:#101820dd;color:#fff;padding:5px 8px;border-radius:7px;font:11px system-ui";host.innerHTML=`<label>MUSIC <input id="a5-music" aria-label="Music volume" type="range" min="0" max="1" step="0.05"></label> <label>SFX <input id="a5-sfx" aria-label="SFX volume" type="range" min="0" max="1" step="0.05"></label>`;document.body.appendChild(host);for(const k of ["music","sfx"])host.querySelector(`#a5-${k}`).addEventListener("input",e=>setLevel(k,e.target.value));syncUI();}
  ["pointerdown","touchstart","keydown"].forEach(type=>addEventListener(type,unlock,{passive:true,once:true}));
  document.addEventListener("tmb:sfx",e=>play(e.detail?.name,e.detail));document.addEventListener("tmb:audio-pause",e=>setPaused(e.detail!==false));document.addEventListener("tmb:audio-platform",e=>setPlatform(e.detail!==false));
  document.addEventListener("tmb:audio-language",e=>language(e.detail));
  document.addEventListener("visibilitychange",()=>{if(!faults.ignoreVisibility)setPaused(document.hidden)});addEventListener("blur",()=>setPaused(true));addEventListener("focus",()=>{if(!document.hidden)setPaused(false)});addEventListener("DOMContentLoaded",installUI);
  function mutate(name,value=true){if(!DEBUG||!(name in faults))return false;faults[name]=!!value;if(ctx&&name==="bypass"){try{sfx.disconnect();limiter.disconnect();ceiling.disconnect();sfx.connect(value?sfxMeter:limiter);if(!value){limiter.connect(ceiling);ceiling.connect(sfxMeter)}}catch(_){}}if(ctx&&name==="musicToSfx"){try{music.disconnect();music.connect(value?sfxMeter:musicMeter);if(!value)musicMeter.connect(ctx.destination)}catch(_){}}return true;}
  if(DEBUG)window.__tmbAudio={play,unlock,setLevel,setPaused,setPlatform,tone,sample,mutate,state:()=>({context:ctx?.state||"none",active,unlocked,paused,platform,levels:{...levels},failed:[...failed],log:[...log],limiter:!faults.bypass,musicSources})};
})();
