from pathlib import Path
import hashlib,json,difflib
r=Path.cwd();o=Path((r/'03-test/a4b2c-run-path.txt').read_text(encoding='utf-8-sig').strip());b=o/'pre/02-kod';rows=[]
def check(label,ok):
 rows.append(dict(label=label,pass_=ok))
 if not ok: raise AssertionError(label)
old=(b/'js/a12-campaign.js').read_bytes();current=(r/'js/a12-campaign.js').read_bytes();expected=old.replace(b'if (/^M0/.test(id)) return !!ROUTES[id] && (id === "M01" || !!profile.progressByRoute.M01?.completed);',b'if (/^M0/.test(id)) return !!ROUTES[id] && (id === "M01" || !!profile.progressByRoute[`M0${Number(id.slice(1))-1}`]?.completed);').replace(b'["M02","M01"]',b'["M04","M03","M02","M01"]').replace(b'==="magma"?["M01","M02"]',b'==="magma"?["M01","M02","M03","M04"]').replace(b'unlocked:Object.fromEntries(["F01","F02","F03","F04"].map',b'unlocked:Object.fromEntries((route.worldId==="magma"?["M01","M02","M03","M04"]:["F01","F02","F03","F04"]).map').replace(b'      profile.selectedWorldId = pendingWorldId;',b'      if (pendingWorldId === "magma" && !/^M0/.test(id || "")) id = firstRouteForWorld("magma");\r\n      else if (profile.selectedWorldId === "magma" && pendingWorldId !== "magma" && /^M0/.test(id || "")) id = firstRouteForWorld(pendingWorldId);\r\n      profile.selectedWorldId = pendingWorldId;')
check('a12 only approved MAGMA chain/world-transition/debug-lock substitutions; all other bytes identical',current==expected)
for f in ['index.html','03-test/lib/bot-s-drive.cjs','03-test/lib/bot-w.cjs','03-test/lib/bot-magma.cjs','03-test/lib/magma-b-probe.cjs','03-test/t2-b-dynamic.cjs','03-test/t2-coins.spec.cjs','03-test/parkour-tur1.spec.cjs','03-test/tn-a12.spec.cjs','03-test/t1b-bot-s.spec.cjs','03-test/t2-chief.spec.cjs']+[str(p.relative_to(b)).replace('\\','/') for p in (b/'03-test/route-inputs').glob('*.json')]:check(f+' bytes unchanged',(r/f).read_bytes()==(b/f).read_bytes())
expected=(b/'03-test/lib/magma-probe.cjs').read_bytes().replace(b'M01:{completed:true}',b'M01:{completed:true},M02:{completed:true},M03:{completed:true}');check('probe fixture change only',(r/'03-test/lib/magma-probe.cjs').read_bytes()==expected)
expected=(b/'03-test/tn-a4.spec.cjs').read_bytes().replace(b"__TMB_A12__.renderWorldOnRoute('magma','M01');__TMB_A12__.finish();",b"for(const prerequisite of ['M01','M02','M03']){__TMB_A12__.renderWorldOnRoute('magma',prerequisite);__TMB_A12__.finish();}");check('old tn-a4 prefix preserved except sequential unlock fixture',(r/'03-test/tn-a4.spec.cjs').read_bytes().startswith(expected))
prior=Path((r/'03-test/a4b2b-run-path.txt').read_text(encoding='utf-8-sig').strip());check('manifest unchanged since approved 2b',(prior/'m-manifest.json').read_bytes()==(r.parent/'01-tasarim/coin-T2/m-manifest.json').read_bytes())
files=['index.html','js/a12-campaign.js','03-test/tn-a4.spec.cjs','03-test/t2-coins.spec.cjs']+[str(p.relative_to(r)).replace('\\','/') for p in (r/'03-test/route-inputs').glob('M*.json')]+[str(p.relative_to(r)).replace('\\','/') for p in (r/'03-test/lib').glob('*') if p.is_file()]
sha={f:hashlib.sha256((r/f).read_bytes()).hexdigest() for f in files}
(o/'integrity-c.json').write_text(json.dumps(rows,indent=2),encoding='utf8');(o/'final-sha.json').write_text(json.dumps(sha,indent=2),encoding='utf8')
diff=''.join(difflib.unified_diff(old.decode('utf8').splitlines(True),current.decode('utf8').splitlines(True),fromfile='pre/a12-campaign.js',tofile='final/a12-campaign.js'));(o/'a12.diff').write_text(diff,encoding='utf8')
print(json.dumps({'checks':len(rows),'pass':True,'a12':sha['js/a12-campaign.js']}))
