const fs=require('fs'),path=require('path'),http=require('http'),{chromium}=require('playwright');
const {runAftermath}=require('./lib/bot-aftermath.cjs'),{runWalking}=require('./lib/bot-w.cjs');
const root=path.resolve(__dirname,'..'),out=fs.readFileSync(path.join(__dirname,'a4c2a-run-path.txt'),'utf8').trim();
(async()=>{const server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/, '')||'index.html';fs.readFile(path.join(root,rel),(e,b)=>{res.statusCode=e?404:200;res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':'application/octet-stream');res.end(e?'missing':b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true});
try{const rows=[];for(const id of ['A01','A02']){const runs=[];for(let n=0;n<(process.env.M_QUICK?'1':2);n++){const page=await browser.newPage({viewport:{width:1280,height:720}});await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await page.addInitScript(()=>{let seed=0x1a2b3c4d,now=0;Math.random=()=> (seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296;Date.now=()=>Math.floor(now);Object.defineProperty(performance,'now',{value:()=>now});window.__tmbAdvanceTime=ms=>now+=ms;localStorage.setItem('trust_me_bro_campaign_profile_v1',JSON.stringify({progressByRoute:{A01:{completed:true}}}));});await page.goto('http://127.0.0.1:'+server.address().port+'/index.html#debug');await page.waitForFunction(()=>window.__TMB_A12__&&window.__tmbParkour);await page.locator('.characterChoice:visible').first().click();
const size=await page.evaluate(async()=>new TextEncoder().encode(await (await fetch('js/a12-campaign.js')).text()).length);if(size!==fs.statSync(path.join(root,'js/a12-campaign.js')).size)throw Error('loaded JS size mismatch');
await page.evaluate(()=>{const original=__tmbCampaignStep;window.__mTrace=[];window.__mUsage={};window.__mRides={};window.__mCollapse={};window.__tmbCampaignStep=function(dt){const v=original(dt),s=__TMB_A12__.getState(),p=s.player,park=__tmbParkour.read();__mTrace.push({x:p.x,y:p.y,w:s.hitbox.w,h:s.hitbox.h,state:park.state});for(const o of s.route.obstacles){const live=s.movingPlatforms.find(v=>v.id===o.id)||o,overlap=p.x+s.hitbox.w>live.x&&p.x<live.x+live.w;const used=['vault','slide'].includes(o.type)?overlap&&park.state===o.type:overlap&&p.onGround&&Math.abs(p.y+s.hitbox.h-live.y)<=2;if(used)__mUsage[o.id]=( __mUsage[o.id]||0)+1;}for(const m of s.movingPlatforms)__mRides[m.id]=Math.max(__mRides[m.id]||0,m.rideFrames);for(const c of s.collapsing){(__mCollapse[c.id]||=new Set()).add(c.state);}return v;};});
const r=await runAftermath(page,id);const observed=await page.evaluate(()=>({trace:__mTrace,usage:__mUsage,rides:__mRides,collapse:Object.fromEntries(Object.entries(__mCollapse).map(([k,v])=>[k,[...v]])),economy:__TMB_A12__.getState().economy,world:__TMB_A12__.getState().world.selectedWorldId,routeId:__TMB_A12__.getState().routeId}));runs.push({...r,observed});console.log(JSON.stringify({id,n,finished:r.finished,deaths:r.deaths,game_s:r.game_s,x:r.x,hash:r.hash,coins:observed.economy.collectedCoinIds,rides:observed.rides,usage:observed.usage,collapse:observed.collapse}));if(n===0&&!process.env.M_QUICK){const w=await runWalking(page,id);fs.writeFileSync(path.join(out,id+'-w.json'),JSON.stringify(w));console.log('W '+JSON.stringify({id,complete:w.complete,coins:w.coinIds,coverage:w.coverage}));}await page.close();}rows.push({id,runs});fs.writeFileSync(path.join(out,'a-s.json'),JSON.stringify(rows));}}
finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
