const {test,expect}=require('playwright/test'),fs=require('fs'),path=require('path'),http=require('http');let server,base;const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'a5b1-evidence');
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://x').pathname.slice(1)||'index.html';let b;try{b=fs.readFileSync(path.join(root,rel));}catch{res.statusCode=404;return res.end();}if(rel==='js/a12-campaign.js')b=Buffer.from(b.toString().replace('if (DEBUG) {','if (DEBUG) { window.a5Probe=code=>eval(code);'));if(rel==='index.html'){let s=b.toString(),i=s.lastIndexOf('})();');s=s.slice(0,i)+'if(location.hash.includes("debug"))window.a5Engine=code=>eval(code);\n'+s.slice(i);b=Buffer.from(s);}if(rel==='js/a12-campaign.js'&&process.env.A5_MUTATION){const m=JSON.parse(fs.readFileSync(path.join(out,'mutations.json')))[process.env.A5_MUTATION],v=b.toString();if(!v.includes(m.from))throw Error('mutation not applied');b=Buffer.from(v.replace(m.from,m.to));}res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':rel.endsWith('.json')?'application/json':'application/octet-stream');res.end(b);});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/index.html#debug`;});test.afterAll(async()=>new Promise(r=>server.close(r)));
async function open(page){await page.route('**/*',r=>r.request().url().startsWith(base.split('/index')[0])?r.continue():r.abort());await page.goto(base);await page.waitForFunction(()=>window.a5Probe);await page.evaluate(async()=>{__tmbPause();__tmbParkour.manual();await a5Probe('runnerAtlasReady');});}

for(const size of [[1080,540],[844,390],[390,844]]) {
 test(`shop-preview-portrait-layout ${size.join('x')}`,async({page})=>{
 await page.setViewportSize({width:size[0],height:size[1]});await open(page);await page.evaluate(()=>__TMB_A12__.openShop());
 const before=await page.locator('#a12Preview').boundingBox(),products=await page.locator('#a12Products').boundingBox();
 expect(before.x).toBeGreaterThanOrEqual(0);expect(before.y).toBeGreaterThanOrEqual(0);expect(products.y+products.height).toBeLessThanOrEqual(size[1]);
 if(size[0]<size[1])expect(before.y+before.height).toBeLessThanOrEqual(products.y);else expect(before.x+before.width).toBeLessThanOrEqual(products.x);
 const b=await page.locator('#a12Preview canvas').boundingBox();expect(b.width/b.height).toBeCloseTo(1.5,1);
 const overlay=await page.evaluate(()=>{const c=document.querySelector('#a12Preview canvas'),b=c.getBoundingClientRect();const stack=document.elementsFromPoint(b.x+b.width/2,b.y+b.height/2);return stack.slice(0,stack.indexOf(c)).filter(e=>!e.contains(c)).length});expect(overlay).toBe(0);
 await page.locator('#a12Products').evaluate(e=>e.scrollTop=e.scrollHeight);expect(await page.locator('#a12Preview').boundingBox()).toEqual(before);
 for(const selector of ['[data-preview-runner="female"]','[data-preview-motion="frontFlip"]']){const box=await page.locator(selector).boundingBox();expect(box.y).toBeGreaterThanOrEqual(before.y);expect(box.y+box.height).toBeLessThanOrEqual(before.y+before.height);}
 fs.writeFileSync(path.join(out,`layout-${size.join('x')}.json`),JSON.stringify({before,products,canvas:b}));
 });
 test(`shop-preview-runner-and-animation ${size.join('x')}`,async({page})=>{
 await page.setViewportSize({width:size[0],height:size[1]});await open(page);await page.locator('.characterChoice:visible').first().click();await page.evaluate(()=>__TMB_A12__.openShop());
 await page.evaluate(async()=>{a5Probe('profile.migrationFlags.v36=true');await a5Probe('persist()')});
 const saved=await page.evaluate(()=>({p:__TMB_A12__.getState().profile,storage:localStorage.getItem('trust_me_bro_campaign_profile_v1')}));
 await page.locator('[data-item="hazardRunner"] h3').click();await page.locator('[data-preview-runner="female"]').click();await page.locator('[data-preview-motion="frontFlip"]').click();
 expect(await page.evaluate(()=>a5Probe('({previewRunnerId,previewMotion,previewOutfitId})'))).toEqual({previewRunnerId:'female',previewMotion:'frontFlip',previewOutfitId:'hazardRunner'});
 const matrix=await page.evaluate(()=>a5Probe(`(()=>{const q=document.querySelector('#a12Preview canvas'),c=q.getContext('2d'),result=[];for(const runner of ['male','female'])for(const motion of ['idle','run','frontFlip']){previewRunnerId=runner;previewMotion=motion;const hashes=[];for(let frame=0;frame<8;frame++){drawShopPreview(previewStartedAt+(frame+.01)*1000/(motion==='run'?16:8));const actual=c.getImageData(0,0,480,320).data;const ref=document.createElement('canvas');ref.width=480;ref.height=320;const x=ref.getContext('2d');drawThemeScene(x,480,320,profile.selectedWorldId,true);x.translate(240,240);x.scale(3,3);drawRunnerAtlas(x,runner,'hazardRunner',{motion,frame},0,0);const expected=x.getImageData(0,0,480,320).data;if(actual.some((v,i)=>v!==expected[i]))throw Error('preview frame mismatch');let hash=0;for(const v of actual)hash=(Math.imul(hash,31)+v)|0;hashes.push(hash);}result.push({runner,motion,hashes,unique:new Set(hashes).size});}return result})()`));
 expect(matrix).toHaveLength(6);expect(matrix.every(x=>x.unique>1)).toBe(true);
 await page.locator('[data-tab="worlds"]').click();const worlds=[];
 for(const w of ['dock31','frozen','magma','aftermath']){await page.locator(`[data-list="worlds"] [data-item="${w}"] h3`).click();worlds.push(await page.evaluate(()=>a5Probe(`(()=>{drawShopPreview(previewStartedAt);let h=0;for(const v of document.querySelector('#a12Preview canvas').getContext('2d').getImageData(0,0,480,320).data)h=(Math.imul(h,31)+v)|0;return h})()`)));}expect(new Set(worlds).size).toBe(4);
 expect(await page.evaluate(()=>__TMB_A12__.getState().profile)).toEqual(saved.p);expect(await page.evaluate(()=>localStorage.getItem('trust_me_bro_campaign_profile_v1'))).toBe(saved.storage);
 await page.evaluate(()=>__TMB_A12__.closeShop());await page.reload();await page.waitForFunction(()=>window.a5Probe);const reloaded=await page.evaluate(()=>__TMB_A12__.getState().profile);expect(reloaded.profileRevision).toBe(saved.p.profileRevision+1);expect({...reloaded,profileRevision:saved.p.profileRevision}).toEqual(saved.p);
 fs.writeFileSync(path.join(out,`preview-${size.join('x')}.json`),JSON.stringify({matrix,worlds}));
 });
}
test('preview purchase equips explicitly previewed runner only',async({page})=>{await open(page);await page.locator('.characterChoice:visible').first().click();await page.evaluate(async()=>{await __TMB_A12__.setWallet(300);__TMB_A12__.openShop()});await page.locator('[data-preview-runner="female"]').click();await page.locator('[data-item="nightShift"] [data-action]').click();const p=await page.evaluate(()=>__TMB_A12__.getState().profile);expect(p.runnerId).toBe('male');expect(p.equippedOutfitByRunner).toEqual({male:'default',female:'nightShift'});expect(p.walletBalance).toBe(60);});
test('npc roles pixels reactions and render does not mutate state',async({page})=>{await open(page);await page.locator('.characterChoice:visible').first().click();const rows=await page.evaluate(()=>a5Probe(`(()=>{const rows=[];for(const world of ['dock31','frozen','magma','aftermath']){profile.selectedWorldId='dock31';profile.ownedWorldIds=['dock31','frozen','magma','aftermath'];startRoute('D03',true);profile.selectedWorldId=world;campaignChief={active:true,x:520,y:GROUND-48};const worker=route.obstacles.find(o=>o.type==='worker');const original=route;route={...route,obstacles:[...route.obstacles,...(!worker?[{type:'worker',x:700}]:[])]};const roles=presentationNpcs();if(!['carrier','operator','worker','chief'].every(r=>roles.some(n=>n.role===r)))throw Error('missing roles');for(const n of roles){const q=document.createElement('canvas');q.width=q.height=180;const c=q.getContext('2d');player.x=n.x;frontFlip.active=true;frontFlip.elapsed=.3;const before=JSON.stringify({player,run,frontFlip,route,movingPlatforms,barrels,workerClock,campaignChief,gameClock});c.translate(90-n.x,150-n.y);drawNpcPresentation(c,false);const quiet=c.getImageData(0,0,180,180).data;c.clearRect(n.x-90,n.y-150,180,180);drawNpcPresentation(c,true);const active=c.getImageData(0,0,180,180).data;const difference=active.reduce((v,x,i)=>v+(x!==quiet[i]),0);if(!difference)throw Error('no reaction');if(n.added&&!quiet.some((v,i)=>i%4===3&&v))throw Error('no added role');if(before!==JSON.stringify({player,run,frontFlip,route,movingPlatforms,barrels,workerClock,campaignChief,gameClock}))throw Error('render side effect');rows.push({world,role:n.role,difference});}route=original;}return rows})()`));expect(rows.length).toBeGreaterThanOrEqual(16);fs.writeFileSync(path.join(out,'npc-roles.json'),JSON.stringify(rows));});
test('npc reaction on off identical player camera hazard trace',async({page})=>{await open(page);await page.locator('.characterChoice:visible').first().click();const traces=[];for(const enabled of [false,true]){traces.push(await page.evaluate(enabled=>a5Probe(`(()=>{startRoute('D01',true);__tmbSegmentStart(400);player.walkPhase=0;a5Engine('anchorFrac=.31;cam=0');const q=document.createElement('canvas'),c=q.getContext('2d');const trace=[];document.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',code:'ArrowRight',bubbles:true}));for(let i=0;i<180;i++){__tmbCampaignStep(1/60);const prior=frontFlip.active;frontFlip.active=true;drawNpcPresentation(c,${enabled});frontFlip.active=prior;trace.push({player:{...player},camera:a5Engine('cam'),workerClock,barrels:JSON.stringify(barrels),runCoins:run.runCoins});}document.dispatchEvent(new KeyboardEvent('keyup',{key:'ArrowRight',code:'ArrowRight',bubbles:true}));return trace})()`),enabled));}expect(traces[1]).toEqual(traces[0]);expect(traces[0][179].player.x).toBeGreaterThan(traces[0][0].player.x);fs.writeFileSync(path.join(out,'npc-physics.json'),JSON.stringify({frames:180,equal:true}));});

test('NPC layer called by live game renderer',async({page})=>{await open(page);await page.locator('.characterChoice:visible').first().click();const count=await page.evaluate(()=>a5Probe(`(()=>{const original=drawNpcPresentation;let calls=0;drawNpcPresentation=function(...args){calls++;return original(...args)};try{a5Engine('drawDispatch()')}finally{drawNpcPresentation=original}return calls})()`));expect(count).toBe(1);});
