const {test,expect}=require('playwright/test');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {source}=require('./phase3-verify.cjs');
let server,base;
const colors=[[232,40,40,255],[40,210,70,255],[40,90,230,255],[235,195,40,255]];
const actions={vault:.28,slide:.32,roll:.24,wallRun:.25};
// Production sprites are read directly, never fixture redirects.
test('real sheets: 160 frame/flip/feet checks and 17 evidence crops',async({page})=>{
 await open(page,'real');const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});let count=0;
 for(let id=0;id<4;id++)for(const action of Object.keys(actions)){
  for(const dir of [-1,1])for(const [t,frame] of [[0,0],[.25,1],[.5,2],[.75,3],[1,3]]){
   await pose(page,id,action,t,dir);const r=await render(page);
   expect(r.last.src).toMatch(new RegExp('/real/sprites/'+['courier','forklift','picker','guard'][id]+'-'+(action==='wallRun'?'wallrun':action)+'\\.png$'));
   expect(r.last.a[0]).toBe(frame*212);expect(r.last.m.a).toBe(dir);expect(r.last.m.d).toBe(1);expect(Math.abs(r.last.m.b)).toBe(0);expect(Math.abs(r.last.m.c)).toBe(0);
   expect(r.last.a[5]+r.last.a[7]+r.last.m.f).toBe(250+(action==='slide'?24:48));expect(r.last.a[6]/r.last.a[7]).toBeCloseTo(212/192,5);expect(r.last.a[7]).toBeCloseTo(192*56/[177,159,181,177][id],5);expect(r.last.a[4]+r.last.a[6]/2).toBe(0);count++;
  }
  await page.evaluate(()=>animProbe("parkourFixture=null;currentLevel=3;currentPart=1;resetScene(false);spawnGrace=0;dead=false;characterSelectOpen=false;systemPaused=true;player.x=sceneStart()+160;cam=sceneStart();"));
  await page.evaluate(({id,action})=>animProbe("characterId="+id+";parkour.state='"+action+"';parkour.timer="+({vault:.28,slide:.32,roll:.24,wallRun:.25}[action]/2)+";player.h="+(action==='slide'?24:48)+";player.y=GROUND-player.h;draw();"),{id,action});
  const data=await evidence(page);
  const dir=path.join(__dirname,'evidence');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,['courier','forklift','picker','guard'][id]+'-'+(action==='wallRun'?'wallrun':action)+'-50.png'),Buffer.from(data,'base64'));
  await page.evaluate(()=>animProbe('player.x=250;player.y=250;'));
 }
 expect(count).toBe(160);
 for(const phase of [0,.5]){
  const shots=[];for(const action of ['normal','vault']){await pose(page,0,action,phase);await page.evaluate(()=>animProbe('player.x=sceneStart()+160;player.y=GROUND-player.h;player.vx=255;player.walkPhase=0;player.facing=1;draw();'));shots.push(await evidence(page));}
  const combined=await page.evaluate(async shots=>{const canvas=document.createElement('canvas');canvas.width=720;canvas.height=360;const ctx=canvas.getContext('2d');for(let i=0;i<2;i++){const img=new Image();img.src='data:image/png;base64,'+shots[i];await img.decode();ctx.drawImage(img,i*360,0);}return canvas.toDataURL().split(',')[1]},shots);fs.writeFileSync(path.join(__dirname,'evidence/courier-comparison-'+phase+'.png'),Buffer.from(combined,'base64'));
 }
 await page.evaluate(()=>animProbe('player.x=250;player.y=250;'));

 let hzChecks=0;
 for(let id=0;id<4;id++)for(const action of Object.keys(actions))for(const dir of [-1,1])for(const hz of [30,60,120]){
  const t=Math.floor(actions[action]*hz*.6)/hz/actions[action];await pose(page,id,action,t,dir);const r=await render(page);
  expect(r.last.a[0]).toBe(Math.min(3,Math.floor(t*4))*212);expect(r.last.m.a).toBe(dir);expect(r.last.m.d).toBe(1);expect(Math.abs(r.last.m.b)).toBe(0);expect(Math.abs(r.last.m.c)).toBe(0);hzChecks++;
 }
 expect(hzChecks).toBe(96);
 await page.evaluate(()=>animProbe('rt.chief={active:true,x:player.x-70};drawChief();'));
 await page.waitForFunction(()=>animProbe("ACTION_SHEETS.get('chief').loaded"));
 expect((await render(page,true)).last.src).toMatch(/\/real\/sprites\/chief.png$/);
 await page.evaluate(()=>animProbe("player.x=sceneStart()+160;player.y=GROUND-player.h;rt.chief.x=player.x-70;draw();"));
 fs.writeFileSync(path.join(__dirname,'evidence/chief-50.png'),Buffer.from(await evidence(page,true),'base64'));expect(errors).toEqual([]);
});
async function evidence(page,chief=false){return page.evaluate(chief=>animProbe("(()=>{const scale=dpr*viewScale,cx=(("+(chief?'rt.chief.x':'player.x')+")+16-cam)*scale+dpr*viewOffsetX,cy=(GROUND+worldY-40)*scale+dpr*viewOffsetY,sz=180*scale,out=document.createElement('canvas');out.width=360;out.height=360;const cc=out.getContext('2d');cc.imageSmoothingEnabled=false;cc.drawImage(c,cx-sz/2,cy-sz/2,sz,sz,0,0,360,360);return out.toDataURL().split(',')[1]})()"),chief)}
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const parts=new URL(req.url,'http://localhost').pathname.split('/').filter(Boolean),mode=parts.shift(),rel=parts.join('/');if(rel==='playgama-bridge-config.json'){const c=JSON.parse(fs.readFileSync(path.join(__dirname,'..',rel),'utf8'));c.optionalSprites=mode==='none'||mode==='head'?[]:fs.readdirSync(path.join(__dirname,'fixtures/sprites')).map(n=>n.replace(/\.png$/,'')).filter(n=>!(mode==='mixed'&&n==='courier-slide'));res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(c))}if(rel==='index.html'){let html=source(mode==='head'?'HEAD':'WORKTREE');const end=html.lastIndexOf('})();');html=html.slice(0,end)+'window.animProbe=code=>eval(code);\n'+html.slice(end);res.setHeader('Content-Type','text/html');return res.end(html)}const optional=/^sprites\/(chief|(?:courier|forklift|picker|guard)-(?:vault|slide|roll|wallrun))\.png$/.test(rel);if(optional&&(mode==='none'||mode==='head'||mode==='mixed'&&rel==='sprites/courier-slide.png')){res.statusCode=404;return res.end('missing')}if(optional&&mode==='invalid'){res.setHeader('Content-Type','image/svg+xml');return res.end('<svg xmlns="http://www.w3.org/2000/svg" width="423" height="192"/>')}const file=optional&&mode!=='real'?path.join(__dirname,'fixtures',rel):path.join(__dirname,'..',rel);fs.readFile(file,(err,b)=>{res.statusCode=err?404:200;if(rel.endsWith('.png'))res.setHeader('Content-Type','image/png');res.end(err?'missing':optional&&mode==='large'?Buffer.concat([b,Buffer.alloc(512*1024)]):b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;});
test.afterAll(async()=>{await new Promise(r=>server.close(r))});
test.afterEach(async({page})=>{expect(page.animErrors||[]).toEqual([])});
async function open(page,mode='all'){page.animErrors=[];page.on('pageerror',e=>page.animErrors.push(e.message));await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;performance.now=()=>10000});await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());await page.goto(`${base}/${mode}/index.html#debugParkour`);await page.waitForFunction(()=>window.animProbe&&window.__tmb?.platform.initialized,{},{polling:10});await page.evaluate(()=>{__tmbPause();__tmbParkour.manual();__tmbParkour.setup();animProbe('spawnGrace=0;dead=false;player.x=250;player.y=250;rt.t=.15;')});await page.waitForFunction(()=>animProbe('PNG_SPRITES.every(s=>s.loaded||s.failed)'),{},{polling:10});}
async function pose(page,id,action,t=0,dir=1){await page.evaluate(({id,action,t,dir})=>animProbe(`characterId=${id};parkour.state='${action}';parkour.timer=${({vault:.28,slide:.32,roll:.24,wallRun:.25,stun:.12}[action]||0)*(1-t)};player.h=${action==='slide'?24:48};player.facing=${dir};player.onGround=true;player.vx=0;drawCourier();`),{id,action,t,dir});if(action in actions)await page.waitForFunction(({id,action})=>animProbe(`(()=>{const s=ACTION_SHEETS.get(SPRITE_NAMES[${id}]+'-${action==='wallRun'?'wallrun':action}');return s&&(s.loaded||s.failed)})()`),{id,action},{polling:10});}
async function render(page,chief=false){return page.evaluate(chief=>animProbe(`(()=>{ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,c.width,c.height);ctx.globalAlpha=1;const calls=[],old=ctx.drawImage;ctx.drawImage=function(image,...a){const m=this.getTransform();calls.push({src:image.src||'pixel',a,m:{a:m.a,b:m.b,c:m.c,d:m.d,e:m.e,f:m.f}});return old.call(this,image,...a)};try{${chief?'drawChief()':'drawCourier()'}}finally{ctx.drawImage=old}const last=calls.at(-1);let pixel=null;if(last){const a=last.a,m=last.m,x=a[4]+a[6]*.15,y=a[5]+a[7]*.2;pixel=Array.from(ctx.getImageData(Math.round(m.a*x+m.c*y+m.e),Math.round(m.b*x+m.d*y+m.f),1,1).data)}return{last,pixel,hash:c.toDataURL()}})()`),chief);}
for(let id=0;id<4;id++)for(const action of Object.keys(actions))test(`${id} ${action}: five frame boundaries, pixels, untransformed feet`,async({page})=>{await open(page);for(const [t,frame] of [[0,0],[.25,1],[.5,2],[.75,3],[1,3]]){await pose(page,id,action,t);const r=await render(page);expect(r.last.a[0]).toBe(frame*212);expect(r.pixel).toEqual(colors[frame]);expect(r.last.m.a).toBe(1);expect(r.last.m.d).toBe(1);expect(Math.abs(r.last.m.b)).toBe(0);expect(Math.abs(r.last.m.c)).toBe(0);expect(r.last.a[5]+r.last.a[7]+r.last.m.f).toBe(250+(action==='slide'?24:48));}});
test('missing sheets reproduce v62 canvas for every action/character/direction and chief',async({page,context})=>{await open(page,'none');const before=await context.newPage();await open(before,'head');for(let id=0;id<4;id++)for(const action of Object.keys(actions))for(const dir of [-1,1]){await pose(page,id,action,.5,dir);await before.evaluate(code=>animProbe(code),`characterId=${id};parkour.state='${action}';parkour.timer=${actions[action]/2};player.h=${action==='slide'?24:48};player.facing=${dir};player.onGround=true;player.vx=0;`);expect((await render(page)).hash).toBe((await render(before)).hash)}for(const p of [page,before])await p.evaluate(()=>animProbe('rt.chief={active:true,x:120};'));await render(page,true);await page.waitForFunction(()=>animProbe("ACTION_SHEETS.get('chief').failed"),{},{polling:10});expect((await render(page,true)).hash).toBe((await render(before,true)).hash);await before.close()});
test('cancellation immediately restores normal sheet; crouch holds slide last frame',async({page})=>{await open(page);await pose(page,0,'slide',.5);await page.evaluate(()=>animProbe("parkour.state='crouch';"));expect((await render(page)).last.a[0]).toBe(636);await page.evaluate(()=>animProbe('parkourCancel(true);'));expect((await render(page)).last.src).toMatch(/courier\.png$/)});
test('chief present uses four walking frames and keeps flashlight',async({page})=>{await open(page);await page.evaluate(()=>animProbe('rt.chief={active:true,x:120};drawChief();'));await page.waitForFunction(()=>animProbe("ACTION_SHEETS.get('chief').loaded"),{},{polling:10});for(let i=0;i<4;i++){await page.evaluate(i=>animProbe(`rt.t=${i*.1};`),i);const r=await render(page,true);expect(r.last.a[0]).toBe(i*212);expect(r.pixel).toEqual(colors[i])}});
test('one missing sheet cannot disable other sheets; lazy cache; debug byte measurement',async({page})=>{await open(page,'mixed');expect(await page.evaluate(()=>animProbe('ACTION_SHEETS.size'))).toBe(0);await pose(page,0,'slide');expect((await render(page)).last.src).toMatch(/courier\.png$/);await pose(page,0,'vault');expect((await render(page)).last.src).toMatch(/courier-vault\.png$/);await pose(page,1,'slide');expect((await render(page)).last.src).toMatch(/forklift-slide\.png$/);await page.waitForFunction(()=>animProbe("ACTION_SHEETS.get('courier-vault').bytes>0"),{},{polling:10});expect(await page.evaluate(()=>animProbe("ACTION_SHEETS.get('courier-vault').bytes"))).toBe(fs.statSync(path.join(__dirname,'fixtures/sprites/courier-vault.png')).size)});
test('4 characters x 2 directions x 30/60/120 Hz x 4 actions: proportional frames',async({page})=>{await open(page);let n=0;for(let id=0;id<4;id++)for(const dir of [-1,1])for(const hz of [30,60,120])for(const action of Object.keys(actions)){const elapsed=Math.floor(actions[action]*hz*.6)/hz;await pose(page,id,action,elapsed/actions[action],dir);const r=await render(page);expect(r.last.a[0]).toBe(Math.min(3,Math.floor(elapsed/actions[action]*4))*212);expect(r.last.m.a).toBe(dir);expect(r.last.m.d).toBe(1);n++}expect(n).toBe(96)});
test('stun uses idle with small jitter and leaves physics untouched',async({page})=>{await open(page);await pose(page,0,'stun',.25);const state=await page.evaluate(()=>animProbe('JSON.stringify({player,parkour})'));const r=await render(page);expect(r.last.a[0]).toBe(0);expect(Math.abs(r.last.m.e-266)).toBeLessThanOrEqual(1.2);expect(await page.evaluate(()=>animProbe('JSON.stringify({player,parkour})'))).toBe(state)});

test('oversized sheet warns in debug but stays usable',async({page})=>{const warnings=[];page.on('console',m=>{if(m.type()==='warning')warnings.push(m.text())});await open(page,'large');await pose(page,0,'vault');await page.waitForFunction(()=>animProbe("ACTION_SHEETS.get('courier-vault').bytes>512*1024"),{},{polling:10});expect(warnings.some(s=>s.includes('exceeds 512 KiB'))).toBe(true);expect((await render(page)).pixel).toEqual(colors[0])});
test('wrong sheet dimensions fail independently and retain fallback',async({page})=>{await open(page,'invalid');await pose(page,0,'vault');expect(await page.evaluate(()=>animProbe("ACTION_SHEETS.get('courier-vault').failed"))).toBe(true);expect((await render(page)).last.src).toMatch(/courier\.png$/)});
// Build-time discovery prevents missing optional HTTP requests; no console-error filtering.
test('absent optional sheets make zero PNG requests and zero console errors',async({page})=>{const errors=[],requests=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(/sprites\/(chief|.+-(vault|slide|roll|wallrun))\.png/.test(r.url()))requests.push(r.url())});await open(page,'none');for(let id=0;id<4;id++)for(const action of Object.keys(actions))await pose(page,id,action);await page.evaluate(()=>animProbe('rt.chief={active:true,x:120};drawChief()'));await page.waitForFunction(()=>animProbe("ACTION_SHEETS.get('chief').failed"));expect(requests).toEqual([]);expect(errors).toEqual([])});
