const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),campaign=path.join(root,'js','a12-campaign.js');
let src=fs.readFileSync(campaign,'utf8');
const round=n=>Math.round(n*100)/100;
function objectRange(text,marker){const start=text.indexOf(marker);if(start<0)throw Error('missing '+marker);const open=text.indexOf('{',start);let depth=0,string=false,escape=false;for(let i=open;i<text.length;i++){const c=text[i];if(string){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')string=false;continue}if(c==='"'){string=true;continue}if(c==='{')depth++;else if(c==='}'&&!--depth)return {open,close:i};}throw Error('unbalanced '+marker)}
function readObjects(text){const cr=objectRange(text,'const COINS = Object.freeze('),rr=objectRange(text,'const ROUTES = Object.freeze(');const coins=vm.runInNewContext('('+text.slice(cr.open,cr.close+1)+')');const makeCoins=id=>coins[id].map(c=>({...c,id:`${id}-c${String(c.n+1).padStart(2,'0')}`}));const routes=vm.runInNewContext('('+text.slice(rr.open,rr.close+1)+')',{makeCoins,COINS:coins});return {coins,routes,cr,rr}}
const sourceMap={D07:'F01',D08:'F02',D09:'F03',D10:'F04',D11:'M01',D12:'M02',D13:'M03',D14:'M04',D15:'A01',D16:'A02'};
const names={D07:'NIGHT GANTRY',D08:'REEFER ROW',D09:'BERTH SEVEN',D10:'STACK RUNNER',D11:'HARBOR ROOFS',D12:'QUAY SPRINT',D13:'BOLLARD LINE',D14:'CUSTOMS YARD',D15:'DRY DOCK',D16:'PILOT TOWER',D17:'TWIN CRANES',D18:'LAST MANIFEST'};
const dataRoots={F01:'frozen-f01f02',F02:'frozen-f01f02',F03:'frozen-f03f04',F04:'frozen-f03f04',M01:'magma-m01m02',M02:'magma-m01m02',M03:'magma-m03m04',M04:'magma-m03m04',A01:'aftermath-a01a02',A02:'aftermath-a01a02'},design='E:/oyunlar/TrustMeBro/01-tasarim/vector-parkur';
const sourceTransitions=Object.fromEntries(Object.keys(dataRoots).map(id=>[id,JSON.parse(fs.readFileSync(path.join(design,dataRoots[id],`transitions-${id}.json`),'utf8'))]));
function renameDeep(value,from,to){if(typeof value==='string')return value.replaceAll(from.toLowerCase(),to.toLowerCase()).replaceAll(from,to);if(Array.isArray(value))return value.map(x=>renameDeep(x,from,to));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,renameDeep(v,from,to)]));return value}
function cloneRoute(routes,coins,id,source){const r=renameDeep(structuredClone(routes[source]),source,id);Object.assign(r,{routeId:id,worldId:'dock31',version:1,name:names[id],chief:{startX:r.checkpoints[1]}});delete r.voidEdges;r.coins=undefined;const cs=renameDeep(structuredClone(coins[source]),source,id);cs.forEach((c,n)=>{c.n=n;c.move_id=c.move_id.replace(new RegExp('^'+source.toLowerCase()),id.toLowerCase())});return {route:r,coins:cs}}
function shiftThing(x,dx,dy,prefix){const q=structuredClone(x);for(const k of ['x','x1','x2','landX','minX','maxX'])if(Number.isFinite(q[k]))q[k]=round(q[k]+dx);for(const k of ['y','landY','baseY','openY','peakY'])if(Number.isFinite(q[k]))q[k]=round(q[k]+dy);if(q.id)q.id=prefix+q.id;if(q.move_id)q.move_id=prefix+q.move_id;return q}
function surfaceAt(route,x){return route.groundSegments.filter(s=>s.x<=x&&s.x+s.w>=x).sort((a,b)=>a.y-b.y)[0]||route.groundSegments.slice().sort((a,b)=>Math.abs(a.x+a.w/2-x)-Math.abs(b.x+b.w/2-x))[0]}
function shiftTransition(t,dx,dy,prefix){const q=renameDeep(structuredClone(t),t.A.id.split('-')[0].toUpperCase(),prefix.slice(0,-1).toUpperCase());const walk=o=>{if(!o||typeof o!=='object')return;for(const [k,v] of Object.entries(o)){if(v&&typeof v==='object')walk(v);else if(Number.isFinite(v)&&['x','x0','x1','x2','landX','runStart'].includes(k))o[k]=round(v+dx);else if(Number.isFinite(v)&&['y','landY','peakY'].includes(k))o[k]=round(v+dy)}};walk(q);return q}
function compose(routes,coins,id,parts){let out={routeId:id,worldId:'dock31',version:1,name:names[id],movementProfile:'vector-v1',highJumpZones:[],groundSegments:[],catchableSurfaces:[],diveZones:[],obstacles:[]},pool=[],cursor=0,seams=[],transitions=[];
  parts.forEach((spec,pi)=>{const r=routes[spec.id],target=r.length*spec.fraction,anchor=surfaceAt(r,target);if(!anchor)throw Error(`no cut anchor ${spec.id}`);const cut=spec.side==='left'?anchor.x+anchor.w:anchor.x,chosen=r.groundSegments.filter(s=>spec.side==='left'?s.x<cut:s.x+s.w>cut);const edge=spec.side==='left'?Math.max(...chosen.map(s=>s.x+s.w)):Math.min(...chosen.map(s=>s.x));const edgeSurface=spec.side==='left'?chosen.sort((a,b)=>(b.x+b.w)-(a.x+a.w))[0]:chosen.sort((a,b)=>a.x-b.x)[0];const dx=cursor-edge,dy=pi?out.groundSegments.slice().sort((a,b)=>b.x+b.w-a.x-a.w)[0].y-edgeSurface.y:0,prefix=`${id.toLowerCase()}-p${pi+1}-`;
    const ids=new Set(chosen.map(s=>s.id));for(const s of chosen)out.groundSegments.push(shiftThing(s,dx,dy,prefix));for(const c of r.catchableSurfaces||[])if(ids.has(c.id))out.catchableSurfaces.push({id:prefix+c.id});for(const z of r.diveZones||[])if(spec.side==='left'?z.landX<=cut:z.x1>=cut)out.diveZones.push(shiftThing(z,dx,dy,prefix));for(const o of r.obstacles||[])if(spec.side==='left'?o.x+o.w<=cut:o.x>=cut)out.obstacles.push(shiftThing(o,dx,dy,prefix));for(const c of coins[spec.id])if(spec.side==='left'?c.x<=cut:c.x>=cut)pool.push(shiftThing(c,dx,dy,prefix));for(const t of sourceTransitions[spec.id])if(spec.side==='left'?t.B.x1<=cut:t.A.x0>=cut)transitions.push(shiftTransition(t,dx,dy,prefix));if(pi)seams.push({x:cursor,y:round(edgeSurface.y+dy),from:parts[pi-1].id,to:spec.id});cursor=Math.max(...out.groundSegments.map(s=>s.x+s.w));
  });
  const minX=Math.min(...out.groundSegments.map(s=>s.x)),normalize=70-minX;for(const list of [out.groundSegments,out.diveZones,out.obstacles,pool])for(const q of list)for(const k of ['x','x1','x2','landX','minX','maxX'])if(Number.isFinite(q[k]))q[k]=round(q[k]+normalize);for(const t of transitions){const walk=o=>{if(!o||typeof o!=='object')return;for(const [k,v]of Object.entries(o)){if(v&&typeof v==='object')walk(v);else if(Number.isFinite(v)&&['x','x0','x1','x2','landX','runStart'].includes(k))o[k]=round(v+normalize)}};walk(t)}cursor=round(cursor+normalize);for(const s of seams)s.x=round(s.x+normalize);
  const second=out.groundSegments.filter(s=>s.id.startsWith(`${id.toLowerCase()}-p2-`)).sort((a,b)=>a.x-b.x);if(second.length>1&&!transitions.some(t=>Math.abs(t.B.x0-second[1].x)<.02)){const [A,B]=second;transitions.push({A:{x0:A.x,x1:round(A.x+A.w),y:A.y,id:A.id},B:{x0:B.x,x1:round(B.x+B.w),y:B.y,id:B.id},gap:round(B.x-A.x-A.w),D:round(B.y-A.y),mech:B.y<A.y?'tutunma':'kosu',vectorTrigger:'composite-seam'})}
  const wanted={CJ:8,CC:4,CS:2},selected=[];for(const [kind,count] of Object.entries(wanted)){const cand=pool.filter(c=>c.kind===kind).sort((a,b)=>a.x-b.x);for(let i=0;i<count;i++){const c=structuredClone(cand[Math.min(i,cand.length-1)]||pool[i%pool.length]);c.kind=kind;c.skill=kind!=='CJ';selected.push(c)}}selected.sort((a,b)=>a.x-b.x).forEach((c,n)=>{c.n=n;c.move_id=`${id.toLowerCase()}-mix-${String(n+1).padStart(2,'0')}`});out.length=round(cursor+140);out.finishX=cursor;out.checkpoints=[70,round(cursor*.25),round(cursor*.5),round(cursor*.75)];out.chief={startX:out.checkpoints[1]};transitions.sort((a,b)=>a.A.x0-b.A.x0).forEach((t,i)=>t.i=i);return {route:out,coins:selected,seams,parts,transitions}}
const parsed=readObjects(src),newRoutes={},newCoins={},meta={copies:{},composites:{}};
const newTransitions={};for(const [id,source] of Object.entries(sourceMap)){const x=cloneRoute(parsed.routes,parsed.coins,id,source);newRoutes[id]=x.route;newCoins[id]=x.coins;newTransitions[id]=renameDeep(sourceTransitions[source],source,id);meta.copies[id]=source}
for(const [id,parts] of Object.entries({D17:[{id:'F04',side:'left',fraction:.5},{id:'M03',side:'right',fraction:.5}],D18:[{id:'A01',side:'left',fraction:.5},{id:'F03',side:'right',fraction:.5}]})){const x=compose(parsed.routes,parsed.coins,id,parts);newRoutes[id]=x.route;newCoins[id]=x.coins;newTransitions[id]=x.transitions;meta.composites[id]={parts,seams:x.seams,length:x.route.length}}
function inject(text,marker,entries){const r=objectRange(text,marker),body=text.slice(r.open+1,r.close).trimEnd(),addition=Object.entries(entries).map(([k,v])=>`  "${k}":${JSON.stringify(v)}`).join(',\n');return text.slice(0,r.open+1)+body+(body.trim()&&!body.endsWith(',')? ',\n':'\n')+addition+'\n'+text.slice(r.close)}
src=inject(src,'const COINS = Object.freeze(',newCoins);src=inject(src,'const ROUTES = Object.freeze(',Object.fromEntries(Object.entries(newRoutes).map(([id,r])=>[id,{...r,coins:`__MAKE_${id}__`}]))).replace(/"coins":"__MAKE_(D\d\d)__"/g,'"coins":makeCoins("$1", COINS.$1)');
src=src.replace('routes: ["D01", "D02", "D03", "D04", "D05", "D06"]','routes: ['+Array.from({length:18},(_,i)=>`"D${String(i+1).padStart(2,'0')}"`).join(', ')+']');
src=src.replace('  function routeUnlocked(id) {','  function routeUnlocked(id) {\n    if (/^D\\d{2}$/.test(id)) return !!ROUTES[id];');
src=src.replace('  function firstRouteForWorld(worldId=profile.selectedWorldId) {','  function firstRouteForWorld(worldId=profile.selectedWorldId) {\n    if (worldId==="dock31") return WORLD_REGISTRY.dock31.routes.find(id=>routeUnlocked(id)) || "D01";');
src=src.replace('profile.selectedWorldId==="frozen"?["F01","F02","F03","F04"]:["D01","D02","D03","D04","D05","D06"]','profile.selectedWorldId==="frozen"?["F01","F02","F03","F04"]:WORLD_REGISTRY.dock31.routes');
src=src.replace('profile.selectedWorldId==="frozen"?["F04","F03","F02","F01"]:["D06","D05","D04","D03","D02","D01"]','profile.selectedWorldId==="frozen"?["F04","F03","F02","F01"]:[...WORLD_REGISTRY.dock31.routes].reverse()');
src=src.replace('    document.head.appendChild(style);','    style.textContent += `#a12DockRoutes{position:fixed;z-index:30;left:50%;bottom:148px;transform:translateX(-50%);width:min(94vw,760px);display:grid;grid-template-columns:repeat(6,1fr);gap:5px;padding:8px;box-sizing:border-box;background:#06121be8;border:1px solid #ffffff33;border-radius:12px}#a12DockRoutes[hidden]{display:none!important}#a12DockRoutes button{min-width:0;padding:6px 2px;border:1px solid #ffffff33;border-radius:7px;background:#153246;color:#fff;font:800 10px/1.05 system-ui}#a12DockRoutes small{display:block;color:#ffd45c;font-size:9px}@media(max-width:540px) and (orientation:portrait){#a12DockRoutes{grid-template-columns:repeat(6,1fr);bottom:154px;gap:3px;padding:5px}#a12DockRoutes button{padding:5px 1px;font-size:9px}}`;\n    document.head.appendChild(style);');
src=src.replace('    document.body.appendChild(actions);','    document.body.appendChild(actions);\n    const dockRoutes=document.createElement("nav");dockRoutes.id="a12DockRoutes";dockRoutes.hidden=true;document.body.appendChild(dockRoutes);const renderDockRoutes=()=>{const show=document.body.dataset.campaignPhase==="result"&&profile.selectedWorldId==="dock31";dockRoutes.hidden=!show;if(!show)return;dockRoutes.innerHTML=WORLD_REGISTRY.dock31.routes.map(id=>`<button data-route="${id}">${id}<small>${"★".repeat(profile.progressByRoute[id]?.stars||0)}${"☆".repeat(3-(profile.progressByRoute[id]?.stars||0))}</small></button>`).join("")};new MutationObserver(renderDockRoutes).observe(document.body,{attributes:true,attributeFilter:["data-campaign-phase"]});dockRoutes.addEventListener("click",e=>{const id=e.target.closest("[data-route]")?.dataset.route;if(id)startRoute(id)});');
fs.writeFileSync(campaign,src,'utf8');
const out=path.join(__dirname,'dock18-generated');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'meta.json'),JSON.stringify(meta,null,2)+'\n');fs.writeFileSync(path.join(out,'routes.json'),JSON.stringify(newRoutes,null,2)+'\n');for(const [id,t] of Object.entries(newTransitions))fs.writeFileSync(path.join(out,`transitions-${id}.json`),JSON.stringify(t,null,2)+'\n');
console.log(JSON.stringify(meta,null,2));
