const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path');
const root=process.env.TMB_ROOT||path.join(__dirname,'..');let server,base;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/, '')||'index.html';fs.readFile(path.join(root,rel),(e,b)=>{if(e){res.statusCode=404;return res.end('missing')}res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':'application/octet-stream');res.end(b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/index.html`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function boot(page,id='D01',viewport={width:1280,height:720}){await page.setViewportSize(viewport);await page.goto(base+'#debug');await page.waitForFunction(()=>window.__TMB_A12__);await page.locator('.characterChoice:visible').first().click();await page.evaluate(id=>{__TMB_A12__.renderWorldOnRoute(id[0]==='F'?'frozen':'dock31',id);__TMB_A12__.startRoute(id)},id);await page.waitForFunction(id=>__TMB_A12__.getState().route.id===id,id)}
async function placeAtEntry(page,offset=8){await page.evaluate(offset=>{const s=__TMB_A12__.getState(),r=__TMB_A12__.routeDefinition(s.route.id);let x=s.chief.entry.x+offset,grounds=(r.groundSegments||[]).filter(v=>v.kind==="ground"&&x>=v.x&&x<=v.x+v.w);if(!grounds.length){const next=(r.groundSegments||[]).filter(v=>v.kind==="ground"&&v.x+v.w>=s.chief.entry.x).sort((a,b)=>a.x-b.x)[0];if(next){x=Math.max(s.chief.entry.x+offset,next.x+Math.min(24,next.w*.5));grounds=[next]}}const y=(grounds.length?Math.min(...grounds.map(v=>v.y)):455)-48;__TMB_A12__.placePlayer(x,y);},offset)}
async function placeAtLadderStart(page){await page.evaluate(()=>__TMB_A12__.placePlayerAtChiefLadderStart())}
async function waitChiefRunning(page){for(let i=0;i<90;i++){const phase=await page.evaluate(()=>{__tmbCampaignStep(1/60);return __TMB_A12__.getState().chief.entryPhase});if(phase==='running')return}throw new Error('chief did not enter running phase')}
const EXPECTED_D_DELAY=2.1,EXPECTED_F_DELAY=1.008;

test('all recorded chief paths are fresh; an in-memory coordinate mutation is rejected',async({page})=>{await boot(page);const result=await page.evaluate(()=>{const ids=Object.keys(window.TMB_CHIEF_PATHS||{}).sort();return {ids,fresh:ids.map(id=>[id,__TMB_A12__.chiefPathStatus(id)]),mutated:__TMB_A12__.chiefPathStatus('D01',1)}});expect(result.ids.length).toBeGreaterThan(0);for(const [id,s] of result.fresh){console.log(`HASH-${id} | ${s.current} | ${s.valid?'PASS':'FAIL'}`);expect(s.valid).toBe(true)}console.log(`HASH-negative-D01 | stored=${result.mutated.stored} current=${result.mutated.current} | ${!result.mutated.valid?'RED-as-expected':'FAIL'}`);expect(result.mutated.valid).toBe(false)});

for(const id of ['D01','D05','D09','D12']){
  test(`${id} post-ladder joins recorded route with configured gap`,async({page})=>{test.setTimeout(15000);await boot(page,id);await page.keyboard.up('ArrowRight');await placeAtLadderStart(page);const delay=EXPECTED_D_DELAY;await waitChiefRunning(page);const s=await page.evaluate(()=>__TMB_A12__.getState());const gap=s.chief.playerT-s.chief.chiefT;console.log(`JOIN-${id} post-ladder | phase=${s.chief.entryPhase}, delay=${s.chief.delay}, gap=${gap.toFixed(3)}, catches=${s.chief.catches} | PASS`);expect(s.chief.active).toBe(true);expect(s.chief.delay).toBeCloseTo(delay,3);expect(gap).toBeGreaterThanOrEqual(delay-.15);expect(gap).toBeLessThanOrEqual(delay+.15);expect(s.chief.catches).toBe(0)});
  test(`${id} post-ladder never rewinds behind ladder x`,async({page})=>{test.setTimeout(15000);await boot(page,id);await page.keyboard.up('ArrowRight');await placeAtLadderStart(page);await waitChiefRunning(page);const rows=[];for(let i=0;i<10;i++){rows.push(await page.evaluate(()=>{__tmbCampaignStep(1/60);const c=__TMB_A12__.getState().chief;return {x:c.x,entryX:c.entry.x,chiefT:c.chiefT,playerT:c.playerT}}))}const minX=Math.min(...rows.map(r=>r.x)),maxDx=Math.max(...rows.slice(1).map((r,i)=>Math.abs(r.x-rows[i].x)));console.log(`NO-REWIND-${id} | entryX=${rows[0].entryX.toFixed(2)}, minX=${minX.toFixed(2)}, maxDx=${maxDx.toFixed(2)} | ${minX>=rows[0].entryX&&maxDx<=80?'PASS':'FAIL'}`);expect(minX).toBeGreaterThanOrEqual(rows[0].entryX);expect(maxDx).toBeLessThanOrEqual(80)});
  test(`${id} pre-ladder pause delay-0.5 has no visible/catching chief`,async({page})=>{await boot(page,id);await page.keyboard.up('ArrowRight');const delay=EXPECTED_D_DELAY;await page.waitForTimeout((delay-.5)*1000);const s=await page.evaluate(()=>__TMB_A12__.getState());console.log(`PRE-LADDER-${id} delay-0.5 | active=${s.chief.active}, phase=${s.chief.entryPhase}, catches=${s.chief.catches} | ${!s.chief.active&&s.chief.catches===0?'PASS':'FAIL'}`);expect(s.chief.active).toBe(false);expect(s.chief.catches).toBe(0)});
}

for(const id of ['D15','D18'])test(`${id} t~4s pause delay-0.5 does not catch`,async({page})=>{await boot(page,id);await page.evaluate(()=>__TMB_A12__.placePlayerAtChiefTime(4));await page.waitForTimeout(1000);const s=await page.evaluate(()=>__TMB_A12__.getState());console.log(`PAUSE-${id}-T4 delay-0.5 | playerT=${s.chief.playerT.toFixed(3)}, chiefT=${s.chief.chiefT.toFixed(3)}, catches=${s.chief.catches} | ${s.chief.catches===0?'PASS':'FAIL'}`);expect(s.chief.catches).toBe(0)});

test('mid-climb vertical offset uses monotonic x fallback without early catch',async({page})=>{await boot(page,'D01');await page.evaluate(()=>__TMB_A12__.placePlayerAtChiefTime(6,-400));await page.waitForTimeout(100);const mid=await page.evaluate(()=>__TMB_A12__.getState());await page.waitForTimeout(900);const s=await page.evaluate(()=>__TMB_A12__.getState());console.log(`CLIMB-X-FALLBACK | mode=${mid.chief.matchMode}, gap=${(s.chief.playerT-s.chief.chiefT).toFixed(3)}, catches=${s.chief.catches} | ${mid.chief.matchMode==='x'&&s.chief.catches===0?'PASS':'FAIL'}`);expect(mid.chief.matchMode).toBe('x');expect(s.chief.catches).toBe(0)});

for(const id of ['D01','D09','D12'])test(`${id} keyboard ladder entry: hidden before 15%, climb after route-delay schedule, then faster gap`,async({page})=>{await boot(page,id);await page.keyboard.up('ArrowRight');const before=await page.evaluate(()=>__TMB_A12__.getState().chief);expect(before.active).toBe(false);expect(before.entryPhase).toBe('waiting');await placeAtEntry(page);await page.waitForTimeout(120);const waiting=await page.evaluate(()=>__TMB_A12__.getState().chief);expect(waiting.active).toBe(false);expect(waiting.entryPhase).toBe('waiting');await placeAtLadderStart(page);await page.waitForTimeout(120);const climbing=await page.evaluate(()=>__TMB_A12__.getState().chief);expect(climbing.active).toBe(true);expect(climbing.entryPhase).toBe('climbing');expect(climbing.pose).toBe('climb');await waitChiefRunning(page);const running=await page.evaluate(()=>__TMB_A12__.getState().chief);const gap=running.playerT-running.chiefT;console.log(`LADDER-${id}-KEYBOARD | beforeActive=${before.active}, scheduledWait=${waiting.entryPhase}, climbPose=${climbing.pose}, gap=${gap.toFixed(3)} | PASS`);expect(gap).toBeGreaterThanOrEqual(EXPECTED_D_DELAY-.15);expect(gap).toBeLessThanOrEqual(EXPECTED_D_DELAY+.15)});

for(const id of ['D01','D09','D12'])test(`${id} touch 390x844 ladder entry`,async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1}),page=await context.newPage();try{await boot(page,id,{width:390,height:844});let s=await page.evaluate(()=>__TMB_A12__.getState());expect(s.chief.active).toBe(false);expect(s.chief.delay).toBeCloseTo(EXPECTED_D_DELAY,3);await placeAtLadderStart(page);await page.waitForTimeout(120);s=await page.evaluate(()=>__TMB_A12__.getState());expect(s.chief.entryPhase).toBe('climbing');expect(s.chief.pose).toBe('climb');await waitChiefRunning(page);s=await page.evaluate(()=>__TMB_A12__.getState());const gap=s.chief.playerT-s.chief.chiefT;console.log(`LADDER-${id}-TOUCH-390x844 | phase=${s.chief.entryPhase}, delay=${s.chief.delay}, gap=${gap.toFixed(3)} | PASS`);expect(gap).toBeGreaterThanOrEqual(EXPECTED_D_DELAY-.15);expect(gap).toBeLessThanOrEqual(EXPECTED_D_DELAY+.15)}finally{await context.close()}});

test('F01 uses the recorded Frozen faster chief after ladder entry',async({page})=>{await boot(page,'F01');await page.keyboard.up('ArrowRight');let s=await page.evaluate(()=>__TMB_A12__.getState());expect(s.chief.active).toBe(false);expect(s.chief.delay).toBeCloseTo(EXPECTED_F_DELAY,3);s=await page.evaluate(()=>{const a=__TMB_A12__;const primed=a.placePlayerAtChiefLadderStart();a.placePlayerAtChiefTime(primed.chief.entry.readyTime);return a.getState()});console.log(`RECORDED-F01-LADDER | active=${s.chief?.active}, phase=${s.chief?.entryPhase}, delay=${s.chief?.delay} | ${s.chief?.active&&Math.abs(s.chief.delay-.864)<.001?'PASS':'FAIL'}`);expect(s.chief.active).toBe(true);expect(s.chief.delay).toBeCloseTo(EXPECTED_F_DELAY,3)});
