const {test,expect}=require('playwright/test');
const {load,source}=require('./phase3-verify.cjs');
const start=(p,l=6,part=1)=>p(`bgm.pause=()=>{};currentLevel=${l};currentPart=${part};deaths=partDeaths=chiefCatches=0;speedLevel=jumpLevel=0;dead=won=upgradePending=characterSelectOpen=livesPending=adPending=systemPaused=false;resetScene();spawnGrace=0;`);
test('31 speeds below base, S1-5 disabled, exact lead at all 62 starts',()=>{const p=load(source('WORKTREE'));for(let l=1;l<=31;l++)for(let part=1;part<=2;part++){start(p,l,part);expect(p('rt.chief.active')).toBe(l>=6);expect(p('rt.chief.speed')).toBe(l<=5?0:255*(l===31?.84:l>=16?.78:.72));expect(p('rt.chief.speed')).toBeLessThan(255);expect(p('player.x-rt.chief.x')).toBe(320);}});
test('catch returns to current part in 820 ms; incidents +1, deaths/lives/rage tier unchanged',()=>{const p=load(source('WORKTREE'));start(p,6,2);p('deaths=7;partDeaths=2;rt.chief.x=player.x;rt.chief.grace=0;update(1/60)');expect(p('dead&&rt.chief.caught')).toBe(true);expect(p('deaths')).toBe(7);expect(p('partDeaths')).toBe(2);expect(p('incidentCount()')).toBe(8);expect(p('lives')).toBe(10);p('performance.now=()=>819;update(1/60)');expect(p('dead')).toBe(true);p('performance.now=()=>820;update(1/60)');expect(p('dead')).toBe(false);expect(p('currentLevel===6&&currentPart===2&&player.x===sceneStart()+66')).toBe(true);expect(p('player.x-rt.chief.x')).toBe(320);expect(p('player.w===32&&player.h===48&&parkour.state==="normal"')).toBe(true);});
test('pause freezes simulation; resume, hard restart and death respawn reset lead',()=>{const p=load(source('WORKTREE'));start(p);p('update(.1);globalThis.cx=rt.chief.x;pauseGame();update(1)');expect(p('rt.chief.x===cx')).toBe(true);p('resumeGame()');expect(p('player.x-rt.chief.x')).toBe(320);p("kill('test');performance.now=()=>deathDeadline;update(.016)");expect(p('deaths')).toBe(1);expect(p('player.x-rt.chief.x')).toBe(320);p('chiefCatches=4;hardRestart()');expect(p('chiefCatches')).toBe(0);expect(p('rt.chief.active')).toBe(false);});
test('sector 8 interstitial pauses chief; return resets lead and preserves ad cadence',async()=>{const p=load(source('WORKTREE'));start(p,8,2);p("Object.defineProperty(platformAdapter,'hasInterstitial',{value:true,configurable:true});platformAdapter.showInterstitial=()=>new Promise(r=>globalThis.releaseAd=r);collected.add(8*16+2);player.x=sceneStart()+SCENE_W;passScene();for(let i=0;i<80&&currentLevel===8;i++)update(1/60);globalThis.cx=rt.chief.x;update(1)");expect(p('currentLevel')).toBe(9);expect(p('adPending&&systemPaused')).toBe(true);expect(p('rt.chief.x===cx')).toBe(true);p('releaseAd()');await new Promise(r=>setImmediate(r));expect(p('adPending||systemPaused')).toBe(false);expect(p('player.x-rt.chief.x')).toBe(320);expect(source('WORKTREE').match(/if\(levelCompleted&&completedLevel>=6&&completedLevel%4===0\)/)[0]).toBe(source('HEAD').match(/if\(levelCompleted&&completedLevel>=6&&completedLevel%4===0\)/)[0]);});
test('part transition stays live with new lead and camera-relative position',()=>{const p=load(source('WORKTREE'));start(p,6,1);p('collected.add(6*16+1);gate.phase="opening";for(let i=0;i<30;i++)update(1/60);player.x=sceneStart()+SCENE_W;cam=player.x-200;passScene();for(let i=0;i<80&&currentPart===1;i++)update(1/60)');expect(p('currentPart')).toBe(2);expect(p('player.x-rt.chief.x')).toBe(320);expect(p('cam-player.x')).toBe(-200);expect(p('dead||adPending||upgradePending||systemPaused')).toBe(false);});
test('v61 save accepted, schema and locked functions remain identical',()=>{const before=load(source('HEAD')),after=load(source('WORKTREE'));for(const l of [1,16,31])for(const part of [1,2,6]){before(`bgm.pause=()=>{};currentLevel=${l};currentPart=${part};deaths=11`);const saved=before('JSON.stringify(snapshotSave())');expect(after(`validSave(${saved},36)`)).toBe(true);expect(after(`applySave(${saved})`)).toBe(true);expect(after('currentPart')).toBe(Math.min(part,2));expect(after('deaths')).toBe(11);}for(const symbol of ['warnScale','warningDelay','ragePatterns','rageFamily','selectRageMembers','snapshotSave','validSave','applySave']){expect(after(`typeof ${symbol}==='undefined'?'absent':${symbol}.toString().replace(/\\r\\n/g,'\\n')`)).toBe(before(`typeof ${symbol}==='undefined'?'absent':${symbol}.toString().replace(/\\r\\n/g,'\\n')`));}for(const name of ['ROUTE_PARTS','PART_COUNT','SCENE_COUNT','WARNING_MIN_ABS','WARNING_SCALE_END'])expect(after(name)).toBe(before(name));});
test('HUD silhouette and distance meter render without mutating game state',()=>{const p=load(source('WORKTREE'));start(p);const state=p('JSON.stringify({p:player,c:rt.chief,deaths,chiefCatches})');p('drawChief();drawChiefMeter(0,0,100);draw()');expect(p('JSON.stringify({p:player,c:rt.chief,deaths,chiefCatches})')).toBe(state);});
test('stationary catch time measures lead minus catch threshold + grace in each speed band',()=>{const p=load(source('WORKTREE')),catchX=p('CHIEF_CATCH_X');const rows=[];for(const level of [6,16,31]){start(p,level);const r=JSON.parse(p(`JSON.stringify((()=>{let frames=0;while(!dead&&frames<500){update(1/120);frames++;}return{level:currentLevel,seconds:frames/120,caught:rt.chief.caught,deaths,speed:rt.chief.speed}})())`));expect(r.caught).toBe(true);expect(r.deaths).toBe(0);expect(Math.abs(r.seconds-1-(320-catchX)/r.speed)).toBeLessThanOrEqual(1/120);rows.push(r);}console.log('CHIEF_BUFFER='+JSON.stringify(rows));});
test('existing HUD counter includes catches; catch does not repeat a death toast',()=>{const p=load(source('WORKTREE'));start(p);p("deaths=7;deathToast='OLD DEATH';rt.chief.x=player.x;rt.chief.grace=0;update(1/60);globalThis.drawn=[];ctx.fillText=t=>drawn.push(String(t));draw()");expect(p("drawn.find(t=>t.includes('STAMPS')).endsWith('\u{1f480} 7 \u00b7 \u{1f441} 1')")).toBe(true);expect(p("drawn.includes('OLD DEATH')")).toBe(false);expect(p('snapshotSave().deaths')).toBe(7);});

test("chief spawn grace holds exactly one second",()=>{const p=load(source("WORKTREE"));start(p);p("globalThis.cx=rt.chief.x;for(let i=0;i<60;i++)updateChief(1/60)");expect(p("Math.abs(rt.chief.x-cx)")).toBeLessThan(.0001);p("updateChief(1/60)");expect(p("rt.chief.x>cx")).toBe(true);});

test('player jump does not drive chief y; vertical catch threshold is enforced',()=>{const p=load(source('WORKTREE'));start(p);p('rt.chief.grace=0;globalThis.cy=rt.chief.y;player.vy=-560;player.onGround=false;for(let i=0;i<12;i++)updateChief(1/120)');expect(p('rt.chief.y')).toBe(p('cy'));p('rt.chief.x=player.x;rt.chief.y=player.y+PK_BODY_H+20;rt.chief.vy=0;rt.chief.onGround=false;updateChief(1/120)');expect(p('dead')).toBe(false);p('rt.chief.y=player.y;rt.chief.vy=0;updateChief(1/120)');expect(p('dead&&rt.chief.caught')).toBe(true);});

test('chief jumps for its own gap and obstacle cues across all 62 active routes',()=>{const p=load(source('WORKTREE'));let passed=0,jumps=0;for(let level=1;level<=31;level++)for(let part=1;part<=2;part++){start(p,level,part);if(!p('rt.chief.active')){passed++;continue}const r=JSON.parse(p(`JSON.stringify((()=>{rt.chief.grace=0;player.x=sceneStart()+SCENE_W+500;player.y=GROUND-PK_BODY_H;let jumped=false;for(let i=0;i<2400&&rt.chief.x<sceneStart()+SCENE_W;i++){const prior=rt.chief.vy;updateChief(1/120);if(prior>=0&&rt.chief.vy<0)jumped=true;}return{x:rt.chief.x,y:rt.chief.y,jumped,dead}})())`));expect(r.dead,level+'.'+part).toBe(false);expect(r.x,level+'.'+part).toBeGreaterThanOrEqual(p('sceneStart()+SCENE_W'));expect(r.y,level+'.'+part).toBeLessThan(p('GROUND+240'));passed++;jumps+=r.jumped?1:0;}expect(passed).toBe(62);expect(jumps).toBeGreaterThan(0);console.log('CHIEF_ROUTE=62/62 jumps='+jumps);});
