const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path');
const root=path.join(__dirname,'..');let server,base;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/, '')||'index.html';fs.readFile(path.join(root,rel),(e,b)=>{if(e){res.statusCode=404;return res.end('missing')}res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':'application/octet-stream');res.end(b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/index.html`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function boot(page,id='D01',viewport={width:1280,height:720}){await page.setViewportSize(viewport);await page.goto(base+'#debug');await page.waitForFunction(()=>window.__TMB_A12__);await page.locator('.characterChoice:visible').first().click();await page.evaluate(id=>{__TMB_A12__.renderWorldOnRoute(id[0]==='F'?'frozen':'dock31',id);__TMB_A12__.startRoute(id)},id);await page.waitForFunction(id=>__TMB_A12__.getState().route.id===id,id)}

test('18 chief paths are fresh; an in-memory coordinate mutation is rejected',async({page})=>{await boot(page);const result=await page.evaluate(()=>{const ids=Array.from({length:18},(_,i)=>`D${String(i+1).padStart(2,'0')}`);return {fresh:ids.map(id=>[id,__TMB_A12__.chiefPathStatus(id)]),mutated:__TMB_A12__.chiefPathStatus('D01',1)}});for(const [id,s] of result.fresh){console.log(`HASH-${id} | ${s.current} | ${s.valid?'PASS':'FAIL'}`);expect(s.valid).toBe(true)}console.log(`HASH-negative-D01 | stored=${result.mutated.stored} current=${result.mutated.current} | ${!result.mutated.valid?'RED-as-expected':'FAIL'}`);expect(result.mutated.valid).toBe(false)});

for(const id of ['D01','D05']){
  test(`${id} pause delay+0.3 catches once and checkpoint reset is safe inside 2s`,async({page})=>{test.setTimeout(15000);await boot(page,id);await page.keyboard.up('ArrowRight');const delay=id==='D01'?2.5:1.5;await page.waitForFunction(()=>__TMB_A12__.getState().chief.catches===1,null,{timeout:(delay+.3)*1000+1500});const caught=await page.evaluate(()=>__TMB_A12__.getState());expect(caught.chief.lastReturnX).toBe(70);expect(caught.chief.chiefT).toBeGreaterThanOrEqual(-delay);expect(caught.chief.chiefT).toBeLessThan(-delay+.25);await page.waitForTimeout(1900);const after=await page.evaluate(()=>__TMB_A12__.getState());console.log(`PAUSE-${id} delay+0.3 | catches=${after.chief.catches}, return=${after.chief.lastReturnX}, resetChiefT=${caught.chief.chiefT.toFixed(3)} | PASS`);expect(after.chief.catches).toBe(1)});
  test(`${id} pause delay-0.5 does not catch`,async({page})=>{await boot(page,id);await page.keyboard.up('ArrowRight');const delay=id==='D01'?2.5:1.5;await page.waitForTimeout((delay-.5)*1000);const s=await page.evaluate(()=>__TMB_A12__.getState());console.log(`PAUSE-${id} delay-0.5 | catches=${s.chief.catches} | ${s.chief.catches===0?'PASS':'FAIL'}`);expect(s.chief.catches).toBe(0)});
}

for(const id of ['D15','D18'])test(`${id} t~4s pause delay-0.5 does not catch`,async({page})=>{await boot(page,id);await page.evaluate(()=>__TMB_A12__.placePlayerAtChiefTime(4));await page.waitForTimeout(1000);const s=await page.evaluate(()=>__TMB_A12__.getState());console.log(`PAUSE-${id}-T4 delay-0.5 | playerT=${s.chief.playerT.toFixed(3)}, chiefT=${s.chief.chiefT.toFixed(3)}, catches=${s.chief.catches} | ${s.chief.catches===0?'PASS':'FAIL'}`);expect(s.chief.catches).toBe(0)});

test('mid-climb vertical offset uses monotonic x fallback without early catch',async({page})=>{await boot(page,'D01');await page.evaluate(()=>__TMB_A12__.placePlayerAtChiefTime(4,-160));await page.waitForTimeout(100);const mid=await page.evaluate(()=>__TMB_A12__.getState());await page.waitForTimeout(900);const s=await page.evaluate(()=>__TMB_A12__.getState());console.log(`CLIMB-X-FALLBACK | mode=${mid.chief.matchMode}, gap=${(s.chief.playerT-s.chief.chiefT).toFixed(3)}, catches=${s.chief.catches} | ${mid.chief.matchMode==='x'&&s.chief.catches===0?'PASS':'FAIL'}`);expect(mid.chief.matchMode).toBe('x');expect(s.chief.catches).toBe(0)});

test('D01 chief exists on first frame, waits, then starts at delay',async({page})=>{await boot(page,'D01');await page.keyboard.up('ArrowRight');await page.evaluate(()=>{const r=__TMB_A12__.routeDefinition('D01'),s=r.groundSegments.filter(v=>v.x>3000&&v.w>300).sort((a,b)=>b.w-a.w)[0];__TMB_A12__.placePlayer(s.x+s.w/2,s.y-48)});const first=await page.evaluate(()=>__TMB_A12__.getState().chief);expect(first).toBeTruthy();expect(first.active).toBe(true);await page.waitForTimeout(2100);const waiting=await page.evaluate(()=>__TMB_A12__.getState().chief);expect(waiting.x).toBeCloseTo(first.x,1);await page.waitForTimeout(650);const moving=await page.evaluate(()=>__TMB_A12__.getState().chief);console.log(`START-D01 | first=${first.x.toFixed(3)}, waiting=${waiting.x.toFixed(3)}, afterDelay=${moving.x.toFixed(3)} | PASS`);expect(moving.x).toBeGreaterThan(waiting.x)});

for(const id of ['D01','D05'])test(`${id} touch 390x844 has active recorded chief`,async({browser})=>{const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1}),page=await context.newPage();try{await boot(page,id,{width:390,height:844});const s=await page.evaluate(()=>__TMB_A12__.getState());expect(s.chief.active).toBe(true);expect(s.chief.delay).toBe(id==='D01'?2.5:1.5);console.log(`TOUCH-${id}-390x844 | active=${s.chief.active}, delay=${s.chief.delay} | PASS`)}finally{await context.close()}});

test('F01 without recording keeps 306082d null-chief behavior',async({page})=>{await boot(page,'F01');await page.keyboard.up('ArrowRight');const s=await page.evaluate(()=>__TMB_A12__.getState());console.log(`LEGACY-F01 | chief=${s.chief} | ${s.chief===null?'PASS':'FAIL'}`);expect(s.chief).toBeNull()});
