const {test,expect}=require('playwright/test');
const {load,source}=require('./phase3-verify.cjs');
test.setTimeout(3600000);
const bot=String.raw`globalThis.parkourBot=(level,part,hz,blind=false,beamWidth=48,knownPlan=null)=>{currentLevel=level;currentPart=part;chiefCatches=0;partDeaths=deaths=coins=0;collected.clear();speedLevel=jumpLevel=0;dead=won=upgradePending=characterSelectOpen=livesPending=adPending=false;resetScene();spawnGrace=0;const start=sceneStart(),states=new Set(),target=coinPos(scene(),part);let frames=0;
 if(level===2){let jumped=false;for(let i=0;i<hz*5&&!dead;i++){const x=player.x-start,feet=player.y+player.h;keys.right=x<164||player.onGround&&feet===GROUND;keys.left=keys.jump=false;if(!jumped&&player.onGround&&x<140){keys.jump=true;jumped=true;}if(x<140&&!player.onGround&&feet<=GROUND-PK_WALL_HEIGHT+PK_WALL_RISE&&Math.abs(140-x-player.w)<=4&&parkour.state==='normal')keys.jump=true;if(player.onGround&&feet===GROUND&&x>164&&x<220)keys.jump=true;update(1/hz);states.add(parkour.state);frames++;if(player.x-start>280)break;}}
 const capture=()=>({p:{...player},r:JSON.parse(JSON.stringify(rt)),pk:JSON.parse(JSON.stringify(parkour)),c:[...collected],v:[currentLevel,currentPart,dead,won,deaths,partDeaths,coins,lives,jumpBufferT,coyoteT,speedHold,speedHoldDir,spawnGrace,upgradePending,characterSelectOpen,livesPending,adPending,totalTime,cachedGeometryLevel,chiefCatches],g:[cachedGroundSegments,cachedStaticPlatforms,cachedSolidRects]});
 const restore=s=>{Object.assign(player,s.p);rt=JSON.parse(JSON.stringify(s.r));Object.assign(parkour,JSON.parse(JSON.stringify(s.pk)));collected.clear();s.c.forEach(c=>collected.add(c));[currentLevel,currentPart,dead,won,deaths,partDeaths,coins,lives,jumpBufferT,coyoteT,speedHold,speedHoldDir,spawnGrace,upgradePending,characterSelectOpen,livesPending,adPending,totalTime,cachedGeometryLevel,chiefCatches]=s.v;[cachedGroundSegments,cachedStaticPlatforms,cachedSolidRects]=s.g;keys.jump=keys.left=keys.right=false;};
 const advance=(dir,jumpAt,n,record=false)=>{for(let i=0;i<n&&!dead&&!won&&currentLevel===level&&currentPart===part&&!upgradePending;i++){keys.right=dir>0;keys.left=dir<0;keys.jump=i===jumpAt;if(level===2&&part===2&&!player.onGround&&coyoteT>0&&player.x>=rt.mind.memoryBeam.x+rt.mind.memoryBeam.w)keys.jump=true;update(1/hz);if(record)states.add(parkour.state);}};
 const initial=capture(),actions=[[1,false,0],[1,true,0],[1,true,Math.round(hz*.05)],[0,false,0],[0,true,0],[-1,false,0],[-1,true,0]],ticks=Math.round(hz*.1),move=rt.parkourLayer.move;let beam=[{s:initial,path:[],seen:[...states]}],winner=knownPlan?{path:knownPlan}:null,bestNode=beam[0];
 for(let depth=0;depth<180&&!winner;depth++){const next=[],dedup=new Set();for(const node of beam){for(let ai=0;ai<actions.length;ai++){restore(node.s);const [dir,jump,press]=actions[ai],seen=new Set(node.seen);for(let i=0;i<ticks&&!dead&&!won&&currentLevel===level&&currentPart===part;i++){keys.right=dir>0;keys.left=dir<0;keys.jump=jump&&i===press;if(level===2&&part===2&&!player.onGround&&coyoteT>0&&player.x>=rt.mind.memoryBeam.x+rt.mind.memoryBeam.w)keys.jump=true;update(1/hz);seen.add(parkour.state);}if(dead)continue;const path=node.path.concat(ai),got=collected.has(level*16+part),cleared=won||currentLevel!==level||currentPart!==part;if(cleared){if(seen.has(move)){winner={path,seen:[...seen]};break}continue}const key=[Math.round(player.x/8),Math.round(player.y/8),Math.round(coyoteT*40),Math.round(player.vx/40),Math.round(player.vy/100),parkour.state,got,rt.armed,rt.mind.stage,Math.round(rt.warning*5),seen.has(move)].join(':');if(dedup.has(key))continue;dedup.add(key);const main=rt.parkourLayer.rects.find(s=>s.parkour===move),gx=seen.has(move)?target.x:start+(main?main.x-player.w:rt.parkourLayer.drop.x+100),gy=seen.has(move)?target.y:move==='wallRun'?main.y+20-player.h:move==='slide'?main.y+main.h+PK_BEAM_CLEARANCE-player.h:move==='vault'?main.y+main.h-player.h:GROUND-player.h,distance=got?start+SCENE_W-player.x:Math.abs(gx-player.x)+(seen.has(move)?Math.max(0,player.y-gy):Math.abs(player.y-gy))*1.5,score=(got?10000:0)-distance+(seen.has(move)?5000:0)+(player.onGround?3:0)-Math.max(0,player.y-(GROUND-player.h))*4;next.push({s:capture(),path,seen:[...seen],score});}if(winner)break;}next.sort((a,b)=>b.score-a.score);beam=next.slice(0,beamWidth);if(!beam.length)break;bestNode=beam[0];}
 restore(initial);const route=winner?.path||bestNode.path;for(const ai of route){const [dir,jump,press]=actions[ai];advance(dir,jump?press:-1,ticks,true);frames+=ticks;}
 return{level,part,catches:chiefCatches,plan:winner?.path||null,used:states.has(move),dead,clear:won||currentLevel!==level||currentPart!==part,states:[...states],x:player.x-start,frames,cause:dead?deathToast:null};};`;
test('informed bot: all 62 segments, actual movement and five full replays',()=>{const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),p=load(source('WORKTREE'));p(bot);const report=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'tmb-tur2-bot-')),'report.json');console.log('BOT_REPORT='+report);const rows=[],cached=fs.existsSync(process.env.TMB_BOT_PLAN_REPORT||path.join(__dirname,'parkour-plans.json'))?JSON.parse(fs.readFileSync(process.env.TMB_BOT_PLAN_REPORT||path.join(__dirname,'parkour-plans.json'),'utf8')):[];for(let l=1;l<=31;l++)for(let part=1;part<=2;part++){let first;const prior=cached.find(r=>r.level===l&&r.part===part&&r.plan);if(prior)first=JSON.parse(p(`JSON.stringify(parkourBot(${l},${part},60,false,48,${JSON.stringify(prior.plan)}))`));for(const width of [48,160,320]){if(first?.clear&&!first.dead&&first.used)break;first=JSON.parse(p(`JSON.stringify(parkourBot(${l},${part},60,false,${width}))`));if(first.clear&&!first.dead&&first.used)break;}rows.push({...first,run:1});for(let run=2;run<=5;run++)rows.push(first.plan?{...JSON.parse(p(`JSON.stringify(parkourBot(${l},${part},60,false,48,${JSON.stringify(first.plan)}))`)),run}:{level:l,part,run,clear:false,reason:'No verified plan'});fs.writeFileSync(report,JSON.stringify(rows));console.log(`bot ${l}.${part}: ${rows.slice(-5).filter(r=>r.clear&&!r.dead&&r.used).length}/5`);}fs.writeFileSync(report,JSON.stringify(rows));expect(rows).toHaveLength(310);expect(rows.filter(r=>!r.clear||r.dead||!r.used).map(({plan,...r})=>r)).toEqual([]);});
test('every movement in >=3 sectors; sign rates exactly match each band',()=>{const p=load(source('WORKTREE'));const r=JSON.parse(p(`JSON.stringify({moves:PK_SECTOR_MOVES,bands:[[1,5],[6,15],[16,30],[31,31]].map(([a,b])=>{let total=0,lies=0;for(let l=a;l<=b;l++)for(let part=1;part<=2;part++)for(const s of parkourLayout(l,part).signs){total++;lies+=s.lie?1:0}return{total,lies}})})`));for(const move of ['vault','slide','roll','wallRun'])expect(r.moves.filter(m=>m===move).length).toBeGreaterThanOrEqual(3);expect(r.bands.map(b=>b.lies/b.total)).toEqual([0,.2,.35,.5]);});
