const {test,expect}=require('playwright/test');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
let server,base;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/+/, '')||'index.html';fs.readFile(path.join(__dirname,'..',rel),(err,b)=>{res.statusCode=err?404:200;res.end(err?'missing':b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/#debugParkour`;});
test.afterAll(async()=>{await new Promise(r=>server.close(r))});
test.beforeEach(async({page})=>{await page.goto(base);await page.waitForFunction(()=>window.__tmb?.platform.initialized&&window.__tmbParkour);await page.evaluate(()=>{__tmbPause();__tmbParkour.manual();__tmbParkour.setup()})});
for(const kind of ['vault','slide','wallRun'])for(const dir of [-1,1])test(`${kind} direction ${dir}: enter/body/cancel/death/reset`,async({page})=>{
 const a=await page.evaluate(({kind,dir})=>{const h=__tmbParkour;h.setup(kind,dir);const before=h.read();h.press();h.step(1/60);return{before,after:h.read()}},{kind,dir});
 expect(a.after.state).toBe(kind);expect(a.after.player.w).toBe(32);expect(a.after.player.h).toBe(kind==='slide'?24:48);expect(a.after.hurtbox.h).toBe(kind==='slide'?16:40);
 if(kind==='wallRun')expect(a.after.player.y).toBeLessThan(a.before.player.y);
 const b=await page.evaluate(()=>{const h=__tmbParkour;h.cancel();h.step(1/60);const cancelled=h.read();h.kill();const killed=h.read();h.reset();return{cancelled,killed,reset:h.read()}});
 expect(b.cancelled.state).toBe('normal');expect(b.killed.dead).toBe(true);expect(b.killed.player.h).toBe(48);expect(b.reset.state).toBe('normal');expect(b.reset.player.h).toBe(48);
});
for(const hz of [30,60,120])test(`vault finishes without penetration ${hz} Hz`,async({page})=>{const r=await page.evaluate(hz=>{const h=__tmbParkour;h.setup('vault');const start=h.read();h.press();for(let i=0;i<Math.ceil(.29*hz);i++)h.step(1/hz);return{start,end:h.read()}},hz);expect(r.end.state).toBe('normal');expect(r.end.player.y).toBeCloseTo(r.start.player.y-24,2);expect(r.end.player.x).toBeGreaterThan(r.start.player.x);});
test('roll buffer, roll cancel and debug-only stun',async({page})=>{const r=await page.evaluate(()=>{const h=__tmbParkour;function fall(press){h.setup('roll');h.stop();for(let i=0;i<160;i++){const s=h.read();if(press&&s.player.vy>0&&s.player.y+s.player.h>400)h.press();h.step(1/120);if(h.read().player.onGround)return h.read()}return h.read()}const stun=fall(false),roll=fall(true);h.cancel();return{stun,roll,cancel:h.read()}});expect(r.stun.state).toBe('stun');expect(r.roll.state).toBe('roll');expect(r.roll.player.h).toBe(48);expect(r.cancel.state).toBe('normal');});
test('slide stays crouched under ceiling and resumes standing outside',async({page})=>{const r=await page.evaluate(()=>{const h=__tmbParkour;h.setup('slide');h.press();for(let i=0;i<30;i++)h.step(1/120);h.stop();for(let i=0;i<120;i++)h.step(1/120);return h.read()});expect(r.state).toBe('slide');expect(r.player.h).toBe(24);});
for(let id=0;id<4;id++)test(`character ${id}: keyboard repeat, touch and boost fallback`,async({page})=>{await page.evaluate(id=>{__tmbParkour.character(id);__tmbParkour.setup('slide')},id);await page.evaluate(()=>{window.dispatchEvent(new KeyboardEvent('keydown',{key:' ',repeat:true}));__tmbParkour.step(1/60)});expect((await page.evaluate(()=>__tmbParkour.read())).state).toBe('normal');await page.evaluate(()=>{__tmbParkour.setup('slide');document.querySelector('#jumpWrap button').dispatchEvent(new PointerEvent('pointerdown',{pointerId:77,bubbles:true}));__tmbParkour.manual();__tmbParkour.step(1/60)});expect((await page.evaluate(()=>__tmbParkour.read())).state).toBe('slide');const r=await page.evaluate(()=>{const h=__tmbParkour;h.setup('vault');h.boost();h.press();h.step(1/60);return h.read()});expect(r.state).toBe('normal');expect(r.player.vy).toBeLessThan(0);});
test('untagged fixture falls back to normal jump',async({page})=>{const r=await page.evaluate(()=>{const h=__tmbParkour;h.setup('none');h.press();h.step(1/60);return h.read()});expect(r.state).toBe('normal');expect(r.player.vy).toBeLessThan(0);});

for(const kind of ['vault','slide','wallRun'])test(`${kind} invalid geometry does not consume jump`,async({page})=>{const r=await page.evaluate(kind=>{const h=__tmbParkour;h.setup(kind==='wallRun'?'vault':kind);h.obstacle({parkour:kind,w:500,y:100,h:10});h.press();h.step(1/60);return h.read()},kind);expect(r.state).toBe('normal');expect(r.player.vy).toBeLessThan(0)});
test('keyboard starts contextual movement; release cancels wall-run',async({page})=>{const r=await page.evaluate(()=>{const h=__tmbParkour;h.setup('wallRun');window.dispatchEvent(new KeyboardEvent('keydown',{key:' '}));h.manual();h.step(1/60);const active=h.read();window.dispatchEvent(new KeyboardEvent('keyup',{key:'ArrowRight'}));h.step(1/60);return{active,end:h.read()}});expect(r.active.state).toBe('wallRun');expect(r.end.state).toBe('normal')});
test('roll death, reset and pause clear body/state',async({page})=>{const r=await page.evaluate(()=>{const h=__tmbParkour;h.setup('roll');h.stop();for(let i=0;i<160;i++){const s=h.read();if(s.player.vy>0&&s.player.y+s.player.h>400)h.press();h.step(1/120);if(h.read().state==='roll')break}const active=h.read();h.kill();const killed=h.read();h.reset();h.pause();return{active,killed,end:h.read()}});expect(r.active.state).toBe('roll');expect(r.killed.state).toBe('normal');expect(r.killed.player.h).toBe(48);expect(r.end.state).toBe('normal')});

test('pause under beam cancels action without expanding into ceiling',async({page})=>{const r=await page.evaluate(()=>{const h=__tmbParkour;h.setup('slide');h.press();for(let i=0;i<30;i++)h.step(1/120);h.stop();const before=h.read();h.pause();const paused=h.read();h.manual();h.move(1);for(let i=0;i<120;i++)h.step(1/120);return{before,paused,end:h.read()}});expect(r.paused.state).toBe('crouch');expect(r.paused.player.h).toBe(24);expect(r.paused.player.y).toBe(r.before.player.y);expect(r.end.state).toBe('normal');expect(r.end.player.h).toBe(48)});
for(const hz of [30,60,120])test(`slide, roll, wall-run duration and geometry ${hz} Hz`,async({page})=>{const r=await page.evaluate(hz=>{const h=__tmbParkour;h.setup('wallRun');const start=h.read();h.press();let highest=start.player.y;for(let i=0;i<Math.ceil(.35*hz);i++){h.step(1/hz);highest=Math.min(highest,h.read().player.y)}const wall=h.read();h.setup('slide');h.press();for(let i=0;i<Math.ceil(1*hz);i++)h.step(1/hz);const slide=h.read();h.setup('roll');h.stop();for(let i=0;i<Math.ceil(1*hz);i++){const s=h.read();if(s.player.vy>0&&s.player.y+s.player.h>400)h.press();h.step(1/hz);if(h.read().state==='roll')break}const roll=h.read();for(let i=0;i<Math.ceil(.3*hz);i++)h.step(1/hz);return{rise:start.player.y-highest,wall,slide,roll,end:h.read()}},hz);expect(r.rise).toBeLessThanOrEqual(30.001);expect(r.wall.state).toBe('normal');expect(r.slide.player.h).toBe(48);expect(r.roll.state).toBe('roll');expect(r.end.state).toBe('normal')});
