const {test,expect}=require('playwright/test');
const fs=require('fs'),path=require('path'),http=require('http');
const root=path.resolve(__dirname,'..');let server,origin;
test.use({viewport:{width:390,height:844},hasTouch:true});
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://x').pathname.slice(1)||'index.html';try{let b=fs.readFileSync(path.join(root,rel));if(rel==='js/a12-campaign.js')b=Buffer.from(b.toString().replace('if (DEBUG) {','if (DEBUG) { window.workerProbe=code=>eval(code);'));res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':rel.endsWith('.png')?'image/png':'application/octet-stream');res.end(b)}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function open(page){await page.addInitScript(()=>{window.__workerAudio={events:[],starts:[]};document.addEventListener('tmb:sfx',e=>window.__workerAudio.events.push(e.detail?.name));const start=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...a){window.__workerAudio.starts.push(this.buffer?.duration||0);return start.apply(this,a)}});await page.goto(`${origin}/index.html#debug`);await page.waitForFunction(()=>window.__TMB_A12__,null,{timeout:10000});await page.locator('.characterChoice:visible').first().click();await page.evaluate(()=>__TMB_A12__.startRoute('D01'))}
test('worker barrel audio is absent while audio bus remains live',async({page})=>{test.setTimeout(25000);await open(page);await page.waitForTimeout(14500);await page.evaluate(()=>{const cp=__TMB_A12__.getState().route.checkpoints[1];__TMB_A12__.placePlayer(cp-45)});await page.keyboard.down('ArrowRight');await page.waitForTimeout(600);await page.keyboard.up('ArrowRight');const a=await page.evaluate(()=>window.__workerAudio);const barrelBuffers=a.starts.filter(v=>v>=.24&&v<=.26).length,barrelEvents=a.events.filter(v=>v==='barrel').length,otherEvents=a.events.filter(v=>v!=='barrel').length;console.log('WORKER_AUDIO',JSON.stringify({seconds:15.1,barrelEvents,barrelBuffers,otherEvents,events:a.events}));expect(barrelEvents).toBe(0);expect(barrelBuffers).toBe(0);expect(otherEvents).toBeGreaterThan(0)});
test('stomp disables worker without changing chief and side contact does not',async({page})=>{await open(page);const worker=await page.evaluate(()=>__TMB_A12__.getState().route.obstacles.find(o=>o.type==='worker'));await page.evaluate(w=>__TMB_A12__.placePlayer(w.x,w.baseY-84-64-60),worker);await page.waitForTimeout(100);const chiefBefore=await page.evaluate(()=>__TMB_A12__.getState().chief);await expect.poll(()=>page.evaluate(()=>__TMB_A12__.getState().worker?.disabled),{timeout:4000}).toBe(true);const landed=await page.evaluate(()=>__TMB_A12__.getState()),ids=new Set(landed.barrels.map(b=>b.id));expect(landed.chief.catches).toBe(chiefBefore.catches);await page.waitForTimeout(5000);const after=await page.evaluate(()=>__TMB_A12__.getState()),newBarrels=after.barrels.filter(b=>!ids.has(b.id)).length;console.log('WORKER_STOMP',JSON.stringify({worker:after.worker,newBarrelsAfter5s:newBarrels,chiefBefore,chiefAtStomp:landed.chief,chiefAfter5s:after.chief}));expect(newBarrels).toBe(0);await page.evaluate(()=>{__TMB_A12__.startRoute('D01');const w=__TMB_A12__.getState().route.obstacles.find(o=>o.type==='worker');__TMB_A12__.placePlayer(w.x-80,w.baseY-64);document.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',code:'ArrowRight',bubbles:true}))});await page.waitForTimeout(800);const side=await page.evaluate(()=>{document.dispatchEvent(new KeyboardEvent('keyup',{key:'ArrowRight',code:'ArrowRight',bubbles:true}));return __TMB_A12__.getState().worker});expect(side.disabled).toBe(false)});
test('disabled worker drawing differs from standing worker ROI',async({page})=>{await open(page);const result=await page.evaluate(async()=>{const w=__TMB_A12__.getState().route.obstacles.find(o=>o.type==='worker');__TMB_A12__.placePlayer(w.x-120,w.baseY-64);await new Promise(r=>setTimeout(r,250));const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),layout=__tmb.layout,roi=()=>{const cam=__tmb.cam,x=Math.max(0,Math.floor((w.x-65-cam)*layout.viewScale)),y=Math.max(0,Math.floor((w.baseY-115+layout.worldY)*layout.viewScale)),ww=Math.min(canvas.width-x,150),hh=Math.min(canvas.height-y,125);return [...ctx.getImageData(x,y,ww,hh).data]};const standing=roi();__TMB_A12__.placePlayer(w.x,w.baseY-84-64-60);for(let i=0;i<240&&!__TMB_A12__.getState().worker?.disabled;i++)await new Promise(r=>requestAnimationFrame(r));await new Promise(r=>requestAnimationFrame(r));const fallen=roi();let difference=0;for(let i=0;i<Math.min(standing.length,fallen.length);i++)if(standing[i]!==fallen[i])difference++;return{difference,disabled:__TMB_A12__.getState().worker?.disabled,samples:Math.min(standing.length,fallen.length)}});console.log('WORKER_ROI',JSON.stringify(result));expect(result.disabled).toBe(true);expect(result.difference).toBeGreaterThan(0)});
test('barrels follow D01 surfaces, fall at edges and break on tall faces',async({page})=>{
  test.setTimeout(20000);await open(page);
  const result=await page.evaluate(async()=>{
    const surfaces=workerProbe('routeSurfaces(route).filter(s=>s.kind==="ground")'),seen=new Map(),removed=new Set();
    let supported=0,maxSupportError=0,falling=0,maxPenetration=0,tallFaceId=null;
    for(let frame=0;frame<720;frame++){
      await new Promise(r=>requestAnimationFrame(r));
      if(frame===500)workerProbe('workerDisabled=true;barrels=[{id:"tall-face-probe",x:9820,y:250,vx:-185,vy:0,life:8,warning:0}]');
      const barrels=__TMB_A12__.getState().barrels,current=new Set(barrels.map(b=>b.id));
      for(const [id,last] of seen)if(!current.has(id)&&last.x>9770&&last.x<9920)removed.add(id);
      for(const b of barrels){
        const last=seen.get(b.id);seen.set(b.id,{x:b.x,y:b.y,vy:b.vy});
        const under=surfaces.filter(s=>b.x+28>s.x&&b.x<s.x+s.w&&s.y>=b.y+28-2).sort((a,c)=>a.y-c.y)[0];
        if(under&&Math.abs(b.y+28-under.y)<=2){supported++;maxSupportError=Math.max(maxSupportError,Math.abs(b.y+28-under.y))}
        if(last&&b.vy>0&&b.y>last.y)falling++;
        for(const s of surfaces){const ox=Math.min(b.x+28,s.x+s.w)-Math.max(b.x,s.x),oy=Math.min(b.y+28,s.y+s.h)-Math.max(b.y,s.y);if(ox>0&&oy>0)maxPenetration=Math.max(maxPenetration,Math.min(ox,oy))}
        if(b.id==='tall-face-probe')tallFaceId=b.id;
      }
    }
    return{supported,maxSupportError,falling,maxPenetration,tallFaceId,tallFaceRemoved:tallFaceId?removed.has(tallFaceId):false,barrelIds:[...seen.keys()]};
  });
  console.log('BARREL_SURFACES',JSON.stringify(result));
  expect(result.supported).toBeGreaterThan(0);expect(result.maxSupportError).toBeLessThanOrEqual(2);expect(result.falling).toBeGreaterThan(0);expect(result.tallFaceId).toBeTruthy();expect(result.tallFaceRemoved).toBe(true);expect(result.maxPenetration).toBeLessThanOrEqual(2);
});
