const {test,expect,devices}=require('playwright/test');
const fs=require('fs'),path=require('path'),http=require('http');
const {runBot}=require('./lib/bot-s-drive.cjs');
const root=path.resolve(__dirname,'..');let server,origin;
const pixel=devices['Pixel 7'];
test.use({...pixel,viewport:{width:pixel.viewport.height,height:pixel.viewport.width},isMobile:true,hasTouch:true,launchOptions:{args:['--autoplay-policy=user-gesture-required']}});
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://x').pathname.slice(1)||'index.html';try{const b=fs.readFileSync(path.join(root,rel));res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':rel.endsWith('.ogg')?'audio/ogg':'application/octet-stream');res.end(b)}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function open(page){await page.goto(`${origin}/index.html#debug`);await page.waitForFunction(()=>window.__tmb&&window.__tmbAudio&&window.__TMB_A12__)}

test('safe-area keeps camera framing centered and controls on their safe side',async({page})=>{
  await open(page);const cdp=await page.context().newCDPSession(page),rows=[];
  for(const [name,left,right] of [['none',0,0],['left',45,0],['right',0,45]]){
    await cdp.send('Emulation.setSafeAreaInsetsOverride',{insets:{top:0,left,bottom:0,right}});await page.evaluate(()=>dispatchEvent(new Event('resize')));await page.waitForTimeout(50);
    const row=await page.evaluate(()=>{const l=__tmb.layout,s=v=>v*l.viewScale,joy=document.querySelector('#joystick').getBoundingClientRect(),jump=document.querySelector('#jumpWrap').getBoundingClientRect();return{center:(l.gameRect.x+s(l.safeLeft)+(l.gameRect.w-s(l.safeLeft+l.safeRight))/2)-innerWidth/2,pad:l.cameraPadLeft,joyLeft:joy.left,jumpRight:innerWidth-jump.right,safeLeft:s(l.safeLeft),safeRight:s(l.safeRight)}});rows.push({name,...row});
    expect(Math.abs(row.center),name).toBeLessThanOrEqual(1);expect(row.joyLeft+1,name).toBeGreaterThanOrEqual(left);expect(row.jumpRight+1,name).toBeGreaterThanOrEqual(right);
  }
  expect(Math.abs(rows[1].pad-rows[2].pad)).toBeLessThanOrEqual(1);console.log('MOBILE_SAFE',JSON.stringify(rows));
});

test('fullscreen control is reachable in landscape without covering play UI',async({page,browser})=>{
  const cases=[['none',0,0],['left',45,0],['right',0,45]],rows=[];
  await open(page);await page.locator('.characterChoice:visible').first().click();const cdp=await page.context().newCDPSession(page);
  for(const [name,left,right] of cases){
    await cdp.send('Emulation.setSafeAreaInsetsOverride',{insets:{top:0,left,bottom:0,right}});await page.evaluate(()=>dispatchEvent(new Event('resize')));await page.waitForTimeout(50);
    const button=page.locator('#fullscreenBtn');await expect(button,name).toBeVisible();
    rows.push(await page.evaluate(name=>{const r=e=>{const x=e.getBoundingClientRect();return{x:x.left,y:x.top,w:x.width,h:x.height,right:x.right,bottom:x.bottom}},hit=(a,b)=>Math.max(0,Math.min(a.right,b.right)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.y,b.y)),b=r(fullscreenBtn),l=__tmb.layout,s=v=>v*l.viewScale,canvasRect=x=>({x:l.viewOffsetX+s(x.x),y:l.viewOffsetY+s(x.y),w:s(x.w),h:s(x.h),right:l.viewOffsetX+s(x.x+x.w),bottom:l.viewOffsetY+s(x.y+x.h)}),runner=canvasRect(l.runner),targets={hud:canvasRect(l.hud),pause:r(pauseBtn),mute:r(muteBtn),swap:r(characterChange),joystick:r(document.querySelector('#joystick')),jump:r(document.querySelector('#jumpWrap button'))};return{name,button:b,intersections:Object.fromEntries(Object.entries({...targets,runner}).map(([k,v])=>[k,hit(b,v)]))}},name));
  }
  await page.locator('#fullscreenBtn').click();await page.waitForFunction(()=>!!(document.fullscreenElement||document.webkitFullscreenElement));await expect(page.locator('#fullscreenBtn')).toBeHidden();await page.evaluate(()=>document.exitFullscreen());await expect(page.locator('#fullscreenBtn')).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>dispatchEvent(new Event('orientationchange')));await expect(page.locator('#fullscreenBtn')).toBeHidden();
  const hiddenCases=[['desktop',{viewport:{width:1280,height:720},hasTouch:false,isMobile:false},null],['native',{...pixel,viewport:{width:pixel.viewport.height,height:pixel.viewport.width}},()=>{window.Capacitor={isNativePlatform:()=>true}}],['playables',{...pixel,viewport:{width:pixel.viewport.height,height:pixel.viewport.width}},()=>{window.ytgame={IN_PLAYABLES_ENV:true}}]];
  for(const [name,options,init] of hiddenCases){const context=await browser.newContext(options);if(init)await context.addInitScript(init);const candidate=await context.newPage();await open(candidate);await expect(candidate.locator('#fullscreenBtn'),name).toBeHidden();await context.close()}
  for(const row of rows.filter(x=>x.intersections))for(const [target,area] of Object.entries(row.intersections))expect(area,`${row.name}:${target}`).toBe(0);console.log('MOBILE_FULLSCREEN',JSON.stringify(rows));
});

test('audio unlock retries after a resume that resolves while still suspended',async({page})=>{
  await page.addInitScript(()=>{window.__blockAudioResume=true;const A=window.AudioContext||window.webkitAudioContext,raw=A.prototype.resume,failed=new WeakSet(),resumed=new WeakSet();let owner=A.prototype,state;while(owner&&!(state=Object.getOwnPropertyDescriptor(owner,'state')))owner=Object.getPrototypeOf(owner);A.prototype.resume=function(){if(window.__blockAudioResume){failed.add(this);return Promise.resolve()}resumed.add(this);return raw.call(this)};Object.defineProperty(A.prototype,'state',{configurable:true,get(){return failed.has(this)&&!resumed.has(this)?'suspended':state.get.call(this)}})});await open(page);
  await page.evaluate(()=>dispatchEvent(new Event('click')));await page.waitForTimeout(50);expect((await page.evaluate(()=>__tmbAudio.state().context))).toBe('suspended');
  await page.evaluate(()=>window.__blockAudioResume=false);await page.evaluate(()=>dispatchEvent(new Event('click')));await page.waitForFunction(()=>__tmbAudio.state().context==='running');const start=await page.evaluate(()=>__tmbAudio.state().clock);await page.waitForFunction(x=>__tmbAudio.state().clock>x+.001,start);
  const reading=await page.evaluate(async()=>{void __tmbAudio.play('land');let db=-Infinity,end=performance.now()+1000;while(performance.now()<end){db=Math.max(db,__tmbAudio.sample('sfx').db);await new Promise(r=>setTimeout(r,5))}return{db,a5:__tmbAudio.state(),legacy:__tmb.audio}});expect(reading.db).toBeGreaterThan(-40);expect(reading.legacy.acState).toBe('running');console.log('MOBILE_AUDIO',JSON.stringify(reading));
});

test('audio unlock retries when the first resume promise never settles',async({page})=>{
  await page.addInitScript(()=>{const A=window.AudioContext||window.webkitAudioContext,raw=A.prototype.resume,calls=new WeakMap(),blocked=new WeakSet(),resumed=new WeakSet();let owner=A.prototype,state;while(owner&&!(state=Object.getOwnPropertyDescriptor(owner,'state')))owner=Object.getPrototypeOf(owner);window.__armPendingResume=()=>{window.__pendingResumeArmed=true};A.prototype.resume=function(){if(!window.__pendingResumeArmed){blocked.add(this);return Promise.resolve()}const n=(calls.get(this)||0)+1;calls.set(this,n);if(n===1){blocked.add(this);return new Promise(()=>{})}resumed.add(this);return raw.call(this)};Object.defineProperty(A.prototype,'state',{configurable:true,get(){return blocked.has(this)&&!resumed.has(this)?'suspended':state.get.call(this)}})});await open(page);await page.evaluate(()=>__armPendingResume());
  await page.evaluate(()=>dispatchEvent(new Event('click')));await page.waitForTimeout(50);expect((await page.evaluate(()=>__tmbAudio.state().context))).toBe('suspended');
  await page.evaluate(()=>dispatchEvent(new Event('click')));await page.waitForFunction(()=>__tmbAudio.state().context==='running');const start=await page.evaluate(()=>__tmbAudio.state().clock);await page.waitForFunction(x=>__tmbAudio.state().clock>x+.001,start);
  const reading=await page.evaluate(async()=>{void __tmbAudio.play('land');let db=-Infinity,end=performance.now()+1000;while(performance.now()<end){db=Math.max(db,__tmbAudio.sample('sfx').db);await new Promise(r=>setTimeout(r,5))}return{db,legacy:__tmb.audio}});expect(reading.db).toBeGreaterThan(-40);expect(reading.legacy.acState).toBe('running');console.log('MOBILE_AUDIO_PENDING',JSON.stringify(reading));
});

test('landscape campaign framing keeps the runner in the lower gameplay band',async({page})=>{
  test.setTimeout(120000);await open(page);await page.evaluate(()=>{__TMB_A12__.startRoute('D01');window.__frameSamples=[];let raw=window.__tmbCampaignStep;window.__tmbCampaignStep=dt=>{raw(dt);const l=__tmb.layout,s=v=>v*l.viewScale,state=__TMB_A12__.getState(),r={x:l.viewOffsetX+s(l.runner.x),y:l.viewOffsetY+s(l.worldY+l.runner.y),w:s(l.runner.w),h:s(l.runner.h)},h={x:l.viewOffsetX+s(l.hud.x),y:l.viewOffsetY+s(l.hud.y),w:s(l.hud.w),h:s(l.hud.h)},foot=(r.y+r.h)/innerHeight,ground=(l.viewOffsetY+s(state.cameraWorldY+state.cameraGroundFootY))/innerHeight;window.__frameSamples.push({foot,ground,onGround:state.player.onGround,hit:r.x<h.x+h.w&&r.x+r.w>h.x&&r.y<h.y+h.h&&r.y+r.h>h.y})}});
  const bot=await runBot(page,'D01',{resume:true,live:true}),samples=await page.evaluate(()=>__frameSamples),grounded=samples.filter(x=>x.onGround).map(x=>x.foot).sort((a,b)=>a-b),feet=samples.map(x=>x.foot),median=grounded[Math.floor(grounded.length/2)],min=Math.min(...feet),max=Math.max(...feet),hits=samples.filter(x=>x.hit).length,jumpRise=Math.max(...samples.filter(x=>!x.onGround).map(x=>x.ground-x.foot));
  console.log('MOBILE_FRAMING',JSON.stringify({median,min,max,jumpRise,hits,bot:{finished:bot.finished,deaths:bot.deaths,game_s:bot.game_s}}));expect(median).toBeGreaterThanOrEqual(.58);expect(median).toBeLessThanOrEqual(.64);expect(min).toBeGreaterThanOrEqual(.25);expect(max).toBeLessThanOrEqual(.80);expect(jumpRise).toBeGreaterThanOrEqual(.10);expect(hits).toBe(0);
});

test('landscape shop fits preview cards prices and bottom actions',async({page})=>{
  await open(page);await page.evaluate(()=>__TMB_A12__.startRoute('D01'));
  const ghostText=()=>page.evaluate(()=>[...document.querySelectorAll('#a12Shop [data-list]:not([hidden]) article')].flatMap(card=>[...card.querySelectorAll('*')].flatMap(el=>{if(el.matches('h3,.priceBadge'))return[];const text=[...el.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent).join('').trim(),cs=getComputedStyle(el),rect=el.getBoundingClientRect();if(!text||cs.display==='none'||cs.visibility==='hidden'||!rect.width||!rect.height)return[];let opacity=1,node=el;while(node&&node!==card.parentElement){opacity*=Number(getComputedStyle(node).opacity);node=node.parentElement}return opacity>0&&opacity<.9?[{item:card.dataset.item,text,opacity}]:[]})));
  const actionFacts=()=>page.evaluate(()=>[...document.querySelectorAll('#a12Shop [data-list]:not([hidden]) article')].map(card=>{const action=card.querySelector('[data-action]'),r=e=>{const x=e.getBoundingClientRect();return{x:x.left,y:x.top,w:x.width,h:x.height,right:x.right,bottom:x.bottom}},transparent=v=>v==='transparent'||/rgba\([^)]*,\s*0(?:\.0+)?\)$/.test(v),cr=r(card),ar=r(action),cs=getComputedStyle(action),text=(action.textContent||action.getAttribute('aria-label')||'').trim(),visibleLabel=!!text&&!transparent(cs.color),invisibleClickable=[...card.querySelectorAll('button,a,[role="button"]')].filter(el=>{const s=getComputedStyle(el),x=el.getBoundingClientRect();return !el.disabled&&x.width&&x.height&&(Number(s.opacity)<.1||(transparent(s.color)&&transparent(s.backgroundColor)))}).length;return{item:card.dataset.item,owned:card.dataset.owned==='true',price:card.dataset.price,opacity:Number(cs.opacity),text,visibleLabel,h:ar.h,inside:ar.x>=cr.x&&ar.y>=cr.y&&ar.right<=cr.right&&ar.bottom<=cr.bottom,invisibleClickable}}));
  await page.evaluate(()=>__TMB_A12__.openShop());await expect(page.locator('#fullscreenBtn')).toBeHidden();await expect(page.locator('#a12Shop [data-list="worlds"] article').first()).toBeHidden();expect(await ghostText(),'outfits ghost text').toEqual([]);for(const x of await actionFacts()){expect(x.opacity,`${x.item} action opacity`).toBeGreaterThanOrEqual(.9);expect(x.visibleLabel,`${x.item} visible action label`).toBe(true);expect(x.h,`${x.item} action height`).toBeGreaterThanOrEqual(44);expect(x.inside,`${x.item} action inside card`).toBe(true);expect(x.invisibleClickable,`${x.item} invisible clickable`).toBe(0)}await page.locator('#a12Shop [data-tab="worlds"]').click();await expect(page.locator('#a12Shop [data-list="outfits"] article').first()).toBeHidden();await expect(page.locator('#a12Shop [data-list="worlds"] article').first()).toBeVisible();expect(await ghostText(),'worlds ghost text').toEqual([]);for(const x of await actionFacts()){expect(x.opacity,`${x.item} action opacity`).toBeGreaterThanOrEqual(.9);expect(x.visibleLabel,`${x.item} visible action label`).toBe(true);expect(x.h,`${x.item} action height`).toBeGreaterThanOrEqual(44);expect(x.inside,`${x.item} action inside card`).toBe(true);expect(x.invisibleClickable,`${x.item} invisible clickable`).toBe(0)}await page.locator('#a12Shop [data-tab="outfits"]').click();const facts=await page.evaluate(()=>{const q=s=>document.querySelector(s),r=e=>{const x=e.getBoundingClientRect();return{x:x.left,y:x.top,w:x.width,h:x.height,right:x.right,bottom:x.bottom}},cards=[...document.querySelectorAll('#a12Shop [data-list="outfits"] article')],badges=[...document.querySelectorAll('#a12Shop [data-list="outfits"] [data-action]')],back=q('#a12Shop [data-shop-back]'),buy=q('#a12Shop [data-shop-buy]'),preview=r(q('#a12Preview'));return{docOverflow:document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight,cards:cards.map(x=>r(x)),badges:badges.map(x=>r(x)),back:back&&r(back),buy:buy&&r(buy),preview,shopH:r(q('#a12Shop')).h,products:r(q('#a12Products'))}});console.log('MOBILE_SHOP',JSON.stringify(facts));expect(facts.docOverflow).toBe(false);expect(facts.badges.length).toBe(facts.cards.length);expect(facts.back?.h||0).toBeGreaterThanOrEqual(44);expect(facts.buy?.h||0).toBeGreaterThanOrEqual(44);expect(facts.preview.h/facts.shopH).toBeGreaterThanOrEqual(.35);await page.locator('#a12Shop [data-shop-back]').click();await expect(page.locator('#fullscreenBtn')).toBeVisible();
});
