const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path');
let server,base;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://local').pathname.slice(1)||'index.html';fs.readFile(path.join(__dirname,'..',rel),(e,b)=>{res.statusCode=e?404:200;res.setHeader('Content-Type',rel.endsWith('.html')?'text/html':rel.endsWith('.png')?'image/png':'application/octet-stream');res.end(e?'missing':b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>{await new Promise(r=>server.close(r))});
for(const zero of [false,true])test(`ready after intro, first movement under 5 s; zero viewport=${zero}`,async({page})=>{
 const errors=[],external=[],consoleErrors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('request',r=>{if(new URL(r.url()).origin!==base)external.push(r.url())});
 await page.setViewportSize({width:390,height:844});await page.addInitScript(zero=>{if(zero){Object.defineProperty(window,'innerWidth',{configurable:true,value:0});Object.defineProperty(window,'innerHeight',{configurable:true,value:0})}window.readyEvents=[];window.bridge={EVENT_NAME:{PAUSE_STATE_CHANGED:'pause',AUDIO_STATE_CHANGED:'audio'},initialize:async()=>{},storage:{get:async()=>[''],set:async()=>{}},platform:{language:'en',isAudioEnabled:true,on(){},sendMessage(name){readyEvents.push({name,ms:performance.now(),intro:!!document.getElementById('introOverlay'),loading:!document.getElementById('bootOverlay').classList.contains('hidden')})}},advertisement:{isInterstitialSupported:false,isRewardedSupported:false,on(){}}}},zero);
 await page.goto(base+'/index.html#debug');await page.waitForFunction(()=>readyEvents.length===1);expect(await page.evaluate(()=>readyEvents[0])).toMatchObject({name:'game_ready',intro:false,loading:false});if(zero)await page.evaluate(()=>{Object.defineProperty(window,'innerWidth',{configurable:true,value:390});Object.defineProperty(window,'innerHeight',{configurable:true,value:844});dispatchEvent(new Event('resize'))});
 await page.locator('.characterChoice').first().click();await page.waitForTimeout(370);const x=await page.evaluate(()=>__tmb.player.x);await page.keyboard.down('ArrowRight');await page.waitForFunction(x=>__tmb.player.x>x+1,x);await page.keyboard.up('ArrowRight');const firstMovementMs=await page.evaluate(()=>performance.now());console.log('READINESS_METRIC='+JSON.stringify({zero,firstMovementMs,ready:await page.evaluate(()=>readyEvents[0])}));expect(firstMovementMs).toBeLessThan(5000);expect(await page.evaluate(()=>[document.getElementById('game').width,document.getElementById('game').height])).toEqual([390,844]);expect(errors).toEqual([]);expect(consoleErrors).toEqual([]);expect(external).toEqual([]);
});
test('real hidden iframe 0x0 recovers to 390x844 without page errors',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/index.html#debug');await page.evaluate(base=>{const f=document.createElement('iframe');f.id='zeroFrame';f.style.cssText='width:0;height:0;border:0';f.src=base+'/index.html#debug';document.body.appendChild(f)},base);const frame=page.frameLocator('#zeroFrame');await frame.locator('#characterSelect.show').waitFor();expect(await frame.locator('body').evaluate(()=>[innerWidth,innerHeight])).toEqual([0,0]);await page.locator('#zeroFrame').evaluate(f=>{f.style.width='390px';f.style.height='844px'});await expect.poll(()=>frame.locator('body').evaluate(()=>[innerWidth,innerHeight])).toEqual([390,844]);expect(await frame.locator('#game').evaluate(c=>[c.width,c.height])).toEqual([390,844]);expect(errors).toEqual([])});
