const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path');
const {load,source}=require('./phase3-verify.cjs');
let server,base;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://local').pathname.slice(1)||'index.html';fs.readFile(path.join(__dirname,'..',rel),(e,b)=>{res.statusCode=e?404:200;res.setHeader('Content-Type',rel.endsWith('.html')?'text/html':rel.endsWith('.mp3')?'audio/mpeg':'application/octet-stream');res.end(e?'missing':b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/index.html#debug`});
test.afterAll(async()=>{await new Promise(r=>server.close(r))});
async function boot(page){await page.goto(base);await page.locator('#characterSelect.show').waitFor();await page.locator('.characterChoice').first().click();await page.waitForFunction(()=>!__tmb.characterSelectOpen)}
test('diagnostic: real mute clicks, debounce and separate unmute',async({page})=>{await boot(page);await page.waitForFunction(()=>__tmb.audio.bgmStarted&&__tmb.audio.acState==='running');expect(await page.evaluate(()=>__tmb.audio.sourceConnected)).toBe(true);await page.locator('#muteBtn').click();expect(await page.evaluate(()=>__tmb.audio.outputMuted)).toBe(true);await page.locator('#muteBtn').evaluate(e=>e.click());expect(await page.evaluate(()=>__tmb.audio.outputMuted)).toBe(true);await page.waitForTimeout(270);await page.locator('#muteBtn').click();expect(await page.evaluate(()=>__tmb.audio.outputMuted)).toBe(false)});
test('active part 2 verified solver route to next sector part 1: 5/5',()=>{const bot=fs.readFileSync(path.join(__dirname,'parkour-bot.spec.cjs'),'utf8').split('const bot=String.raw`')[1].split('`;')[0],plan=JSON.parse(fs.readFileSync(path.join(__dirname,'parkour-plans.json'),'utf8')).find(r=>r.level===1&&r.part===2).plan,p=load(source('WORKTREE'));p('bgm.pause=()=>{}');p(bot);for(let run=0;run<5;run++){const r=JSON.parse(p(`JSON.stringify(parkourBot(1,2,60,false,48,${JSON.stringify(plan)}))`));expect(r.clear&&!r.dead&&r.used).toBe(true);expect(p('[currentLevel,currentPart].join(".")')).toBe('2.1');expect(p('deaths')).toBe(0)}});
test('L2 active P2 reported trap identity is jumpBait',async({page})=>{await boot(page);await page.evaluate(()=>__tmbSetProgress(2,2,0,0));await page.keyboard.press('k');await page.waitForFunction(()=>__tmb.dead);expect(await page.evaluate(()=>__tmb.debugDeath.trap)).toBe('jumpBait')});
