const {test,expect}=require('playwright/test');
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const {runBot}=require('./lib/bot-s-drive.cjs');
test.beforeEach(async({page})=>{const select=page.selectOption.bind(page);page.selectOption=(selector,values,options={})=>select(selector,values,{...options,force:true})});
const root=path.resolve(__dirname,'..');let server,origin;
test.use({hasTouch:true});
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=new URL(req.url,'http://x').pathname.slice(1)||'index.html';try{let b=fs.readFileSync(path.join(root,rel));if(rel==='js/a12-campaign.js')b=Buffer.from(b.toString().replace('if (DEBUG) {','if (DEBUG) { window.a5cProbe=code=>eval(code);'));res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':rel.endsWith('.png')?'image/png':'application/octet-stream');res.end(b)}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function open(page,debug=true){const errors=[];page.on('pageerror',e=>errors.push(e.stack||String(e)));await page.goto(`${origin}/index.html${debug?'#debug':''}`);if(debug)await page.waitForFunction(()=>window.a5cProbe&&window.__TMB_A12__,null,{timeout:10000}).catch(()=>{throw Error(errors.join('\n')||'campaign did not initialize')});}

test('B-L1 dictionary integrity',async({page})=>{await open(page);const d=await page.evaluate(()=>__TMB_A12__.i18n()),keys=Object.keys(d.en).sort();expect(Object.keys(d.tr).sort()).toEqual(keys);expect(Object.keys(d.ru).sort()).toEqual(keys);for(const lang of ['en','tr','ru'])for(const v of Object.values(d[lang]))expect(v).not.toMatch(/[?\uFFFD]/);expect(Object.values(d.tr).join('')).toMatch(/[çğıöşüÇĞİÖŞÜ]/);expect(Object.values(d.ru).join('')).toMatch(/[А-Яа-яЁё]/)});
test('B-L2 TR/RU canvas and DOM campaign surfaces have zero English residue',async({page})=>{test.setTimeout(120000);
  const ALLOW=['TRUST ME BRO','D01','D02','D03','D04','D05','D06','F01','F02','F03','F04','M01','M02','M03','M04','A01','A02','A03','A04'];
  await page.addInitScript(()=>{window.__a5cText=[];const raw=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){window.__a5cText.push(String(text));return raw.call(this,text,...args)}});await open(page);
  const scan=async(lang,surface)=>{const found=await page.evaluate(({lang,surface,ALLOW})=>{const d=__TMB_A12__.i18n(),texts=[...__a5cText];for(const e of document.querySelectorAll('body *')){const s=getComputedStyle(e);if(s.display!=='none'&&s.visibility!=='hidden'&&e.offsetParent!==null&&e.children.length===0&&e.textContent.trim())texts.push(e.textContent.trim())}const allowed=s=>ALLOW.some(a=>s===a||s.includes(a));const exact=new Set(Object.values(d.en).map(v=>v.replace('{price}','').trim()).filter(v=>v.length>2));const english=/\b(?:SHOP|OUTFITS|WORLDS|WALLET|RUNNER|RUN|LIVE|PREVIEW|LANGUAGE|GHOST|CHECKPOINT|FINISH|COMPLETE|EARNED|GOALS|FLOW|LOCAL|BEST|NEW|CLEAN|MASTERY|STYLE|RETRY|NEXT|SELECT|FREE|EXIT|SECTOR|SHIELD|INCIDENTS|PACKAGE|DELIVERED|RESTARTING|ROUTE|COURIER|NIGHT|HAZARD)\b/i;return texts.filter(s=>!allowed(s)&&(exact.has(s)||english.test(s))).map(text=>({lang,surface,text}))},{lang,surface,ALLOW});expect(found).toEqual([]);await page.evaluate(()=>{__a5cText.length=0})};
  for(const [i,lang] of ['tr','ru'].entries()){await page.selectOption('#a12Language',lang);if(i)await page.evaluate(()=>{const e=document.querySelector('#characterSelect');e.classList.add('show');e.setAttribute('aria-hidden','false')});await page.evaluate(()=>{__a5cText.length=0});await page.waitForTimeout(50);await scan(lang,'character+language+ghost');if(!i)await page.locator('.characterChoice:visible').first().click();else await page.evaluate(()=>{const e=document.querySelector('#characterSelect');e.classList.remove('show');e.setAttribute('aria-hidden','true')});await scan(lang,'HUD+finish gate');await page.evaluate(()=>__TMB_A12__.openShop());await scan(lang,'shop outfits');await page.locator('[data-tab="worlds"]').click();await scan(lang,'shop worlds');await page.evaluate(()=>{__TMB_A12__.closeShop();__TMB_A12__.startRoute('D01',true)});const bot=await runBot(page,'D01',{resume:true,live:true});expect(bot.finished).toBeTruthy();expect((await page.evaluate(()=>__TMB_A12__.analytics().events.some(e=>e.event==='checkpoint_reached')))).toBeTruthy();await scan(lang,'D01 checkpoint+result');await page.evaluate(()=>__TMB_A12__.startRoute('D06',true,true));await page.keyboard.down('ArrowRight');const died=await page.waitForFunction(()=>__TMB_A12__.analytics().events.some(e=>e.event==='chief_catch'),null,{timeout:5000}).then(()=>true).catch(()=>false);await page.keyboard.up('ArrowRight');console.log(`B-L2_REAL_INPUT_DEATH ${lang}=${died?'observed':'not-observed-5s'}`);await page.keyboard.press('r');await page.waitForFunction(()=>__TMB_A12__.analytics().events.some(e=>e.event==='retry'),null,{timeout:3000});await scan(lang,'real-input death+retry')}
});
test('B-L3 selection chain',async({page})=>{await page.addInitScript(()=>Object.defineProperty(navigator,'language',{value:'ru-RU',configurable:true}));await open(page);expect(await page.evaluate(()=>__TMB_A12__.profile().settings.language)).toBe('ru');await page.evaluate(()=>__TMB_A12__.setLanguage('tr'));await page.reload();await page.waitForFunction(()=>window.__TMB_A12__);expect(await page.evaluate(()=>__TMB_A12__.profile().settings.language)).toBe('tr');expect(await page.evaluate(()=>a5cProbe(`[languageFrom('de-DE'),languageFrom('tr'),languageFrom('ru-RU')]`))).toEqual(['en','tr','ru'])});
test('M-L4 language UI touch, reload and route persistence without profile loss',async({page})=>{await page.setViewportSize({width:390,height:844});await open(page);const before=await page.evaluate(()=>__TMB_A12__.profile());await page.locator('#a12Language').tap();await page.selectOption('#a12Language','ru');await expect(page.locator('#a12LanguageWrap span')).toHaveText('ЯЗЫК');await page.locator('.characterChoice:visible').first().tap();await page.evaluate(()=>__TMB_A12__.startRoute('D02',true));expect(await page.locator('#a12Language').inputValue()).toBe('ru');await page.reload();await page.waitForFunction(()=>window.__TMB_A12__);const after=await page.evaluate(()=>__TMB_A12__.profile());expect(after.settings.language).toBe('ru');for(const k of ['walletBalance','progressByRoute','equippedOutfitByRunner','ownedOutfitSetIds','ownedWorldIds'])expect(after[k]).toEqual(before[k])});
test('M-L5 desktop text fits',async({page})=>{await page.setViewportSize({width:1080,height:540});await open(page);await page.locator('.characterChoice:visible').first().click();await page.evaluate(()=>__TMB_A12__.openShop());for(const lang of ['en','tr','ru']){await page.evaluate(lang=>__TMB_A12__.setLanguage(lang),lang);const overflow=await page.locator('#a12Shop button,#a12Shop h2,#a12Shop h3').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+1).map(e=>e.textContent));expect(overflow).toEqual([])}});
test('Y-G1 logo family and manifest hashes',()=>{const files={'trust-me-bro-logo.png':[1024,384],'trust-me-bro-icon-512.png':[512,512],'trust-me-bro-icon-48.png':[48,48],'trust-me-bro-store-cover.png':[1200,630]},manifest=fs.readFileSync(path.join(root,'ASSET-MANIFEST.md'),'utf8');for(const [name,[w,h]] of Object.entries(files)){const b=fs.readFileSync(path.join(root,'sprites/a5/brand',name));expect(b.readUInt32BE(16)).toBe(w);expect(b.readUInt32BE(20)).toBe(h);expect(manifest).toContain(crypto.createHash('sha256').update(b).digest('hex'))}});
test('B-A1 full Bot S, commerce, language setting and silent getter',async({page})=>{test.setTimeout(120000);const requests=[];page.on('request',r=>requests.push(r.url()));await open(page);await page.locator('.characterChoice:visible').first().click();await runBot(page,'D01',{resume:true,live:true});await page.evaluate(()=>__TMB_A12__.openShop());await page.locator('[data-list="outfits"] [data-item="dockCrew"] [data-action]').click();await page.locator('[data-list="outfits"] [data-item="default"] [data-action]').click();await page.locator('#a12Shop [data-close]').click();await page.evaluate(()=>__TMB_A12__.setLanguage('tr'));const before=await page.evaluate(()=>__TMB_A12__.analytics());await page.evaluate(()=>{for(let i=0;i<100;i++)__TMB_A12__.getState()});const after=await page.evaluate(()=>__TMB_A12__.analytics());expect(after.events.length).toBe(before.events.length);expect(after.capability).toBe('LOCAL_ONLY');expect(after.remote).toBe('NOT_CONFIGURED');expect(after.events.filter(e=>e.event==='ghost_toggle')).toHaveLength(0);const names=after.events.map(e=>e.event),ordered=['run_start','run_reward_banked','purchase_success','outfit_worn','outfit_worn','language_change'];let at=-1;for(const name of ordered){at=names.indexOf(name,at+1);expect(at,`${name} event order`).toBeGreaterThanOrEqual(0)}for(const e of after.events)expect(Object.keys(e)).toEqual(expect.arrayContaining(['event','gameTimeMs','wallTime','sessionId','runId','routeId','build','params']));expect(requests.filter(u=>!u.startsWith(origin))).toEqual([])});
test('B-C1 18 route OPENING frames and shop reward collision matrix',async({page})=>{test.setTimeout(120000);await page.addInitScript(()=>{window.__a5cFill=[];const raw=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,x,y,...rest){const m=this.measureText(String(text));window.__a5cFill.push({text:String(text),x,y,w:m.width,font:this.font,align:this.textAlign,canvas:this.canvas});return raw.call(this,text,x,y,...rest)}});await open(page);await page.locator('.characterChoice:visible').first().click();const routes=['D01','D02','D03','D04','D05','D06','F01','F02','F03','F04','M01','M02','M03','M04','A01','A02','A03','A04'];for(const id of routes){await page.evaluate(id=>{__a5cFill.length=0;a5cProbe(`profile.ownedWorldIds=['dock31','frozen','magma','aftermath'];for(const k of Object.keys(ROUTES))profile.progressByRoute[k]={completed:true}`);__TMB_A12__.renderWorldOnRoute(id[0]==='F'?'frozen':id[0]==='M'?'magma':id[0]==='A'?'aftermath':'dock31',id)},id);await page.waitForTimeout(25);expect(await page.evaluate(()=>__a5cFill.filter(v=>v.text==='OPENING').length),id).toBe(0)}for(const [width,height] of [[1080,540],[844,390],[390,844]]){await page.setViewportSize({width,height});await page.evaluate(()=>{__TMB_A12__.renderWorldOnRoute('dock31','D01');__TMB_A12__.finish();__TMB_A12__.openShop()});const title=await page.locator('#a12Products h2').boundingBox();const reward=await page.evaluate(()=>{const c=document.querySelector('#game'),r=c.getBoundingClientRect(),v=[...__a5cFill].reverse().find(v=>/\+\d+/.test(v.text));if(!v)return null;const sx=r.width/c.width,sy=r.height/c.height;return{x:r.x+(v.x-v.w/2)*sx,y:r.y+(v.y-24)*sy,width:v.w*sx,height:30*sy,text:v.text}});if(reward)expect(Math.max(0,Math.min(title.x+title.width,reward.x+reward.width)-Math.max(title.x,reward.x))*Math.max(0,Math.min(title.y+title.height,reward.y+reward.height)-Math.max(title.y,reward.y))).toBe(0);await page.screenshot({path:path.join(root,'03-test/a5c1-evidence',`bc1-after-${width}x${height}.png`)})}});
test('Y-D1 no new production globals',async({page})=>{await open(page,false);const forbidden=['analytics','tmbPlatformLanguage','a5cProbe'];expect(await page.evaluate(names=>names.filter(n=>Object.prototype.hasOwnProperty.call(window,n)),forbidden)).toEqual([]);expect(await page.evaluate(()=>Object.keys(window).filter(k=>k.startsWith('__tmb')))).toEqual([])});
