const {test,expect}=require('playwright/test');
const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto'),cp=require('child_process');
const root=path.resolve(__dirname,'..'),evidence=path.join(__dirname,'.a5c-music-pcm');let server,origin;
const worlds=['dock31','frozen','magma','aftermath'];
test.describe.configure({timeout:180000});
test.beforeAll(async()=>{fs.mkdirSync(evidence,{recursive:true});server=http.createServer((req,res)=>{const u=new URL(req.url,'http://x');if(req.method==='POST'&&u.pathname.startsWith('/__pcm/')){const out=path.join(evidence,path.basename(u.pathname)),chunks=[];req.on('data',x=>chunks.push(x));req.on('end',()=>{fs.writeFileSync(out,Buffer.concat(chunks));res.end('ok')});return}const rel=u.pathname.slice(1)||'index.html';try{res.end(fs.readFileSync(path.join(root,rel)))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function decodeToWav(page,name,url,gain=1){return page.evaluate(async({name,url,gain})=>{const ctx=new AudioContext(),ab=await (await fetch(url)).arrayBuffer(),b=await ctx.decodeAudioData(ab),n=b.length,ch=b.numberOfChannels,bytes=44+n*4,buf=new ArrayBuffer(bytes),v=new DataView(buf);let o=0;const s=x=>{for(const c of x)v.setUint8(o++,c.charCodeAt(0))},u=x=>{v.setUint32(o,x,true);o+=4},h=x=>{v.setUint16(o,x,true);o+=2};s('RIFF');u(bytes-8);s('WAVEfmt ');u(16);h(3);h(1);u(b.sampleRate);u(b.sampleRate*4);h(4);h(32);s('data');u(n*4);const cs=Array.from({length:ch},(_,i)=>b.getChannelData(i));for(let i=0;i<n;i++){let z=0;for(const c of cs)z+=c[i];v.setFloat32(o,gain*z/ch,true);o+=4}await fetch('/__pcm/'+name,{method:'POST',body:buf});await ctx.close();return{samples:n,rate:b.sampleRate,duration:b.duration}},{name,url,gain})}
function py(script,args,{allowFail=false}={}){const r=cp.spawnSync('python',[script,...args],{cwd:root,encoding:'utf8'});if(!allowFail&&r.status)throw Error(r.stdout+r.stderr);return{status:r.status,json:JSON.parse(r.stdout)}}
test('B-M2 browser-decoded loops have click-free seams',async({page})=>{await page.goto(origin);const manifest=fs.readFileSync(path.join(root,'ASSET-MANIFEST.md'),'utf8'),rows={},meta={};for(const n of ['menu',...worlds]){const row=manifest.split(/\r?\n/).find(x=>x.includes(`audio/music/${n}.ogg`))||'',values=row.match(/\|\s*([0-9.]+) s\s*\|\s*([0-9.]+) s\s*\|/);expect(values).toBeTruthy();const P=Number(values[1]),L=Number(values[2]);meta[n]={P,L};await decodeToWav(page,n+'.wav',`/audio/music/${n}.ogg`);const rel=path.relative(root,path.join(evidence,n+'.wav')),ok=py('tools/a5/music_loop_check.py',[rel,'--p',String(P),'--l',String(L)]);rows[n]=ok.json[n];console.log(`B-M2 raw ${n} seam=${rows[n].value}`);expect(ok.status).toBe(0);expect(rows[n].pass).toBeTruthy()}const magma=path.relative(root,path.join(evidence,'magma.wav')),bad=py('tools/a5/music_loop_check.py',[magma,'--p',String(meta.magma.P),'--l',String(meta.magma.L),'--trim-ms','37'],{allowFail:true});console.log(`B-M2 browser=${JSON.stringify(rows)} NEG trim37=${JSON.stringify(bad.json.magma)} RED`);expect(bad.status).not.toBe(0);expect(bad.json.magma.pass).toBeFalsy()});
test('Y-M8 manifest hashes, durations, sizes and mutation negative',async()=>{const manifest=fs.readFileSync(path.join(root,'ASSET-MANIFEST.md'),'utf8'),sizes={},durations={},checks=[];for(const n of ['menu',...worlds]){const p=path.join(root,'audio/music',n+'.ogg'),b=fs.readFileSync(p),sha=crypto.createHash('sha256').update(b).digest('hex'),probe=cp.spawnSync('ffprobe',['-v','error','-show_entries','format=duration','-of','default=nw=1:nk=1',p],{encoding:'utf8'}),duration=Number(probe.stdout),row=manifest.split(/\r?\n/).find(x=>x.includes(`audio/music/${n}.ogg`))||'',values=row.match(/\|\s*([0-9.]+) s\s*\|\s*([0-9.]+) s\s*\|/),P=Number(values?.[1]),L=Number(values?.[2]);sizes[n]=b.length;durations[n]=duration;checks.push({n,b,sha,duration,row,values,P,L})}const total=Object.values(sizes).reduce((a,b)=>a+b,0),b=fs.readFileSync(path.join(root,'audio/music/magma.ogg')),changed=Buffer.from(b);changed[0]^=1;const red=!manifest.includes(crypto.createHash('sha256').update(changed).digest('hex'));console.log(`Y-M8 sizes=${JSON.stringify(sizes)} durations=${JSON.stringify(durations)} total=${total} NEG byteMutation=${Number(red)} RED`);for(const {b,sha,duration,row,values,P,L} of checks){expect(values).toBeTruthy();expect(Number.isFinite(duration)).toBeTruthy();expect(Math.abs(duration-(L+2*P))).toBeLessThanOrEqual(.05);expect(b.length).toBeLessThanOrEqual(768*1024);expect(row).toContain(sha);expect(row).toContain('0.384 s');expect(row).toContain(`${L} s`)}expect(total).toBeLessThan(3000000);expect(manifest).toContain('CC0 1.0');expect(manifest).toContain('opengameart.org/content/platformer-chiptunes');expect(manifest).toContain('YÖNETİCİ MÜZİK SÜRÜMÜ');expect(manifest).toContain('kampanya ve menüde kullanılmaz');expect(red).toBeTruthy()});

async function waitMusic(page,source){await page.waitForFunction(s=>{const a=window.__tmbAudio?.state();return a&&a.clock>0&&a.music.source===s&&a.music.sources===1},source);await page.waitForFunction(()=>window.__tmbAudio.sample('music').db>-40)}
async function neutralUnlock(page){await page.mouse.click(20,20);await waitMusic(page,'menu')}
async function chooseRunner(page){await neutralUnlock(page);await page.locator('.characterChoice:visible').first().click();await waitMusic(page,'dock31')}
async function ownWorld(page,name){await page.evaluate(async name=>{await __TMB_A12__.setWallet(2000);await __TMB_A12__.purchaseWorld(name);if(name==='magma'||name==='aftermath')await __TMB_A12__.purchaseWorld(name)},name)}
async function route(page,id,source){await page.evaluate(x=>window.__TMB_A12__.startRoute(x),id);await waitMusic(page,source);return page.evaluate(()=>window.__tmbAudio.state())}
test('B-M3 live UI selects menu and world music without overlap or same-world restart',async({page})=>{await page.goto(origin+'/#debug');await chooseRunner(page);const rows=[];for(const [id,name] of [['D01','dock31'],['F01','frozen'],['M01','magma'],['A01','aftermath']]){if(name!=='dock31')await ownWorld(page,name);const s=id==='D01'?await page.evaluate(()=>window.__tmbAudio.state()):await route(page,id,name),html=await page.evaluate(()=>[...document.querySelectorAll('audio')].filter(x=>!x.paused).length);rows.push({id,source:s.music.source,db:(await page.evaluate(()=>window.__tmbAudio.sample('music').db)),sources:s.musicSources,html});expect(s.music.source).toBe(name);expect(s.musicSources).toBeLessThanOrEqual(1);expect(html).toBe(0)}await page.evaluate(()=>window.__TMB_A12__.purchaseWorld('dock31'));await route(page,'D01','dock31');await page.waitForTimeout(120);const before=await page.evaluate(()=>window.__tmbAudio.state().music.offset);await page.evaluate(()=>window.__TMB_A12__.startRoute('D02'));const after=await page.evaluate(()=>window.__tmbAudio.state().music.offset);expect(after).toBeGreaterThanOrEqual(before);await ownWorld(page,'frozen');await page.evaluate(()=>window.__tmbAudio.mutate('singleTrack'));await page.evaluate(()=>window.__TMB_A12__.startRoute('F01'));await page.waitForFunction(()=>window.__tmbAudio.state().music.source==='dock31');const red=await page.evaluate(()=>window.__tmbAudio.state().music.source!=='frozen');expect(red).toBeTruthy();console.log(`B-M3 rows=${JSON.stringify(rows)} sameWorld=${before.toFixed(3)}->${after.toFixed(3)} prereq=frozen:1,magma:2,aftermath:2 NEG singleTrack=${Number(red)} RED`)});
test('B-M4 music files load only on first need',async({browser})=>{const context=await browser.newContext(),page=await context.newPage(),req=[],bytes={};page.on('request',r=>{if(/(?:audio\/music\/|soundtrack\.mp3)/.test(r.url()))req.push(new URL(r.url()).pathname)});page.on('response',async r=>{if(/audio\/music\//.test(r.url()))try{bytes[new URL(r.url()).pathname]=(await r.body()).length}catch{}});await page.goto(origin);await page.waitForTimeout(3000);expect(req.length).toBe(0);await page.goto('about:blank');await page.goto(origin+'/#debug');await page.waitForFunction(()=>window.__TMB_A12__&&window.__tmbAudio);req.length=0;await Promise.all([page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/audio/music/menu.ogg')),page.mouse.click(20,20)]);await waitMusic(page,'menu');const afterMenu=req.slice();await page.waitForFunction(()=>window.__TMB_A12__&&window.__tmbAudio);await page.evaluate(()=>window.__TMB_A12__.openShop());await page.waitForFunction(()=>window.__TMB_A12__&&window.__tmbAudio);await page.evaluate(()=>window.__TMB_A12__.closeShop());expect(req).toEqual(afterMenu);await page.waitForFunction(()=>window.__TMB_A12__&&window.__tmbAudio);await ownWorld(page,'frozen');await page.waitForFunction(()=>window.__TMB_A12__&&window.__tmbAudio);await Promise.all([page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/audio/music/frozen.ogg')),page.evaluate(()=>window.__TMB_A12__.startRoute('F01'))]);expect(req.filter(x=>x.endsWith('.ogg'))).toEqual(['/audio/music/menu.ogg','/audio/music/frozen.ogg']);await context.close();const neg=await browser.newContext(),p=await neg.newPage(),eager=[];p.on('request',r=>{if(/audio\/music\/.*\.ogg/.test(r.url()))eager.push(r.url())});await p.goto('about:blank');await p.goto(origin+'/#debug');await p.waitForFunction(()=>window.__TMB_A12__&&window.__tmbAudio);await p.evaluate(()=>window.__tmbAudio.mutate('eagerMusic'));await p.mouse.click(20,20);await p.waitForFunction(()=>performance.getEntriesByType('resource').filter(x=>x.name.includes('/audio/music/')).length>=2);expect(eager.length).toBeGreaterThanOrEqual(2);await neg.close();console.log(`B-M4 requests=${JSON.stringify(req)} bytes=${JSON.stringify(bytes)} coldBytes=0 soundtrack=0 shopNew=0 dock31=0 NEG eager=${eager.length} RED`)});
test('B-M7 pause preserves offset and four ad branches recover music',async({page})=>{await page.goto(origin+'/#debug');await chooseRunner(page);await ownWorld(page,'frozen');await route(page,'F01','frozen');const a=await page.evaluate(()=>{window.__tmbLifecycle.pause();return window.__tmbAudio.state().music.offset});await page.waitForTimeout(2000);const hidden=await page.evaluate(()=>window.__tmbAudio.state().music.offset);await page.evaluate(()=>window.__tmbLifecycle.resume());await waitMusic(page,'frozen');expect(Math.abs(hidden-a)).toBeLessThanOrEqual(.2);const ads=[];for(const mode of ['success','missing','error','timeout']){await page.evaluate(m=>window.__tmbLifecycle.ad(m),mode);await waitMusic(page,'frozen');ads.push((await page.evaluate(()=>window.__tmbAudio.state())).music.sources)}await page.evaluate(()=>window.__tmbAudio.mutate('ignoreVisibility'));const db=await page.evaluate(()=>window.__tmbAudio.sample('music').db);expect(db).toBeGreaterThan(-60);console.log(`B-M7 offset=${a.toFixed(3)}->${hidden.toFixed(3)} delta=${Math.abs(hidden-a).toFixed(3)} ads=${JSON.stringify(ads)} NEG ignoreVisibilityDb=${db.toFixed(3)} RED`)});
test('Y-M9 playback flow is same-origin only',async({page})=>{const external=[];page.on('request',r=>{if(new URL(r.url()).origin!==origin)external.push(r.url())});await page.goto(origin+'/#debug');await chooseRunner(page);for(const [id,name] of [['F01','frozen'],['M01','magma'],['A01','aftermath']]){await ownWorld(page,name);await route(page,id,name)}expect(external.length).toBe(0);const red=await page.evaluate(()=>{const a=document.createElement('audio');a.src='https://example.invalid/x.ogg';document.body.appendChild(a);a.load();return Number(new URL(a.src).origin!==location.origin)});expect(red).toBe(1);console.log(`Y-M9 external=${external.length} requestsSameOrigin=1 worlds=4 NEG injected=${red} RED`)});

test('B-M6 collapse warning clears each real world track by six dB',async({page})=>{
  const meter=async(ms=220)=>page.evaluate(async ms=>{let music=-Infinity,sfx=-Infinity;const end=performance.now()+ms;while(performance.now()<end){music=Math.max(music,__tmbAudio.sample('music').db);sfx=Math.max(sfx,__tmbAudio.sample('sfx').db);await new Promise(r=>setTimeout(r,5))}return{music,sfx,delta:sfx-music}},ms);
  await page.goto(origin+'/#debug');await chooseRunner(page);
  const rows=[];
  for(const [id,name] of [['D01','dock31'],['F01','frozen'],['M01','magma'],['A01','aftermath']]){
    await ownWorld(page,name);await route(page,id,name);
    const clock=await page.evaluate(()=>__tmbAudio.state().clock);expect(clock).toBeGreaterThan(0);
    const positive=await Promise.all([page.evaluate(()=>__tmbAudio.play('collapse-warning')),meter()]).then(x=>x[1]);
    expect(positive.delta,id).toBeGreaterThanOrEqual(6);rows.push({id,name,clock,...positive});
    console.log(`B-M6 ${id} delta=${positive.delta.toFixed(3)}dB music=${positive.music.toFixed(3)} sfx=${positive.sfx.toFixed(3)} clock=${clock.toFixed(3)}`);
    await page.waitForTimeout(500);
  }
  await page.evaluate(()=>__tmbAudio.mutate('warningGain',true));
  const negative=await Promise.all([page.evaluate(()=>__tmbAudio.play('collapse-warning')),meter()]).then(x=>x[1]);
  expect(negative.delta).toBeLessThan(6);
  console.log(`B-M6 NEG warningGain delta=${negative.delta.toFixed(3)}dB RED rows=${rows.length}`);
});

test('Y-M5 cold load avoids legacy soundtrack requests',async({browser})=>{
  const baselineRoot=path.resolve(root,'..','01-tasarim','a5c2b-baseline-38187c2','02-kod');
  const serve=dir=>new Promise(resolve=>{const s=http.createServer((req,res)=>{const rel=new URL(req.url,'http://x').pathname.slice(1)||'index.html';try{const b=fs.readFileSync(path.join(dir,rel));const pathname=new URL(req.url,'http://x').pathname;res.setHeader('Content-Type',pathname.endsWith('.js')?'text/javascript':pathname.endsWith('.html')?'text/html':pathname.endsWith('.ogg')?'audio/ogg':pathname.endsWith('.mp3')?'audio/mpeg':'application/octet-stream');res.end(b)}catch{res.statusCode=404;res.end()}});s.listen(0,'127.0.0.1',()=>resolve(s))});
  const baseServer=await serve(baselineRoot),newServer=await serve(root),baseOrigin=`http://127.0.0.1:${baseServer.address().port}`,newOrigin=`http://127.0.0.1:${newServer.address().port}`;
  const stub=()=>{const noop=()=>{},asyncNoop=async()=>{},platform={language:'en',isAudioEnabled:true,on:noop,sendMessage:(name)=>{if(name==='game_ready'&&window.__gameReadyAt==null)window.__gameReadyAt=performance.now()}},storage={get:async()=>[''],set:asyncNoop},advertisement={on:noop,showInterstitial:noop,showRewarded:noop,isInterstitialSupported:false,isRewardedSupported:false};window.__gameReadyAt=null;window.bridge={initialize:asyncNoop,platform,storage,advertisement,EVENT_NAME:{PAUSE_STATE_CHANGED:'pause',AUDIO_STATE_CHANGED:'audio',INTERSTITIAL_STATE_CHANGED:'interstitial',REWARDED_STATE_CHANGED:'rewarded'}}};
  const measure=async(url,{injectLegacy=false}={})=>{const context=await browser.newContext();const page=await context.newPage();let beforeReady=true,soundtrack=0,audio=0;const bodies=[];page.on('request',r=>{const p=new URL(r.url()).pathname;if(p.endsWith('/soundtrack.mp3'))soundtrack++;if(p.includes('/audio/'))audio++});page.on('response',r=>{if(beforeReady)bodies.push(r.body().then(b=>b.length).catch(()=>0))});await page.addInitScript(stub);if(injectLegacy)await page.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{const a=document.createElement('audio');a.preload='auto';a.src='soundtrack.mp3';document.body.appendChild(a);a.load()},{once:true}));await page.goto(url+'/index.html');await page.waitForFunction(()=>window.__gameReadyAt!=null);beforeReady=false;const ready=await page.evaluate(()=>window.__gameReadyAt),bytes=(await Promise.all(bodies)).reduce((a,b)=>a+b,0);await page.waitForTimeout(3000);await context.close();return{soundtrack,audio,ms:ready,bytes}};
  try{
    const baseline=[],current=[];for(let i=0;i<5;i++)baseline.push(await measure(baseOrigin));for(let i=0;i<5;i++)current.push(await measure(newOrigin));
    const median=a=>a.map(x=>x).sort((x,y)=>x-y)[Math.floor(a.length/2)],medians={baseline:{ms:median(baseline.map(x=>x.ms)),bytes:median(baseline.map(x=>x.bytes))},new:{ms:median(current.map(x=>x.ms)),bytes:median(current.map(x=>x.bytes))}};
    console.log(`Y-M5 raw baseline=${JSON.stringify(baseline)} new=${JSON.stringify(current)} medians=${JSON.stringify(medians)}`);
    expect(baseline.every(x=>x.soundtrack>=1)).toBeTruthy();expect(current.every(x=>x.soundtrack===0)).toBeTruthy();expect(current.every(x=>x.audio===0)).toBeTruthy();
    const negative=await measure(newOrigin,{injectLegacy:true});console.log(`Y-M5 NEG preloadAuto=${JSON.stringify(negative)} RED`);expect(negative.soundtrack).toBeGreaterThanOrEqual(1);
  }finally{await Promise.all([new Promise(r=>baseServer.close(r)),new Promise(r=>newServer.close(r))])}
});
