"use strict";
const {test,expect}=require("playwright/test");
const http=require("node:http"),fs=require("node:fs"),path=require("node:path");
const root=path.resolve(__dirname,"..");
const globals=["__GAME_DEBUG__","__tmb","__tmbContinue","__tmbOutOfLives","__tmbPause","__tmbSetProgress","__tmbGateTestSetup","__tmbGateTestStep","__tmbGateTestReach","__tmbExitTestSetup","__tmbExitTestRuntime","__tmbExitTestAfterCrumble","__tmbExitTestStabilize","__tmbExitTestStopped","__exitProbe","__tmbParkour","__tmbWarningDraw"];
let server,origin;
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=new URL(req.url,"http://x").pathname.slice(1)||"index.html";fs.readFile(path.join(root,rel),(e,b)=>{res.statusCode=e?404:200;if(e)return res.end("missing");if(rel==="index.html")b=Buffer.from(b.toString().replace(/\}\)\(\);\s*<\/script>/,`window.e2Run=(level,part)=>{if(rafId)cancelAnimationFrame(rafId);rafId=0;loopRunning=false;systemPaused=false;currentLevel=level;currentPart=part;dead=won=false;deaths=partDeaths=0;resetScene(false);spawnGrace=0;let finishTick=null;for(let tick=0;tick<900;tick++){keys.right=true;keys.left=false;keys.jump=tick%90===30;update(1/120);if((currentLevel!==level||currentPart!==part)&&finishTick===null)finishTick=tick;if(dead)break}return{deaths,dead,finishTick,currentLevel,currentPart};};window.e4State=()=>({validation:Array.isArray(VALIDATION_REPORT),level:currentLevel,part:currentPart});\n})();\n</script>`));res.end(b)})});await new Promise(r=>server.listen(0,"127.0.0.1",r));origin=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>{if(server)await new Promise(r=>server.close(r))});
async function waitBoot(page){await page.waitForFunction(()=>document.querySelector("#bootOverlay")?.classList.contains("hidden"));}
for(const viewport of [{width:960,height:540},{width:540,height:960}])test(`E1 debug globals ${viewport.width}x${viewport.height}`,async({page})=>{await page.setViewportSize(viewport);await page.goto(origin+"/index.html");await waitBoot(page);const off=await page.evaluate(names=>({types:Object.fromEntries(names.map(n=>[n,typeof window[n]])),keys:Object.keys(window).filter(k=>k.startsWith("__")&&names.includes(k))}),globals);expect(off.keys,JSON.stringify(off)).toEqual([]);expect(Object.values(off.types).every(x=>x==="undefined"),JSON.stringify(off)).toBe(true);await page.goto(origin+"/index.html?debug=1#debug");await waitBoot(page);const on=await page.evaluate(names=>Object.fromEntries(names.filter(n=>n!=="__exitProbe").map(n=>[n,typeof window[n]])),globals);expect(Object.values(on).every(x=>x!=="undefined"),JSON.stringify(on)).toBe(true)});
test("E2 debug hash preserves three deterministic keyboard plans",async({browser})=>{const rows=[];for(const [level,part] of [[1,1],[13,1],[31,2]])for(const hash of ["", "debug"]){const page=await browser.newPage();await page.goto(`${origin}/index.html#s${level}p${part}${hash}`);const result=await page.evaluate(([l,p])=>e2Run(l,p),[level,part]);rows.push({level,part,hash,result});await page.close()}for(const [level,part] of [[1,1],[13,1],[31,2]]){const a=rows.find(x=>x.level===level&&x.part===part&&!x.hash).result,b=rows.find(x=>x.level===level&&x.part===part&&x.hash).result;expect(b).toEqual(a)}});
test("E4 legacy tool hashes still execute",async({page})=>{for(const hash of ["validate","geodump","geodumpall","padstat","voiddump3p4"]){const response=await page.goto(`${origin}/index.html?tool=${hash}#${hash}`);expect(response.ok(),hash).toBe(true);expect(await page.locator("#game").isVisible(),hash).toBe(true)}});
