"use strict";
const {test,expect}=require('playwright/test');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');let server,origin;
const EVENTS=['game_ready','first_input','session_end','level_start','movement_used','deception_triggered','telegraph_exposed','player_fail','retry','checkpoint','level_complete','rewarded_offer','rewarded_start','rewarded_complete','reward_granted','interstitial_show','interstitial_return','app_hidden','build_error','run_complete'];
test.beforeAll(async()=>{server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/, '')||'index.html';fs.readFile(path.join(root,rel),(e,b)=>{if(e){res.statusCode=404;return res.end('missing')}if(rel==='index.html')b=Buffer.from(b.toString().replace(/\}\)\(\);\s*<\/script><\/body><\/html>\s*$/,`window.__profileInstall=()=>{const updateTimes=[],drawTimes=[];let emits=0,frames=0;const oldUpdate=update,oldDraw=draw,oldEmit=emitGame;update=function(...a){const s=performance.now();try{return oldUpdate.apply(this,a)}finally{updateTimes.push(performance.now()-s)}};draw=function(...a){const s=performance.now();try{return oldDraw.apply(this,a)}finally{drawTimes.push(performance.now()-s);frames++}};emitGame=function(...a){emits++;return oldEmit.apply(this,a)};return()=>{const stats=a=>{const b=[...a].sort((x,y)=>x-y),sum=a.reduce((x,y)=>x+y,0);return{n:a.length,avg_ms:sum/a.length,p95_ms:b[Math.min(b.length-1,Math.floor(b.length*.95))]}};return{frames,emit_count:emits,update:stats(updateTimes),draw:stats(drawTimes)}}};\n})();\n</script></body></html>`));res.end(b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`});
test.afterAll(async()=>{await new Promise(r=>server.close(r))});
async function ready(page){await page.goto(origin+'/index.html#debug');await page.waitForFunction(()=>window.__tmb?.platform.initialized);if(await page.locator('#characterSelect.show').isVisible())await page.locator('.characterChoice').first().click();await page.waitForFunction(()=>!__tmb.characterSelectOpen)}
async function profile(page,suppressed){await ready(page);return page.evaluate(async({suppressed,events})=>{if(suppressed)for(const e of events)__GAME_DEBUG__._suppress(e);const finish=__profileInstall(),start=performance.now();await new Promise(r=>setTimeout(r,10000));const elapsed=performance.now()-start,result=finish();return{suppressed,elapsed_ms:elapsed,...result,emit_per_s:result.emit_count/(elapsed/1000),events:__GAME_DEBUG__.getTelemetry().reduce((o,e)=>(o[e.event]=(o[e.event]||0)+1,o),{})}}, {suppressed,events:EVENTS})}
test('10 second update draw telemetry profile',async({page})=>{test.setTimeout(60000);const current=await profile(page,false),off=await profile(page,true),out={current,telemetry_suppressed:off};fs.writeFileSync(path.join(__dirname,'vc7-tur2','telemetry-profile.json'),JSON.stringify(out,null,2));expect(current.frames).toBeGreaterThan(300);expect(off.frames).toBeGreaterThan(300)});
