const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path');

// KABUL (ilk koşumdan önce sabit): CZ-1 container-1 mesafe 0,8,...96: 13/13,
// tepede onGround, ölüm 0, H60 tutunma->tepe 0.20±0.04 gameClock. CZ-2 aynı
// tarama CDP çoklu temasla 390x844 ve 844x390: 13/13. CZ-3 130/160'ta
// bölge başlangıcı 0, yüz dibinde ikinci basış 1. CZ-4 150'den kalkış ve <=40
// havada ikinci basış iki kanalda tutunur. CZ-5 d01-high-entry H80 iki kanalda
// 0.53±0.04. CZ-6 seed 20261002, her işaretli yüzde tek basış, P1/0 ölüm/0
// şef/<=120 s. CZ-7 şef yalnız ölçülür. CZ-8 mevcut negatifler değişmez.
// CZ-9 yalnız hedef hunklar ve belirtilen kapılar. CZ-10 üç kare ve piksel assert.

const root=path.resolve(__dirname,'..');
test.setTimeout(130000);
const evidence='E:/oyunlar/TrustMeBro/01-tasarim/vector-parkur/czone';
let server,base;
test.beforeAll(async()=>{fs.mkdirSync(evidence,{recursive:true});server=http.createServer((req,res)=>{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\/+/, '')||'index.html';fs.readFile(path.join(root,rel),(e,b)=>{if(e){res.statusCode=404;return res.end('missing')}res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':'application/octet-stream');res.end(b)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/index.html#debug`});
test.afterAll(async()=>new Promise(r=>server.close(r)));

async function open(page){await page.goto(base);await page.waitForFunction(()=>window.__TMB_A12__);const c=page.locator('.characterChoice:visible').first();if(await c.count())await c.click();await page.evaluate(()=>{__tmbParkour.manual();__TMB_A12__.startRoute('D01')});await page.waitForTimeout(550)}
async function step(page,n=1){return page.evaluate(n=>{let s;for(let i=0;i<n;i++){__tmbCampaignStep(1/60);s=__TMB_A12__.getState()}return s},n)}
async function place(page,x,y=407){await page.evaluate(({x,y})=>__TMB_A12__.placePlayer(x,y),{x,y});await step(page,2)}
async function keyboardStart(page){await page.keyboard.down('ArrowRight');await page.keyboard.down('ArrowUp');await page.waitForFunction(()=>__TMB_A12__.getState().input.right&&__TMB_A12__.getState().input.jump)}
async function touchStart(page,session){const joy=await page.locator('#joystick').boundingBox(),jump=await page.locator('#jumpWrap button').boundingBox();expect(joy).toBeTruthy();expect(jump).toBeTruthy();const j={x:joy.x+joy.width*.88,y:joy.y+joy.height/2,id:1,radiusX:2,radiusY:2,force:1},b={x:jump.x+jump.width/2,y:jump.y+jump.height/2,id:2,radiusX:2,radiusY:2,force:1};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[j]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[j]});await page.waitForFunction(()=>__TMB_A12__.getState().input.joystick>.12);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[j,b]});await page.waitForFunction(()=>{const s=__TMB_A12__.getState();return s.input.jump||s.edgeClimb});return {j,b}}
async function touchEnd(page,session){await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>Math.abs(__TMB_A12__.getState().input.joystick)<.01);await page.waitForTimeout(20)}
async function runCatch(page,startInput,distance,shot){await page.evaluate(()=>__TMB_A12__.startRoute('D01'));await place(page,520-32-distance);await startInput();let catchT=null,topT=null,starts=0,was=false,maxPen=0,inputAccepted=false;for(let i=0;i<150;i++){const s=await step(page),active=!!s.edgeClimb;inputAccepted||=active;if(active&&!was)starts++;was=active;if(active&&s.edgeClimb.phase==='catch'&&catchT===null){catchT=s.gameClock;if(shot)await page.screenshot({path:path.join(evidence,shot)})}const ox=Math.min(s.player.x+32,1050)-Math.max(s.player.x,520),oy=Math.min(s.player.y+48,495)-Math.max(s.player.y,395);if(ox>0&&oy>0)maxPen=Math.max(maxPen,Math.min(ox,oy));if(catchT!==null&&!active&&s.player.onGround&&s.player.y+48<=395.01){topT=s.gameClock;break}}const end=await page.evaluate(()=>__TMB_A12__.getState());return {distance,starts,catchToTop:topT-catchT,deaths:end.campaignDeaths,maxPen,pending:end.vectorJumpPending,inputAccepted,top:!!topT}}

async function tapKey(page,key,ms=90){await page.keyboard.down(key);await page.waitForTimeout(ms);await page.keyboard.up(key)}
async function runD01(page,mode,session){const seed=20261002,started=Date.now(),log=[];let joy;
 if(mode==='keyboard'){await keyboardStart(page)}else{const box=await page.locator('#joystick').boundingBox();joy={x:box.x+box.width*.88,y:box.y+box.height/2,id:1,radiusX:2,radiusY:2,force:1};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[joy]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[joy]});await page.waitForFunction(()=>__TMB_A12__.getState().input.joystick>.12)}
 const action=async key=>{if(mode==='keyboard')return tapKey(page,key);if(key==='ArrowDown')return tapKey(page,key);const b=await page.locator('#jumpWrap button').boundingBox(),p={x:b.x+b.width/2,y:b.y+b.height/2,id:2,radiusX:2,radiusY:2,force:1};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[joy,p]});await page.waitForTimeout(80);await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[joy]})};
 let lastAction=-999,lastX=0;while(Date.now()-started<120000){const s=await page.evaluate(()=>__TMB_A12__.getState());if(s.campaignDeaths)throw new Error(`CZ-6 death x=${s.player.x} state=${s.player.state} inputs=${JSON.stringify(log.slice(-20))}`);if(s.result||s.player.x>=10260){if(mode==='keyboard')await page.keyboard.up('ArrowRight');else await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});return {seconds:(Date.now()-started)/1000,deaths:s.campaignDeaths,chief:s.chief.catches,seed,x:s.player.x,result:s.result}}
 const x=s.player.x,near=s.route.obstacles.find(o=>o.x-x>0&&o.x-x<115);if(near&&x-lastAction>35){const key=near.type==='slide'?'ArrowDown':'ArrowUp';await action(key);log.push({t:Date.now()-started,x:+x.toFixed(1),key,id:near.id});lastAction=x}else if(s.player.onGround&&x-lastAction>430){await action('ArrowUp');log.push({t:Date.now()-started,x:+x.toFixed(1),key:'ArrowUp',id:'surface'});lastAction=x}lastX=x;await step(page);await page.waitForTimeout(16)}throw new Error(`CZ-6 timeout x=${lastX} inputs=${JSON.stringify(log.slice(-20))}`)}

test('CZ-6 full D01 keyboard',async({page})=>{await open(page);const r=await runD01(page,'keyboard');console.log('CZ6',JSON.stringify({channel:'keyboard',...r}));expect(r.x).toBeGreaterThanOrEqual(10260);expect(r.deaths).toBe(0);expect(r.chief).toBe(0)});
test('CZ-6 full D01 touch 844x390',async({browser})=>{const context=await browser.newContext({hasTouch:true,viewport:{width:844,height:390}}),page=await context.newPage(),session=await context.newCDPSession(page);await open(page);const r=await runD01(page,'touch',session);console.log('CZ6',JSON.stringify({channel:'touch',...r}));expect(r.x).toBeGreaterThanOrEqual(10260);expect(r.deaths).toBe(0);expect(r.chief).toBe(0);await context.close()});

test('CZ-1 keyboard distance scan',async({page})=>{await open(page);const rows=[];for(let d=0;d<=96;d+=8){const r=await runCatch(page,()=>keyboardStart(page),d,d===96?'kb-catch.png':null);rows.push(r);await page.keyboard.up('ArrowUp');await page.keyboard.up('ArrowRight')}console.log('CZ1',JSON.stringify(rows));for(const r of rows){expect(r.starts).toBe(1);expect(r.top).toBeTruthy();expect(r.deaths).toBe(0);expect(r.maxPen).toBeLessThanOrEqual(2);expect(r.pending).toBeNull();expect(r.catchToTop).toBeGreaterThanOrEqual(.16);expect(r.catchToTop).toBeLessThanOrEqual(.24)}});

for(const viewport of [{width:390,height:844},{width:844,height:390}])test(`CZ-2 touch distance scan ${viewport.width}x${viewport.height}`,async({browser})=>{const context=await browser.newContext({hasTouch:true,viewport}),page=await context.newPage(),session=await context.newCDPSession(page);await open(page);const rows=[];for(let d=0;d<=96;d+=8){const r=await runCatch(page,()=>touchStart(page,session),d,d===96?`touch-catch-${viewport.width}x${viewport.height}.png`:null);rows.push(r);await touchEnd(page,session)}console.log('CZ2',JSON.stringify({viewport,rows}));for(const r of rows){expect(r.inputAccepted,'R5 girdi ulaşmadı').toBeTruthy();expect(r.starts).toBe(1);expect(r.top).toBeTruthy();expect(r.deaths).toBe(0);expect(r.maxPen).toBeLessThanOrEqual(2);expect(r.catchToTop).toBeGreaterThanOrEqual(.16);expect(r.catchToTop).toBeLessThanOrEqual(.24)}await context.close()});

test('CZ-3 outside zone then face contact',async({page})=>{await open(page);const rows=[];for(const d of [130,160]){await page.evaluate(()=>__TMB_A12__.startRoute('D01'));await place(page,520-32-d);await keyboardStart(page);const first=await step(page);const zoneStarts=Number(!!first.edgeClimb);await page.keyboard.up('ArrowUp');await page.keyboard.up('ArrowRight');await page.evaluate(()=>__TMB_A12__.startRoute('D01'));const near=await runCatch(page,()=>keyboardStart(page),0);await page.keyboard.up('ArrowUp');await page.keyboard.up('ArrowRight');rows.push({d,zoneStarts,nearStarts:near.starts})}console.log('CZ3',JSON.stringify(rows));for(const r of rows){expect(r.zoneStarts).toBe(0);expect(r.nearStarts).toBe(1)}});
