const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path'),crypto=require('crypto');
// FIXED BEFORE FIRST RUN: sample at 60 Hz; apex = launch feet minus minimum feet;
// penetration = max(min(x-overlap,y-overlap)) against the fixture wall; state order
// is first occurrence of jump/ catch/ climb/ grounded-top; ownership overlap counts
// edgeClimb active while wallMantle or wallRun is active. Thresholds are the brief's.
// T2C-2 FIXED BEFORE FIRST RUN: realtime evidence uses the live RAF loop and real
// ArrowRight/ArrowUp events. Sprite-mask evidence compares the same rendered state
// with the runner visible and hidden: >=20 crop pixels change by >20 in some RGB
// channel and max channel delta is >20. The same comparison 128 px left (known empty)
// must change zero pixels. Portrait canvas standard deviation remains >8.
const root=path.resolve(__dirname,'..'),evidence='E:/oyunlar/TrustMeBro/01-tasarim/vector-parkur/t2c';
let server,base,active='E';
const ground=[{x:0,y:455,w:3000,h:100,kind:'ground'}];
const defs={
 E:{profile:true,wall:{id:'e-wall',x:400,y:359,w:40,h:96}},
 E0:{profile:true,wall:{id:'e0-wall',x:400,y:359,w:40,h:96},marked:false},
 F:{profile:true,wall:{id:'f-wall',x:420,y:335,w:40,h:120},zone:{x1:180,x2:300}},
 F0:{profile:true,wall:{id:'f0-wall',x:420,y:335,w:40,h:120},marked:false},
 G:{profile:true,wall:{id:'g-wall',x:400,y:295,w:40,h:160}},
 N1:{profile:true,wall:{id:'n1-wall',x:400,y:359,w:40,h:96}},
 N2:{profile:true,wall:{id:'n2-wall',x:400,y:330,w:100,h:20}},
 N3:{profile:true,wall:{id:'n3-wall',x:400,y:359,w:40,h:96}},
 N4:{profile:true,wall:{id:'n4-wall',x:400,y:359,w:40,h:96}},
 K:{profile:true},K0:{profile:false}
};
function inject(source,name){const d=defs[name],routes=source.indexOf('const ROUTES = Object.freeze'),start=source.indexOf('    D01: {',routes),end=source.indexOf('    D02: {',start);let b=source.slice(start,end);b=b.replace(/      groundSegments: \[[\s\S]*?\r?\n      \],\r?\n      obstacles:/,`      groundSegments: ${JSON.stringify(ground)},\n      movementProfile: ${d.profile?"'vector-v1'":"null"},\n      catchableSurfaces: ${JSON.stringify(d.wall&&d.marked!==false?[{id:d.wall.id,dir:1}]:[])},\n      highJumpZones: ${JSON.stringify(d.zone?[d.zone]:[])},\n      obstacles:`);b=b.replace(/      obstacles: \[[\s\S]*?\r?\n      \],\r?\n      coins:/,`      obstacles: ${JSON.stringify(d.wall?[{...d.wall,type:'platform'}]:[])},\n      coins:`);return source.slice(0,start)+b+source.slice(end)}
test.beforeAll(async()=>{fs.mkdirSync(evidence,{recursive:true});server=http.createServer((req,res)=>{const u=new URL(req.url,'http://x'),rel=decodeURIComponent(u.pathname).replace(/^\/+/, '')||'index.html';if(rel==='index.html')active=u.searchParams.get('fixture')||'E';fs.readFile(path.join(root,rel),(e,body)=>{if(e){res.statusCode=404;return res.end('missing')}if(rel==='js/a12-campaign.js')body=Buffer.from(inject(body.toString('utf8'),active));res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':'application/octet-stream');res.end(body)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/index.html`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function open(page,name,viewport,realtime=false){active=name;if(viewport)await page.setViewportSize(viewport);await page.goto(`${base}?fixture=${name}#debug`);await page.waitForFunction(()=>window.__TMB_A12__);const c=page.locator('.characterChoice:visible').first();if(await c.count())await c.click();await page.evaluate(realtime=>{if(!realtime)__tmbParkour.manual();__TMB_A12__.startRoute('D01')},realtime)}
function depth(p,w){const ox=Math.min(p.x+32,w.x+w.w)-Math.max(p.x,w.x),oy=Math.min(p.y+48,w.y+w.h)-Math.max(p.y,w.y);return ox>0&&oy>0?Math.min(ox,oy):0}
async function drive(page,name,{jump=true,jumpFrame=35,start=170,reverse=false,release=false,noMove=false,frames=360}={}){const d=defs[name];await page.evaluate(x=>__TMB_A12__.placePlayer(x,407),start);if(!noMove){if(reverse)await page.keyboard.down('ArrowLeft');else await page.keyboard.down('ArrowRight')}const rows=[];for(let i=0;i<frames;i++){if(jump&&i===jumpFrame)await page.evaluate(()=>__tmbParkour.press());const s=await page.evaluate(()=>{__tmbCampaignStep(1/60);return __TMB_A12__.getState()});if(release&&i===52){await page.keyboard.up('ArrowRight');await page.keyboard.down('ArrowLeft')}rows.push({i,p:s.player,edge:s.edgeClimb,probe:s.edgeCatchProbe,mantle:s.wallMantle,deaths:s.campaignDeaths});if(s.player.onGround&&d.wall&&s.player.y+48<=d.wall.y+.01&&i>30)break}await page.keyboard.up('ArrowRight');await page.keyboard.up('ArrowLeft');return rows}
function metrics(name,rows){const w=defs[name].wall,phases=rows.map(r=>r.edge&&r.edge.phase),catchI=phases.indexOf('catch'),climbI=phases.indexOf('climb'),topI=rows.findIndex(r=>w&&r.p.onGround&&Math.abs(r.p.y+48-w.y)<=1),maxPen=w?Math.max(0,...rows.map(r=>depth(r.p,w))):0,overlap=rows.filter(r=>r.edge&&(r.mantle||r.p.state==='wallRun')).length,near=rows.flatMap(r=>(r.probe?.probes||[]).map(p=>({i:r.i,...p}))).filter(p=>p.gap<=18&&p.gap>=-2);return{catchI,climbI,topI,maxPen,overlap,deaths:Math.max(...rows.map(r=>r.deaths||0)),catchToTop:catchI>=0&&topI>=0?(rows[topI].t!=null?(rows[topI].t-rows[catchI].t)/1000:(topI-catchI)/60):null,topV:topI>=0?Math.max(...rows.slice(topI,topI+31).map(r=>Math.abs(r.p.vx))):0,near:near.slice(0,12)}}
async function shot(page,file,predicate){const s=await page.evaluate(()=>__TMB_A12__.getState());expect(predicate(s)).toBeTruthy();await page.screenshot({path:path.join(evidence,file)})}
async function liveRun(page,name,{viewport,jumpX,captures={}}){await open(page,name,viewport,true);await page.evaluate(()=>__TMB_A12__.placePlayer(170,407));await page.keyboard.down('ArrowRight');const rows=[],shots=[];let jumped=false,launch=-1;for(let i=0;i<720;i++){const sample=await page.evaluate(()=>({t:performance.now(),s:__TMB_A12__.getState()})),s=sample.s;if(!jumped&&s.player.x>=jumpX){await page.keyboard.down('ArrowUp');await page.waitForTimeout(34);await page.keyboard.up('ArrowUp');jumped=true}const now=await page.evaluate(()=>({t:performance.now(),s:__TMB_A12__.getState()}));if(launch<0&&!now.s.player.onGround)launch=now.t;rows.push({i,t:now.t,p:now.s.player,edge:now.s.edgeClimb,mantle:now.s.wallMantle,deaths:now.s.campaignDeaths});for(const [phase,file] of Object.entries(captures)){if(!shots.some(x=>x.file===file)&&((phase==='top'&&now.s.player.onGround&&defs[name].wall&&Math.abs(now.s.player.y+48-defs[name].wall.y)<=1&&now.s.player.vx>0)||now.s.edgeClimb?.phase===phase)){const pixel=await pixelMetrics(page,now.s);expect(pixel.positive.changed).toBeGreaterThanOrEqual(20);expect(pixel.positive.max).toBeGreaterThan(20);expect(pixel.negative.changed).toBe(0);const png=await page.screenshot({path:path.join(evidence,file)});shots.push({file,phase,md5:crypto.createHash('md5').update(png).digest('hex'),...pixel})}}if(jumped&&defs[name].wall&&now.s.player.onGround&&now.s.player.y+48<=defs[name].wall.y+.01&&i>40&&Object.keys(captures).every(phase=>shots.some(x=>x.phase===phase)))break;await page.waitForTimeout(8)}await page.keyboard.up('ArrowRight');return{rows,shots,launch}}
async function pixelMetrics(page,s){return page.evaluate(s=>{const c=document.querySelector('#game'),g=c.getContext('2d');__tmbCampaignDraw();const tr=g.getTransform(),logicalW=s.viewport.w,estimatedCam=Math.max(0,s.player.x-logicalW*.3),x=Math.round(tr.a*(s.player.x-estimatedCam)+tr.e),y=Math.round(tr.d*(s.player.y+s.cameraWorldY)+tr.f),w=Math.max(1,Math.round(tr.a*32)),h=Math.max(1,Math.round(tr.d*48)),read=rx=>g.getImageData(Math.max(0,rx),Math.max(0,y),Math.min(w,c.width-Math.max(0,rx)),Math.min(h,c.height-Math.max(0,y))).data,visible=read(x),emptyVisible=read(x-128),all=g.getImageData(0,0,c.width,c.height).data;__TMB_A12__.setPlayerVisible(false);__tmbCampaignDraw();const hidden=read(x),emptyHidden=read(x-128);__TMB_A12__.setPlayerVisible(true);__tmbCampaignDraw();const diff=(a,b)=>{let changed=0,max=0;for(let i=0;i<Math.min(a.length,b.length);i+=4){let hit=false;for(let k=0;k<3;k++){const d=Math.abs(a[i+k]-b[i+k]);max=Math.max(max,d);if(d>20)hit=true}if(hit)changed++}return{changed,max}};let n=0,sum=0,sum2=0;for(let i=0;i<all.length;i+=4)for(let k=0;k<3;k++){const v=all[i+k];n++;sum+=v;sum2+=v*v}return{positive:diff(visible,hidden),negative:diff(emptyVisible,emptyHidden),canvasStd:Math.sqrt(sum2/n-(sum/n)**2),screen:{x,y,w,h}}},s)}
test('E catches, climbs, resumes running, and captures realtime evidence',async({page})=>{const live=await liveRun(page,'E',{jumpX:300,captures:{catch:'e-catch.png',climb:'e-climb-mid.png',top:'e-top-run.png'}}),m=metrics('E',live.rows);await open(page,'E',{width:390,height:844},true);const portrait=await liveRun(page,'E',{viewport:{width:390,height:844},jumpX:300,captures:{climb:'e-climb-mid-390x844.png'}});const shots=[...live.shots,...portrait.shots];console.log('T2C_E_REALTIME',JSON.stringify({metrics:m,launch:live.launch,shots}));expect(m.catchI).toBeGreaterThanOrEqual(0);expect(m.climbI).toBeGreaterThan(m.catchI);expect(m.topI).toBeGreaterThan(m.climbI);expect(m.catchToTop).toBeGreaterThanOrEqual(.6);expect(m.catchToTop).toBeLessThanOrEqual(1);expect(m.maxPen).toBeLessThanOrEqual(2);expect(m.topV).toBeGreaterThanOrEqual(200);expect(m.deaths).toBe(0);expect(shots).toHaveLength(4);for(const s of shots)expect(s.regionDiff).toBeGreaterThan(12);expect(portrait.shots[0].canvasStd).toBeGreaterThan(8);global.__t2cShots=shots});
test('F realtime high jump catches while F0 cannot reach wall top',async({page})=>{const live=await liveRun(page,'F',{jumpX:245,captures:{catch:'f-catch.png'}}),fm=metrics('F',live.rows),catchTime=fm.catchI>=0&&live.launch>=0?(live.rows[fm.catchI].t-live.launch)/1000:-1;const shots=live.shots;console.log('T2C_F_REALTIME',JSON.stringify({...fm,catchTime,shots}));expect(fm.catchI).toBeGreaterThan(0);expect(fm.topI).toBeGreaterThan(fm.catchI);expect(catchTime).toBeGreaterThanOrEqual(0);expect(catchTime).toBeLessThanOrEqual(.9);expect(shots).toHaveLength(1);const all=[...(global.__t2cShots||[]),...shots];expect(new Set(all.map(x=>x.md5)).size).toBe(5);await open(page,'F0');const f0=await drive(page,'F0',{jumpFrame:25}),f0m=metrics('F0',f0),minTop=Math.min(...f0.map(r=>r.p.y));console.log('T2C_F0',JSON.stringify({...f0m,minPlayerTop:minTop,wallTop:defs.F0.wall.y}));expect(f0m.catchI).toBe(-1);expect(minTop).toBeGreaterThan(defs.F0.wall.y);expect(f0m.maxPen).toBeLessThanOrEqual(2);expect(f0m.deaths).toBe(0)});
test('G E0 and N1-N4 reject invalid catches',async({page})=>{const out={};for(const name of ['G','E0','N1','N2','N3','N4']){await open(page,name);let opts={};if(name==='N1')opts={start:520,reverse:true};if(name==='N2')opts={start:420,noMove:true};if(name==='N3')opts={jump:false};if(name==='N4')opts={start:350,reverse:true};const rows=await drive(page,name,opts),m=metrics(name,rows);out[name]=m;expect(m.catchI).toBe(-1);expect(m.climbI).toBe(-1);expect(m.deaths).toBe(0);expect(m.maxPen).toBeLessThanOrEqual(2)}console.log('T2C_NEGATIVES',JSON.stringify(out))});
test('K jump apex is profiled, capped with jumpLevel, and legacy when disabled',async({browser})=>{const values={};for(const [name,level,key] of [['K',false,'profile'],['K0',false,'legacy'],['K0',true,'legacyJumpLevel'],['K',true,'profileJumpLevel']]){active=name;const context=await browser.newContext();const save={v36:{v:36,partCount:6,currentLevel:1,currentPart:1,deaths:0,jumpLevel:level?1:0,speedLevel:0,totalTime:0,won:false,collected:new Array(31).fill(0),character:0}};await context.addInitScript(save=>localStorage.setItem('trust_me_bro_last_delivery_v2_save',JSON.stringify(save)),save);const page=await context.newPage();await page.goto(`${base}?fixture=${name}#debug`);await page.waitForFunction(()=>window.__TMB_A12__);await page.evaluate(()=>{__tmbParkour.manual();__TMB_A12__.startRoute('D01')});const feet=[455];await page.evaluate(()=>__tmbParkour.press());for(let i=0;i<150;i++){await page.evaluate(()=>__tmbCampaignStep(1/60));const p=await page.evaluate(()=>__TMB_A12__.getState().player);feet.push(p.y+48);if(i>10&&p.onGround)break}values[key]=455-Math.min(...feet);await context.close()}console.log('T2C_JUMPS',JSON.stringify(values));expect(values.profile).toBeGreaterThanOrEqual(48);expect(values.profile).toBeLessThanOrEqual(67);expect(values.legacy).toBeGreaterThanOrEqual(102.11);expect(values.legacy).toBeLessThanOrEqual(104.11);expect(values.legacyJumpLevel).toBeGreaterThanOrEqual(values.legacy+40);expect(values.profileJumpLevel).toBeGreaterThanOrEqual(48);expect(values.profileJumpLevel).toBeLessThanOrEqual(67)});
test('single state owner has zero overlap',async({page})=>{let overlap=0;for(const name of Object.keys(defs)){await open(page,name);const rows=await drive(page,name,{frames:180});overlap+=metrics(name,rows).overlap}console.log('T2C_OWNER',JSON.stringify({overlap}));expect(overlap).toBe(0)});
test('expired jump request does not overwrite a later vertical impulse',async({page})=>{await open(page,'K');await page.evaluate(()=>__TMB_A12__.placePlayer(200,350));await page.keyboard.press('ArrowUp');await page.evaluate(()=>{__tmbCampaignStep(1/60);__tmbCampaignStep(1/60)});const expired=await page.evaluate(()=>__TMB_A12__.getState().vectorJumpPending);await page.evaluate(()=>__TMB_A12__.placePlayer(200,300));await page.evaluate(()=>__tmbCampaignStep(1/60));const after=await page.evaluate(()=>__TMB_A12__.getState().player.vy);console.log('T2C_PENDING',JSON.stringify({expired,after,overwritten:after===-390}));expect(expired).toBeNull();expect(after).toBeGreaterThan(0);expect(after).not.toBe(-390)});
