const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path'),crypto=require('crypto');
// FIXED BEFORE FIRST RUN (T2C-2): RAF/performance.now supplies all realtime times.
// Drop height is landing feet minus the minimum feet since the last grounded sample.
// Roll ownership is the increase in vectorRollStarts and each H/J must increase exactly once.
// Collision depth is min positive x/y overlap against the unchanged solid fixture box.
// Sprite-mask evidence compares the same rendered state with the runner visible and hidden:
// >=20 pixels in the player crop must change and max channel delta must exceed 20; the
// identical comparison in a known-empty crop 128 px left must change zero pixels.
// These recipes and thresholds are frozen before the first run.
const root=path.resolve(__dirname,'..'),evidence='E:/oyunlar/TrustMeBro/01-tasarim/vector-parkur/t2c';
let server,base,active='H';
const ground=[{x:0,y:455,w:3000,h:100,kind:'ground'}];
const defs={
 H:{profile:true,start:{x:180,y:77}},H1:{profile:true,start:{x:180,y:287}},H0:{profile:false,start:{x:180,y:77}},
 J:{profile:true,start:{x:170,y:407},box:{id:'j-box',x:400,y:433,w:72,h:22},zone:{x1:200,x2:352,landX:500,landY:455}},
 J0:{profile:true,start:{x:170,y:407},box:{id:'j0-box',x:400,y:433,w:72,h:22}}
};
function inject(source,name){const d=defs[name],routes=source.indexOf('const ROUTES = Object.freeze'),start=source.indexOf('    D01: {',routes),end=source.indexOf('    D02: {',start);let b=source.slice(start,end);b=b.replace(/      groundSegments: \[[\s\S]*?\r?\n      \],\r?\n      obstacles:/,`      groundSegments: ${JSON.stringify(ground)},\n      movementProfile: ${d.profile?"'vector-v1'":"null"},\n      catchableSurfaces: [],\n      highJumpZones: [],\n      diveZones: ${JSON.stringify(d.zone?[d.zone]:[])},\n      obstacles:`);b=b.replace(/      obstacles: \[[\s\S]*?\r?\n      \],\r?\n      coins:/,`      obstacles: ${JSON.stringify(d.box?[{...d.box,type:'platform'}]:[])},\n      coins:`);return source.slice(0,start)+b+source.slice(end)}
test.beforeAll(async()=>{fs.mkdirSync(evidence,{recursive:true});server=http.createServer((req,res)=>{const u=new URL(req.url,'http://x'),rel=decodeURIComponent(u.pathname).replace(/^\/+/, '')||'index.html';if(rel==='index.html')active=u.searchParams.get('fixture')||'H';fs.readFile(path.join(root,rel),(e,body)=>{if(e){res.statusCode=404;return res.end('missing')}if(rel==='js/a12-campaign.js')body=Buffer.from(inject(body.toString('utf8'),active));res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':'application/octet-stream');res.end(body)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/index.html`});
test.afterAll(async()=>new Promise(r=>server.close(r)));
async function open(page,name){active=name;await page.goto(`${base}?fixture=${name}#debug`);await page.waitForFunction(()=>window.__TMB_A12__);const c=page.locator('.characterChoice:visible').first();if(await c.count())await c.click();await page.evaluate(()=>__TMB_A12__.startRoute('D01'));const d=defs[name];await page.evaluate(p=>__TMB_A12__.placePlayer(p.x,p.y),d.start)}
function depth(p,b){if(!b)return 0;const ox=Math.min(p.x+32,b.x+b.w)-Math.max(p.x,b.x),oy=Math.min(p.y+48,b.y+b.h)-Math.max(p.y,b.y);return ox>0&&oy>0?Math.min(ox,oy):0}
async function spriteMask(page,s,file){const m=await page.evaluate(async s=>{const c=document.querySelector('#game'),g=c.getContext('2d');__tmbCampaignDraw();const tr=g.getTransform(),cam=Math.max(0,s.player.x-s.viewport.w*.3),x=Math.round(tr.a*(s.player.x-cam)+tr.e),y=Math.round(tr.d*(s.player.y+s.cameraWorldY)+tr.f),w=Math.max(1,Math.round(tr.a*32)),h=Math.max(1,Math.round(tr.d*48)),read=rx=>g.getImageData(Math.max(0,rx),Math.max(0,y),Math.min(w,c.width-Math.max(0,rx)),Math.min(h,c.height-Math.max(0,y))).data;const visible=read(x),emptyVisible=read(x-128);__TMB_A12__.setPlayerVisible(false);__tmbCampaignDraw();const hidden=read(x),emptyHidden=read(x-128);__TMB_A12__.setPlayerVisible(true);__tmbCampaignDraw();const diff=(a,b)=>{let changed=0,max=0;for(let i=0;i<Math.min(a.length,b.length);i+=4){let hit=false;for(let k=0;k<3;k++){const d=Math.abs(a[i+k]-b[i+k]);max=Math.max(max,d);if(d>20)hit=true}if(hit)changed++}return{changed,max}};return{positive:diff(visible,hidden),negative:diff(emptyVisible,emptyHidden),crop:{x,y,w,h}}},s);const pass=m.positive.changed>=20&&m.positive.max>20&&m.negative.changed===0;if(!pass)return{...m,pass:false};const png=await page.screenshot({path:path.join(evidence,file)});return{...m,pass:true,md5:crypto.createHash('md5').update(png).digest('hex')}}
async function live(page,name,{jumpX,shots={}}={}){await open(page,name);await page.keyboard.down('ArrowRight');const rows=[];let jumped=false,keyTime=null,landTime=null;for(let i=0;i<720;i++){const before=await page.evaluate(()=>({t:performance.now(),s:__TMB_A12__.getState()}));if(jumpX!=null&&!jumped&&before.s.player.x>=jumpX){await page.keyboard.down('ArrowUp');await page.waitForTimeout(30);await page.keyboard.up('ArrowUp');jumped=true;keyTime=before.t}let now=await page.evaluate(()=>({t:performance.now(),s:__TMB_A12__.getState()}));rows.push(now);if(jumped&&landTime==null&&now.s.player.onGround&&now.s.player.x>472&&now.s.parkour.state==='roll')landTime=now.t;for(const [state,file] of Object.entries(shots))if(!rows.some(r=>r.shot===file)&&now.s.parkour.state===state){await page.waitForTimeout(18);const drawn=await page.evaluate(()=>({t:performance.now(),s:__TMB_A12__.getState()}));if(drawn.s.parkour.state===state){const mask=await spriteMask(page,drawn.s,file);if(mask.pass){now.shot=file;now.mask=mask}}}if((name[0]==='H'&&now.s.player.onGround&&i>10&&now.s.parkour.state==='normal')||(jumped&&landTime!=null&&now.s.parkour.state==='normal'&&now.s.player.vx>0))break;await page.waitForTimeout(8)}await page.keyboard.up('ArrowRight');return{rows,keyTime,landTime}}
function summarize(name,r){const d=defs[name],states=r.rows.map(x=>x.s.parkour.state),land=d.box?r.rows.findIndex(x=>x.s.player.onGround&&x.s.parkour.state==='roll'):r.rows.findIndex(x=>x.s.player.onGround),pre=land>0?Math.abs(r.rows[land-1].s.player.vx):0,rollRows=r.rows.filter(x=>x.s.parkour.state==='roll'),minRatio=rollRows.length&&pre?Math.min(...rollRows.map(x=>Math.abs(x.s.player.vx)/pre)):null,minFeet=Math.min(...r.rows.map(x=>x.s.player.y+48)),landingFeet=land>=0?r.rows[land].s.player.y+48:null;return{states:[...new Set(states)],rollStarts:Math.max(...r.rows.map(x=>x.s.vectorRollStarts)),stun:states.includes('stun'),land,minRatio,drop:land>=0?landingFeet-minFeet:null,deaths:Math.max(...r.rows.map(x=>x.s.campaignDeaths||0)),maxPen:d.box?Math.max(...r.rows.map(x=>depth(x.s.player,d.box))):0,postVx:land>=0?r.rows.slice(land,land+61).map(x=>x.s.player.vx):[]}}
test('H large drop auto-rolls exactly once and preserves speed',async({page})=>{const r=await live(page,'H',{shots:{roll:'h-roll.png'}}),m=summarize('H',r),shot=r.rows.find(x=>x.shot)?.mask;console.log('T2C_H',JSON.stringify({...m,shot}));expect(m.drop).toBeGreaterThanOrEqual(200);expect(m.states).toContain('roll');expect(m.stun).toBe(false);expect(m.rollStarts).toBe(1);expect(m.minRatio).toBeGreaterThanOrEqual(.9);expect(m.postVx.some(v=>v>0)).toBe(true);expect(m.deaths).toBe(0)});
test('H1 small drop has no roll or stun',async({page})=>{const r=await live(page,'H1'),m=summarize('H1',r);console.log('T2C_H1',JSON.stringify(m));expect(m.drop).toBeLessThan(200);expect(m.states).not.toContain('roll');expect(m.stun).toBe(false);expect(m.rollStarts).toBe(0);expect(m.deaths).toBe(0)});
test('H0 legacy trace for parent comparison',async({page})=>{const r=await live(page,'H0'),m=summarize('H0',r),trace={states:r.rows.map(x=>x.s.parkour.state),vx:m.postVx.slice(0,31)};console.log('T2C_H0',JSON.stringify(trace));expect(m.rollStarts).toBe(0)});
test('J dives over solid box, rolls once, and resumes running',async({page})=>{const r=await live(page,'J',{jumpX:245,shots:{dive:'j-dive.png',roll:'j-roll.png'}}),m=summarize('J',r),duration=(r.landTime-r.keyTime)/1000,shotMasks=r.rows.filter(x=>x.mask).map(x=>x.mask);console.log('T2C_J',JSON.stringify({...m,duration,shotMasks}));expect(duration).toBeGreaterThanOrEqual(0);expect(duration).toBeLessThanOrEqual(.7);expect(m.states).toContain('dive');expect(m.states).toContain('roll');expect(m.rollStarts).toBe(1);expect(m.maxPen).toBe(0);expect(m.postVx.some(v=>v>=200)).toBe(true);expect(shotMasks).toHaveLength(2)});
test('J0 remains a normal Vector jump',async({page})=>{const r=await live(page,'J0',{jumpX:245}),m=summarize('J0',r);console.log('T2C_J0',JSON.stringify(m));expect(m.states).not.toContain('dive');expect(m.maxPen).toBe(0);expect(m.rollStarts).toBe(0)});
