const {test,expect}=require('playwright/test');
const fs=require('fs'),http=require('http'),path=require('path');
const root=path.resolve(__dirname,'..');
const evidence='E:/oyunlar/TrustMeBro/01-tasarim/vector-parkur/t2b';
let server,base,activeFixture=null,activeSlope=true,activeParallax=true;

const fixtures={
  A:{segments:[{x:0,y:455,w:284,h:100,kind:'ground'},{x:1000,y:859,w:9400,h:100,kind:'ground'}],slopes:[{id:'A-down',x1:300,y1:455,x2:1000,y2:859}]},
  B:{segments:[{x:0,y:455,w:284,h:100,kind:'ground'},{x:1032,y:200,w:9368,h:100,kind:'ground'}],slopes:[{id:'B-up',x1:300,y1:455,x2:1000,y2:200}]},
  C:{segments:[{x:0,y:455,w:184,h:100,kind:'ground'},{x:1800,y:1455,w:184,h:100,kind:'ground'},{x:3632,y:-445,w:6768,h:100,kind:'ground'}],slopes:[{id:'C-down',x1:200,y1:455,x2:1800,y2:1455},{id:'C-up',x1:2000,y1:1455,x2:3600,y2:-445}]},
  D:{segments:[{x:0,y:455,w:10400,h:100,kind:'ground'}],slopes:[]}
};

function injectFixture(source,name,enabled=true,parallax=true){
  const cfg=fixtures[name],routes=source.indexOf('const ROUTES = Object.freeze'),start=source.indexOf('    D01: {',routes),end=source.indexOf('    D02: {',start);
  let block=source.slice(start,end);
  block=block.replace(/      groundSegments: \[[\s\S]*?\r?\n      \],\r?\n      obstacles:/,`      groundSegments: ${JSON.stringify(cfg.segments)},\n      slopes: ${enabled?JSON.stringify(cfg.slopes):'[]'},\n      obstacles:`);
  block=block.replace(/      obstacles: \[[\s\S]*?\r?\n      \],\r?\n      coins:/,'      obstacles: [],\n      coins:');
  const injected=source.slice(0,start)+block+source.slice(end);
  return parallax?injected:injected.replace('const verticalParallax=Math.max(-.35*h,Math.min(.35*h,.25*(cameraWorldY-backgroundCameraWorldY)));','const verticalParallax=0;');
}

test.beforeAll(async()=>{fs.mkdirSync(evidence,{recursive:true});server=http.createServer((req,res)=>{const url=new URL(req.url,'http://x'),rel=decodeURIComponent(url.pathname).replace(/^\/+/, '')||'index.html';if(rel==='index.html'){activeFixture=url.searchParams.get('fixture');activeSlope=url.searchParams.get('slope')!=='off';activeParallax=url.searchParams.get('parallax')!=='off'}fs.readFile(path.join(root,rel),(error,body)=>{if(error){res.statusCode=404;return res.end('missing')}if(rel==='js/a12-campaign.js'&&fixtures[activeFixture])body=Buffer.from(injectFixture(body.toString('utf8'),activeFixture,activeSlope,activeParallax));res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':'application/octet-stream');res.end(body)})});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}/index.html`});
test.afterAll(async()=>new Promise(resolve=>server.close(resolve)));

async function open(page,name){page.on('pageerror',error=>console.log('T2B_PAGE_ERROR',error.message));activeFixture=name;activeSlope=true;activeParallax=true;await page.goto(`${base}?fixture=${name}#debug`);await page.waitForFunction(()=>window.__TMB_A12__);const choice=page.locator('.characterChoice:visible').first();if(await choice.count())await choice.click();await page.evaluate(()=>__TMB_A12__.startRoute('D01'))}
async function runRight(page,endX){await page.evaluate(()=>{window.__slopeSamples=[];const raw=window.__tmbCampaignStep;window.__tmbCampaignStep=dt=>{raw(dt);const s=__TMB_A12__.getState(),p=s.player;window.__slopeSamples.push({x:p.x,feet:p.y+s.hitbox.h,vx:p.vx,onGround:p.onGround,state:p.state,worldY:s.cameraWorldY})}});await page.keyboard.down('ArrowRight');await page.evaluate(end=>{for(let i=0;i<2000&&__TMB_A12__.getState().player.x<end;i++)__tmbCampaignStep(1/60)},endX);await page.keyboard.up('ArrowRight');const result=await page.evaluate(()=>window.__slopeSamples);expect(result.at(-1)?.x||0).toBeGreaterThanOrEqual(endX);return result}
function lineY(s,x){const t=(x-s.x1)/(s.x2-s.x1);return s.y1+(s.y2-s.y1)*t}
async function stepToEvidence(page,slope,targetX,file,expectedState){await page.keyboard.down('ArrowRight');const state=await page.evaluate(({slope,targetX})=>{for(let i=0;i<2000;i++){__tmbCampaignStep(1/60);const s=__TMB_A12__.getState(),cx=s.player.x+s.hitbox.w/2;if(cx>=targetX)return{centerX:cx,state:s.player.state}}throw new Error('evidence target not reached')},{slope,targetX});await page.keyboard.up('ArrowRight');expect(state.centerX).toBeGreaterThanOrEqual(slope.x1);expect(state.centerX).toBeLessThanOrEqual(slope.x2);if(expectedState)expect(state.state).toBe(expectedState);await page.waitForTimeout(40);await page.screenshot({path:path.join(evidence,file)});return state}
async function backgroundMetrics(page){await page.evaluate(()=>__tmbCampaignDraw());return page.evaluate(()=>{const canvas=document.querySelector('canvas'),c=canvas.getContext('2d'),W=canvas.width,H=canvas.height,d=c.getImageData(0,0,W,H).data,city=['#94bdce','#6f99aa'].map(s=>[parseInt(s.slice(1,3),16),parseInt(s.slice(3,5),16),parseInt(s.slice(5,7),16)]),near=(p,q,t)=>Math.abs(p[0]-q[0])<=t&&Math.abs(p[1]-q[1])<=t&&Math.abs(p[2]-q[2])<=t;let silhouetteY=H;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const i=(y*W+x)*4,p=[d[i],d[i+1],d[i+2]];if(city.some(q=>near(p,q,3)))silhouetteY=Math.min(silhouetteY,y)}const info=window.__tmbBackgroundDraw||{},tr=c.getTransform(),logicalBoundary=info.fillBoundary,boundary=logicalBoundary==null?null:Math.round(tr.f+tr.d*logicalBoundary),meanRow=y=>{const row=c.getImageData(0,Math.max(0,Math.min(H-1,y)),W,1).data,sum=[0,0,0];let n=0;for(let i=0;i<row.length;i+=4){if(row[i+3]){sum[0]+=row[i];sum[1]+=row[i+1];sum[2]+=row[i+2];n++}}return sum.map(v=>v/Math.max(1,n))};let seamDiff=[0,0,0];if(boundary!=null&&boundary>0&&boundary<H){const a=meanRow(boundary-1),b=meanRow(boundary);seamDiff=a.map((v,i)=>Math.abs(v-b[i]))}return{silhouetteY,canvas:{W,H},backgroundCalls:info.calls,seamDiff,boundary,offset:info.offset}})}

test('fixture A follows 30 degree descent and enters automatic slide',async({page})=>{await open(page,'A');const s=fixtures.A.slopes[0],evidenceState=await stepToEvidence(page,s,(s.x1+s.x2)/2,'slope-slide.png','slide');await open(page,'A');const rows=await runRight(page,1080),on=rows.filter(r=>r.x+16>=s.x1&&r.x+16<=s.x2),flat=rows.filter(r=>r.x>100&&r.x<260),errors=on.map(r=>Math.abs(r.feet-lineY(s,r.x+16))),down=on.filter(r=>r.state==='slide'),flatV=flat.reduce((n,r)=>n+Math.abs(r.vx),0)/flat.length,downV=down.reduce((n,r)=>n+Math.abs(r.vx),0)/down.length;console.log('T2B_SLOPE_A',JSON.stringify({samples:on.length,maxError:Math.max(...errors),fallThrough:on.filter(r=>!r.onGround).length,slide:down.length,flatV,downV,evidenceState}));expect(Math.max(...errors)).toBeLessThanOrEqual(2);expect(on.filter(r=>!r.onGround)).toHaveLength(0);expect(down.length).toBeGreaterThan(0);expect(downV).toBeGreaterThanOrEqual(flatV)});

test('fixture B follows uphill surface without downhill slide',async({page})=>{await open(page,'B');const s=fixtures.B.slopes[0],evidenceState=await stepToEvidence(page,s,(s.x1+s.x2)/2,'slope-uphill-middle.png');await open(page,'B');const rows=await runRight(page,1080),on=rows.filter(r=>r.x+16>=s.x1&&r.x+16<=s.x2),errors=on.map(r=>Math.abs(r.feet-lineY(s,r.x+16)));console.log('T2B_SLOPE_B',JSON.stringify({samples:on.length,maxError:Math.max(...errors),fallThrough:on.filter(r=>!r.onGround).length,slide:on.filter(r=>r.state==='slide').length,evidenceState}));expect(Math.max(...errors)).toBeLessThanOrEqual(2);expect(on.filter(r=>!r.onGround)).toHaveLength(0);expect(on.filter(r=>r.state==='slide')).toHaveLength(0)});

test('fixture C keeps runner visible, camera stable, and backdrop vertically anchored',async({browser})=>{for(const [w,h] of [[1280,720],[844,390],[390,844]]){const context=await browser.newContext({viewport:{width:w,height:h}}),page=await context.newPage();await open(page,'C');const shots=[];let jitter=0;for(const [tag,x,y] of [['start',220,467.5],['middle',1900,1455],['end',3500,-326.25]]){const worlds=await page.evaluate(({x,y})=>{__TMB_A12__.placePlayer(x,y-48);const a=[];for(let i=0;i<180;i++){__tmbCampaignStep(1/60);if(i>=120)a.push(__TMB_A12__.getState().cameraWorldY)}return a},{x,y});jitter=Math.max(jitter,...worlds.slice(2).map((v,i)=>Math.abs(v-2*worlds[i+1]+worlds[i])));const row=await page.evaluate(()=>{const s=__TMB_A12__.getState(),p=s.player,H=__tmb.layout.H||455;return{top:s.cameraWorldY+p.y,bottom:s.cameraWorldY+p.y+s.hitbox.h,H,worldY:s.cameraWorldY}});Object.assign(row,await backgroundMetrics(page));shots.push(row);if(w===390)await page.screenshot({path:path.join(evidence,`portrait-c-${tag}.png`)})}const silhouetteDelta=Math.abs(shots[1].silhouetteY-shots[0].silhouetteY);console.log('T2B_CAMERA_C',JSON.stringify({viewport:`${w}x${h}`,shots,jitter,silhouetteDelta}));expect(shots.filter(x=>x.top<0||x.bottom>x.H)).toHaveLength(0);expect(shots.every(x=>x.backgroundCalls===1)).toBeTruthy();expect(shots.every(x=>x.seamDiff.every(v=>v<=8))).toBeTruthy();if(w===1280||w===390)expect(silhouetteDelta).toBeGreaterThanOrEqual(.15*shots[0].canvas.H);expect(jitter).toBeLessThanOrEqual(2);await context.close()}
  activeFixture='C';activeParallax=false;const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();await page.goto(`${base}?fixture=C&parallax=off#debug`);await page.waitForFunction(()=>window.__TMB_A12__);await page.locator('.characterChoice:visible').first().click();await page.evaluate(()=>__TMB_A12__.startRoute('D01'));const ys=[];for(const [x,y] of [[220,467.5],[1900,1455]]){await page.evaluate(({x,y})=>{__TMB_A12__.placePlayer(x,y-48);for(let i=0;i<180;i++)__tmbCampaignStep(1/60)},{x,y});ys.push((await backgroundMetrics(page)).silhouetteY)}const delta=Math.abs(ys[1]-ys[0]);console.log('T2B_PARALLAX_ZERO',JSON.stringify({viewport:'390x844',silhouetteY:ys,delta}));expect(delta).toBe(0);await context.close();
  activeFixture=null;const dock=await browser.newContext({viewport:{width:1280,height:720}}),dpage=await dock.newPage();await dpage.goto(`${base}#debug`);await dpage.waitForFunction(()=>window.__TMB_A12__);await dpage.locator('.characterChoice:visible').first().click();await dpage.evaluate(()=>{__TMB_A12__.startRoute('D02');__TMB_A12__.placePlayer(1840,277);for(let i=0;i<120;i++)__tmbCampaignStep(1/60)});const dm=await backgroundMetrics(dpage);await dpage.screenshot({path:path.join(evidence,'d02-platform.png')});console.log('T2B_D02_BACKGROUND',JSON.stringify(dm));expect(dm.backgroundCalls).toBe(1);expect(dm.seamDiff.every(v=>v<=8)).toBeTruthy();for(const [id,world,x,y] of [['F01','frozen',760,250],['M01','magma',760,250],['A01','aftermath',760,250]]){await dpage.evaluate(({id,world,x,y})=>{__TMB_A12__.renderWorldOnRoute(world,id);__TMB_A12__.placePlayer(x,y);for(let i=0;i<90;i++)__tmbCampaignStep(1/60)},{id,world,x,y});await dpage.evaluate(()=>__tmbCampaignDraw());await dpage.screenshot({path:path.join(evidence,`${id.toLowerCase()}-platform.png`)})}await dock.close()});

test('fixture D is bit-identical with slope gate off and on',async({browser})=>{const traces=[];for(const mode of ['off','on']){activeFixture='D';activeSlope=mode!=='off';const context=await browser.newContext({viewport:{width:1280,height:720}}),page=await context.newPage();await page.goto(`${base}?fixture=D&slope=${mode}#debug`);await page.waitForFunction(()=>window.__TMB_A12__);await page.locator('.characterChoice:visible').first().click();await page.evaluate(()=>__TMB_A12__.startRoute('D01'));const rows=await runRight(page,500),steady=rows.filter(r=>Math.abs(r.vx)===255).slice(0,60),x0=steady[0].x;traces.push(steady.map(r=>[r.x-x0,r.feet,r.vx,r.onGround,r.state,r.worldY]));await context.close()}console.log('T2B_FLAT_D',JSON.stringify({samples:traces[0].length,equal:JSON.stringify(traces[0])===JSON.stringify(traces[1])}));expect(traces[1]).toEqual(traces[0])});

test('intentional red positive control',()=>{expect(process.env.TMB_T2B_FORCE_RED==='1'?1:0).toBe(0)});
