from pathlib import Path
import json,hashlib,subprocess,sys,datetime
r=Path(__file__).resolve().parents[2];c=json.loads((r/'sprites/a5/atlas-contract.json').read_text())
pre={a['path']:a['sha256'] for a in c['assets']}
subprocess.run([sys.executable,str(r/'tools/a5/generate_placeholders.py')],check=True)
assert all(hashlib.sha256((r/p).read_bytes()).hexdigest()==h for p,h in pre.items())
(r/'03-test/a5a1-evidence/reproducibility.json').write_text(json.dumps({'status':'PASS','files':34,'algorithm':'second generation SHA256 == first generation SHA256'}))
lines=['# A5 Asset Manifest','', '## A5a1 placeholder contract','', 'Runtime integration: DEFERRED to A5a2. These files are not loaded by the game yet. Art is PLACEHOLDER; visual acceptance DEFERRED. No final art approval is claimed.','', 'Source: `tools/a5/generate_placeholders.py`, original procedural shapes; project-owner artwork, no third-party visual input. Generator dependency: installed Pillow 12.3.0. Reproduce: `python tools/a5/generate_placeholders.py`. Check: `python 03-test/a5-assets-check.py`.','', 'Machine-readable contract: `sprites/a5/atlas-contract.json`. 512x512 RGBA atlas, 8x8 cells of 64x64; anchor (32,56); transparent padding >=4px. Standing reference hitbox (16,8,32,48); renderer must never modify player geometry. Existing slide/crouch geometry remains 32x24.','', 'Right-facing source; mirror left around x=32. Layer order: body, bag, vest, helmet, eyewear. Draw cell at (player center x - 32, player feet y - 56). Flip/roll rotate artwork around cell center, not collision geometry. Frames already contain pose transforms: do not apply a second rotation in runtime.','', 'Cache: load each atlas with `?v=<cacheVersion>` from the contract. Final-art replacement MUST regenerate SHA256/cacheVersion; same filename without updated content hash is invalid. Max 524288 bytes/file. Straight alpha; no opaque background.','', 'Timing: idle/run use game time; action frames follow normalized existing mechanic phase (floor(progress*8), clamped 0..7). Durations below are authoring references only and cannot change physics. FrontFlip tuck frames 2..5 must be selected during the existing tuck phase; phase-local mapping is required in A5a2.','', '| Motion | Row | Frames | Reference duration / FPS | Loop |','|---|---:|---|---|---|']
for a,m in c['motions'].items():lines.append(f"| {a} | {m['row']} | 0–7 | {m['duration_s']}s / {m['fps']:.3f} | {m['loop']} |")
lines+=['','Every row: implementation=IMPLEMENTED (generated asset only); functional_test=PASSED (offline contract only); art=PLACEHOLDER; visual_acceptance=DEFERRED. Runtime functional acceptance NOT_TESTED.','','| Asset | Bytes | SHA256 | Cache version |','|---|---:|---|---|']
for a in c['assets']:
 a['functional_test']='PASSED_OFFLINE_CONTRACT'
 lines.append(f"| `{a['path']}` | {a['bytes']} | `{a['sha256']}` | `{a['cacheVersion']}` |")
lines+=['','## A5a2 integration / save contract (not implemented in A5a1)','', '- Keep PROFILE_KEY and schema v1: additive migration, no key rename or balance reset. Add ownedRunnerIds=[male,female]; both free. Preserve runnerId, walletBalance, world ownership, all route progress/pending/best/banked runs, legacy flags and existing settings. Normalize each runner equipped set to owned valid IDs, otherwise default. Migration must be idempotent.', '- Shared ownedOutfitSetIds unlocks purchase for both runners; equippedOutfitByRunner remains independent. Default 0, Dock Crew 40, Night Shift 240, Hazard Runner 360. Add registry products and shop entries in A5a2. A repeated purchase charges zero; insufficient balance leaves data unchanged; persistence failure is tested against current persist rollback semantics.', '- Existing settings.language remains unchanged. No new setting is required for A5a runner/outfit choice.', '- Permitted index presentation points: drawCourier, drawDispatch renderer invocation, sprite loader/preview helpers; UI/sound/language presentation only in later scoped A5 packages. Input/physics functions and listeners are forbidden. Exact conservative block hashes are in 03-test/a5a1-evidence/index-protected-functions.json.', '- Permitted a12 regions in A5a2: OUTFITS, baseProfile/normalizeProfile additive fields, outfit shop rendering/selection/purchase, runner render adapter; DEBUG-only test hooks. No route/coin/chief/physics changes.', '- Runtime gates deferred: all-frame outfit-animation-matrix in live renderer, purchase once/shared unlock/per-runner wear, old save migration/reload, cache replacement, engine animation phase/anchor alignment. Offline matrix cannot replace these tests.','', '## Remaining inventory / art handoff','', 'Existing sprites, soundtrack, logo: previous-version assets; license provenance not audited here. Full runtime manifest and audio provenance belong to A5c; do not infer license clearance. Female/base placeholders and all outfit layers need final art replacement and renewed visibility/performance acceptance. Existing world NPC art remains unchanged.']
(r/'ASSET-MANIFEST.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
# Keep generated JSON deterministic: statuses remain NOT_TESTED in generator output; evidence/manifest carry verification results.
with (r/'03-test/TN-A5-PROGRESS.md').open('a',encoding='utf-8') as f:f.write('\n'+datetime.datetime.now().isoformat()+' — 34 atlases generated; 128 combinations / 1024 frames / 5120 layer samples PASS; 8 negative controls rejected; regeneration SHA identical. Runtime source unchanged. Starting preservation gates.\n')
print('manifest and reproducibility saved')
